### ISSUE TITLE
Option to not optimize any images

### ISSUE THREAD

**Issue by wasamasa** [ciromattia/kcc#105]
Suppose my sources are bad. Really bad. So bad that any quality option I throw at it makes the output quality worse and the archives larger than they used to be. I'd usually go for `--noprocessing` to leave them untouched but I still want to have features like rotation or splitting used for the few pages that can be split. Perhaps there is a way to do the same as Photoshop's "Save as" command which automatically detects the compression used and offers it for not needlessly recompressing the image.

Is there any option for this behaviour I've overlooked? If not, I'm all in for it.

**Comment by StudioEtrange** [comment]
"Not soon" is still not yet in 2021 ? :D
