### ISSUE TITLE
WinError 5

### ISSUE THREAD

**Issue by matyro** [ciromattia/kcc#125]
I have this error when i try to convert a manga (translate to English):
-------------------------------------------------------------------------------------------------------------------
[WinError 5] access deny: 'C:\\...\\AppData\\local\Temp\\KCC-TMP-6tijioj6\\OEBPS\\Images\\Manga Name 61' -> 'C:\\...\\AppData\\local\Temp\\KCC-TMP-6tijioj6\\OEBPS\\Images\\Manga-Name-61' 

Traceback:
File "kcc\KCC_gui.py", line 429, in run
File "kcc\comic2ebook.py", line 1145, in makeBook
File "kcc\comic2ebook.py", line 734, in sanitizeTree

--------------------------------------------------------------------------------------------------------------------

I convert from images to kindle paperwhite on Windows 8.1 x64
Directory structure:

Manga Name
|__ Chapter 1 
|          |_ Image 1
|          |_ Image 2
|          |_ Image ...
|__ Chapter 2 
|         |_ Image 1
|          |_ Image 2
|          |_ Image ...
|__ ...

Conversion of single files or chapters seems to work

**Comment by AcidWeb** [comment]
Something lock directory and prevent name change. Try disable your AV or other software that might use that directory and let me know if that help.

**Comment by matyro** [comment]
AV deactivated, KCC with UAC admin privileges seems to work,

last version worked with Avira on

**Comment by AcidWeb** [comment]
Admin privileges are not necessary.

Nothing changed in last few versions that can cause that - it is random problem that should no longer occur. Even with AV so shitty like Avira.

I will try to invent yet-another layer of workarounds.
