### ISSUE TITLE
Kindlegen hangs up

### ISSUE THREAD

**Issue by frothking** [ciromattia/kcc#132]
I think your software is amazing. Keep up the good work. Im having some issues when converting some files.

I am running windows 8.1 with the latest version of kindlegen (2.9).

When I convert to mobi kindlegen keeps running even when the mobi output file is created. KCC appears to hang up, since it's waiting for kindlegen (I think).
I kill the kindlegen process, and KCC process the mobi output file as usual, and goes to the next comic.
I tried to convert an epub created by KCC with kindlegen, and kindlegen hangs up, as i suspected.

Can you recommend me some outdated version of kindlegen that works with kcc?
Update - tested with kindlegen 2.8 and the problem persists.

Here's the kindlegen output

*************************************************************
 Amazon kindlegen(Windows) V2.9 build 1029-0897292
 A command line e-book compiler
 Copyright Amazon.com and its Affiliates 2014
*************************************************************

Info(prcgen):I1047: Added metadata dc:Title        "[Title]"
Info(prcgen):I1047: Added metadata dc:Creator      "KCC"
Info(prcgen):I1047: Added metadata fixed-layout    "true"
Info(prcgen):I1047: Added metadata book-type       "comic"
Info(prcgen):I1047: Added metadata orientation-lock "portrait"
Info(prcgen):I1047: Added metadata original-resolution "600x800"
Info(prcgen):I1047: Added metadata zero-gutter     "true"
Info(prcgen):I1047: Added metadata zero-margin     "true"
Info(prcgen):I1002: Parsing files  0000320
Info(cssparser):I10004: @rules other than @import, @charset and @font-face are n
ot supported.
Info(prcgen):I1047: Added metadata region-mag  "true"
Info(prcgen):I1015: Building PRC file
Info(prcgen):I1006: Resolving hyperlinks
Info(prcgen):I1049: Building table of content     URL: [PATH]
Warning(prcgen):W14019: Cover is too small :   [PATH]
Info(pagemap):I8000: No Page map found in the book
Info(prcgen):I1045: Computing UNICODE ranges used in the book
Info(prcgen):I1046: Found UNICODE range: Basic Latin [20..7E]
Info(prcgen):I1017: Building PRC file, record count:   0000123
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  2
4.36%
Info(prcgen):I1040: The document identifier is: "TITLE"
Info(prcgen):I1041: The file format version is V6
Info(prcgen):I1031: Saving PRC file
Info(prcgen):I1033: PRC built with WARNINGS!
Info(prcgen):I1016: Building enhanced PRC file
Info(prcgen):I1007: Resolving mediaidlinks
Info(prcgen):I1011: Writing mediaidlinks
Info(prcgen):I1009: Resolving guide items
Warning(prcgen):W14019: Cover is too small :   [PATH]
Info(prcgen):I1046: Found UNICODE range: [PATH]
Info(prcgen):I1017: Building PRC file, record count:   0000187
Info(prcgen):I1039: Final stats - text compressed to (in % of original size):  3
5.81%
Info(prcgen):I1040: The document identifier is: [PATH]
Info(prcgen):I1041: The file format version is V8
Info(prcgen):I1032: PRC built successfully
Info(prcgen):I15000:  Approximate Standard Mobi Deliverable file size :   002409
9KB
Info(prcgen):I15001:  Approximate KF8 Deliverable file size :   0024270KB
Info(prcgen):I1037: Mobi file built with WARNINGS!

**Comment by AcidWeb** [comment]
Interesting.

KindleGen hang on "Info(prcgen):I1037: Mobi file built with WARNINGS!"?

**Comment by frothking** [comment]
Yes.

I think the only warning is "cover is too small" but KCC already scales it to the size of my device (Kindle 6/2014/KT2)

Also when I tried to use 2.8 KCC displayed a warning saying kindlegen was outdated, so I guess using some older version wont fix the problem.

**Comment by AcidWeb** [comment]
There is nothing wrong with this KindleGen output - it is looking like it should be.

Well for sure it is not KCC problem. Something is messing with KindleGen. Try disabling AV (or other real-time scanners) for while and convert that EPUB once again.

**Comment by frothking** [comment]
Fixed. It was G-Buster Browser Protection, a security program installed by my bank. Thanks for your help.
