### ISSUE TITLE
unrar not found

### ISSUE THREAD

**Issue by Maxiride** [ciromattia/kcc#133]
Hello, just downloaded your tool and added kindlegen to the installation folder.
However when trying to convert from cbr to mobi for my kindle touch 7th gen I get this error: http://prntscr.com/6youyg

However the unrar.exe is correctly placed inside the program folder along with kindle gen.

**Comment by AcidWeb** [comment]
KCC don't display warning about missing unrar during startup?

**Comment by Maxiride** [comment]
Nope, no errors are shown nor in KCC nor in any alert popups. I've also tried executing KCC as administrator.

**Comment by AcidWeb** [comment]
Unrar is crashing during unpacking.

Show me full path to file + file name.

**Comment by Maxiride** [comment]
Path to file: D:\Federico\Download\XDCC - Torrent - ecc\Torrent\Completati\Bakuman vol. 1-4\Bakuman pack vol. 1-4.cbr

Path to KCC: C:\Program Files\Kindle Comic Converter

**Comment by AcidWeb** [comment]
I presume you can unpack that file without any problem?

**Comment by Maxiride** [comment]
yep, I can extract it with 7z without any issue and most files looks ok. But it is a 200mb cbr of 4 volumes so i can't check image by image xD

**Comment by AcidWeb** [comment]
Open console in KCC directory and try to start unrar.exe manually. Any errors?

**Comment by Maxiride** [comment]
Nope no errors:
```
C:\Program Files\Kindle Comic Converter>unrar.exe

UNRAR 5.20 freeware      Copyright (c) 1993-2014 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
               <@listfiles...> <path_to_extract\>

<Commands>
  e             Extract files without archived paths
  l[t[a],b]     List archive contents [technical[all], bare]
  p             Print file to stdout
  t             Test archive files
  v[t[a],b]     Verbosely list archive contents [technical[all],bare]
  x             Extract files with full path

<Switches>
  -             Stop switches scanning
  @[+]          Disable [enable] file lists
  ac            Clear Archive attribute after compression or extraction
  ad            Append archive name to destination path
  ag[format]    Generate archive name using the current date
  ai            Ignore file attributes
  ap<path>      Set path inside archive
  c-            Disable comments show
  cfg-          Disable read configuration
  cl            Convert names to lower case
  cu            Convert names to upper case
  dh            Open shared files
  ep            Exclude paths from names
  ep3           Expand paths to full including the drive letter
  f             Freshen files
  id[c,d,p,q]   Disable messages
  ierr          Send all messages to stderr
  inul          Disable all messages
  ioff          Turn PC off after completing an operation
  kb            Keep broken extracted files
  n<file>       Additionally filter included files
  n@            Read additional filter masks from stdin
  n@<list>      Read additional filter masks from list file
  o[+|-]        Set the overwrite mode
  oc            Set NTFS Compressed attribute
  or            Rename files automatically
  ow            Save or restore file owner and group
  p[password]   Set password
  p-            Do not query password
  r             Recurse subdirectories
  ri<P>[:<S>]   Set priority (0-default,1-min..15-max) and sleep time in ms
  sc<chr>[obj]  Specify the character set
  sl<size>      Process files with size less than specified
  sm<size>      Process files with size more than specified
  ta<date>      Process files modified after <date> in YYYYMMDDHHMMSS format
  tb<date>      Process files modified before <date> in YYYYMMDDHHMMSS format
  tn<time>      Process files newer than <time>
  to<time>      Process files older than <time>
  ts<m,c,a>[N]  Save or restore file time (modification, creation, access)
  u             Update files
  v             List all volumes
  ver[n]        File version control
  vp            Pause before each volume
  x<file>       Exclude specified file
  x@            Read file names to exclude from stdin
  x@<list>      Exclude files listed in specified list file
  y             Assume Yes on all queries

C:\Program Files\Kindle Comic Converter>
```

**Comment by AcidWeb** [comment]
Im out of ideas. I seen that error twice already. Never replicated it and never found the cause.

**Comment by Maxiride** [comment]
No idea, I'm on Win7 64bit, other than that I have no idea what else could help debugging.

**Comment by AcidWeb** [comment]
For some reason KCC can't start unrar properly.

Could you upload that CBZ somewhere and send me link on e-mail?

**Comment by Maxiride** [comment]
File in upload, however I have a clue on where the issue could be.
This cbr contains 4 folder: Bakuman_v01[HTT], Bakuman_v02[HTT] etc, each of this folder again contains 7 other folders which contains the png\jpg images of the manga.

Might it be that KKC tries to convert the files only in the first subdirectory? I don't know how the software is built and how usually cbr are made (i'm new to the ereaders) however unpacking the cbr with 7z and then compressing to cbr again the first 4 subfolders in 4 different cbr works properly and even the panel view in the kindle works!

**Comment by AcidWeb** [comment]
KCC support multiple levels of directories inside. Also it crash WAY before any conversion - for some reason it fail to unpack that file. I hope that upload will shed some light on this issue.

For now you can repack it as single CBZ file - it should work.

**Comment by Maxiride** [comment]
Here we go: http://we.tl/RGNeMwnzp6
Hopes ti could help a little.

**Comment by AcidWeb** [comment]
OK. Thanks. I will check it out soon.

**Comment by Maxiride** [comment]
I just inform you that after a week the file will be deleted from wetransfer servers.

**Comment by AcidWeb** [comment]
OK. I found the cause. Temp path + file path in archive is too long for Windows.

I will try to add some workaround to next release.

**Comment by Maxiride** [comment]
Awesome, or maybe just write it into the console, anyway except for this little issue everything works fine! Thanks for marking this software.
