### ISSUE TITLE
Error message misleading.

### ISSUE THREAD

**Issue by Cediddi** [ciromattia/kcc#135]
KCC's last binaries gave me an error that says an image is corrupted. I tried to debug and find out that the exception happened in comic2ebook.py Line 897 which when I debugged, found out that my pillow doesn't have jpeg decoder (installed pillow before installing libjpeg). Users should be warned about this and the error message should be more informative.

![kcc - error_015](https://cloud.githubusercontent.com/assets/2720608/7521564/78e96bc8-f4f7-11e4-8956-85c72da3c47f.png)

Also, solution is uninstalling pillow and installing again.

**Comment by AcidWeb** [comment]
It will be fixed in next release.
