### ISSUE TITLE
Reasons for MOBI file size limit?

### ISSUE THREAD

**Issue by shepheb** [ciromattia/kcc#136]
I'd much rather single files than several for my manga, so I'm wondering why the MOBI output is limited.

I'm using a Kindle Paperwhite and don't care about sending via the email service. I have MOBIs converted using other tools that are 250MB and more, so I'm wondering why KCC chops them up into 32MB-ish chunks.

An option to override that batching would be nice, if it's practical to add.

This annoyance aside, KCC does a great job, so thanks for all your work on it!

**Comment by AcidWeb** [comment]
I guess your input use variant C (https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting) and every volume is placed in separate file. Only CLI version allow to override this split.

Even if variant A or B is used KCC will not create files bigger than 400MB as after passing 300mb mark page turning speed is start to significantly increase.
