### ISSUE TITLE
Failed to process MOBI file

### ISSUE THREAD

**Issue by agzom** [ciromattia/kcc#138]
Receive this error when trying to convert any file

**Comment by AcidWeb** [comment]
Well ANY details would be nice.

**Comment by agzom** [comment]
There are certain CBR files that won't finish converting to MOBI files, even if I separate the images from the RAR file. It does convert to EPUB but once it gets to the end it fails. I happened to get some new CBZ files and those worked. But then I decided to rename just to see what would happen and they failed. Renaming them back to their original file names made them work again. Just thought I'd add that in.

**Comment by AcidWeb** [comment]
"Failed to process MOBI file" is displayed when MOBI file was created correctly but it fail its post-processing.

What OS you use? You store that files on some exotic file system? Provide sample file name that cause conversion to fail.

**Comment by AcidWeb** [comment]
Not found any special characters that cause MOBI tweaking to fail.

Closing due to lack of feedback.
