### ISSUE TITLE
.cbr failing to convert (error in getWorkFolder)

### ISSUE THREAD

**Issue by AinaSG** [ciromattia/kcc#139]
I have two cbr that fail at conversion. Never got the same error before.
![captura de 2015-05-20 23 15 30](https://cloud.githubusercontent.com/assets/7085838/7736715/222d53f4-ff46-11e4-9f25-cb7ff1c7873c.png)

thanks for that awesome software.

Maybe unrar is not working?

**Comment by AcidWeb** [comment]
What version you using?

It look like that two files are not CBR files. This error appear when KCC fail to detect if file is CBR, CBR or CB7.

**Comment by AcidWeb** [comment]
Closing due to lack of feedback.

Next release will have better error message.
