### ISSUE TITLE
"Automatic output splitting" not working properly

### ISSUE THREAD

**Issue by jcchristian** [ciromattia/kcc#140]
I'm following the suggested structure (kcc/wiki/Automatic-output-splitting), in my case it's:

- Beelzebub
     - Volume 09
          - Chapter 71
          - Chapter 72
          - Chapter ...
          - Beelzebub v09 - 003 (cover)
          - Beelzebub v09 - 004 (index)
     - Volume 10
          - Chapter 80
          - Chapter 81
          - Chapter ...
          - Extra (some volumes of the manga have bonus pages)
          - Beelzebub v10 - 003 (cover)
          - Beelzebub v10 - 004 (index)
     - Volume 11
          - Chapter 89
          - Chapter 90
          - Chapter ...
          - Beelzebub v11 - 003 (cover)
          - Beelzebub v11 - 004 (index)

I get this error when converting to Kindle Voyage .MOBI (special parameters: Stretch/Upscale): "Automatic output spiting failed". Am I doing something wrong or is it really an issue?

-----------------------------------------------------------

The file is working great on the Kindle. I have one file Beelzebub.mobi that's named "Beelzebub, KCC" internally, and inside I have in order:

- Cover (Kindle default "name" for the first page, this should be Volume 09, but I don't think it's possible)
     - Chapter 71
     - Chapter 72
     - Chapter ...
- Volume 10 (when I click in those Volume XX, I go to the cover + index pages, as intended)
     - Chapter 80
     - Chapter 81
     - Chapter ...
     - Extra
- Volume 11
     - Chapter 89
     - Chapter 90
     - Chapter ...

Thanks.

**Comment by AcidWeb** [comment]
Cover file should be first file of first chapter of volume.

What is index file?

**Comment by jcchristian** [comment]
@AcidWeb Thanks.

So, should I create a folder called 'Cover' and put both "Beelzebub vXX - 003 (cover)" and "Beelzebub vXX - 004 (index)" in there. Will things get fixed this way and stay in order (Volume > Cover > Chapters > Extra) when viewing on the Kindle?

**Comment by AcidWeb** [comment]
Entire directory tree is parsed alphabetically - so yes.

**Comment by jcchristian** [comment]
Working, thanks!
