### ISSUE TITLE
Kobo Epub 3.0 output

### ISSUE THREAD

**Issue by frozenworks** [ciromattia/kcc#141]
Hi, 
The Kobo reader has an Epub 3.0 compatible reader that lets you read in right to left. To use this the books need to have an extension with the name ".kepub.epub". But it appears that KCC doesn't produce an epub 3.0 file that can be read by kobo readers. There is another application on github that produces epub 3.0 that I use with KCC cbz output, But it would be nice to use just one app for all of this.
The other app is located here
https://github.com/hojel/cbz2epub3

An example of the output, kcc is labeled as such and the cbz2epub output is unlabeled.
https://mega.co.nz/#!59oFDagD!S4vUh-YFgGVkzk2zyKXgDKLlAyN8qcQLY-pELVV9zz0

**Comment by AcidWeb** [comment]
Please define what exactly you mean as "read in right to left". Exactly what is gained by using KEPUB format?

I'm quite sure you can open EPUB file created by KCC on Kobo without any additional modifications.

**Comment by AcidWeb** [comment]
Additionally I don't see any structural changes that matter between example files you provided.

**Comment by frozenworks** [comment]
What I mean is that when using a epub 3.0 book with r-t-l defined in the book, the navigation settings reverse so that when you tap on the left it advances forward a page and when you swipe from left to right it also advances forward a page. Kobo has two readers on their devices one for epub 2 and one for epub 3. The epub 2 reader uses the ".epub" extension and the epub 3 reader uses ".kepub.epub" The epub 3 reader supports right to left reading while the epub 2 reader does not.

When I take a book defined as manga in kcc epub output with the ".epub" extension the book looks like this, (left to right navigation):

![screen_001](https://cloud.githubusercontent.com/assets/7309138/8161308/181ee50a-1344-11e5-8a68-a9b2e353fd21.png)

Changing the extension to ".kepub.epub" which uses the epub 3 reader gets this, right to left navigation works:
Page 1
![screen_002](https://cloud.githubusercontent.com/assets/7309138/8161360/6a804852-1344-11e5-931e-ef42cffc3c68.png)

Page 2
![screen_003](https://cloud.githubusercontent.com/assets/7309138/8161363/6d4bfaa4-1344-11e5-86a8-ad2b91934804.png)

No more pages come up.

Using the other app cbz2epub3 with the ".kepub.epub" extension produces this (right to left navigation).
![screen_005](https://cloud.githubusercontent.com/assets/7309138/8161379/85fd7672-1344-11e5-87a3-2834f4d69bad.png)

**Comment by AcidWeb** [comment]
OK. Thank you for detailed explanation. Kindle have the same option but it is enabled by special flag in file header.

I will research this matter. But it might be little tricky as I don't have access to any real Kobo hardware. That is main reason why CBZ is default output format - as I'm sure it work directly.

EPUB output is broken. As I can see KOBO display number of pages and all images are resized assuming that the entire screen is available. You can confirm that KEPUB use entire screen?

**Comment by frozenworks** [comment]
Yes the Kepub uses the entire screen

**Comment by AcidWeb** [comment]
OK. What Kobo model you have?

**Comment by frozenworks** [comment]
An Aura HD

**Comment by AcidWeb** [comment]
OK. In few moments i will give you a file to check.

**Comment by AcidWeb** [comment]
https://mega.co.nz/#!IhtSiIjI!GSC8TGX5586ikpKsAL7cQ-dZ1LVpaeKsQGJq9gSKkF4

Check if it open and work correctly.

**Comment by frozenworks** [comment]
I have checked the file and it doesn't open correctly.

**Comment by AcidWeb** [comment]
Well that is fully valid EPUB 3.0.

**Comment by AcidWeb** [comment]
Please check this one:
https://mega.co.nz/#!pt8WFACa!N8q_SdnIIpXuYLvIqoSs4UlBB565gkaIezJMzu_xN3s

**Comment by frozenworks** [comment]
For this one I can see the cover in the file browser and when opened I can slide through all twelve pages but they are all blank, still progress.

**Comment by AcidWeb** [comment]
Yeah. Try deleting "!" in file name.

**Comment by frozenworks** [comment]
It is without the "!" that it behaves as described in my last comment.

**Comment by frozenworks** [comment]
I actually got it to work, the problem is the "style.css" file, when I replaced the contents of the "style.css" of the Ubunchu file with the contents of the file from "Naruto Chapter 1 - Uzumaki Naruto.kepub.epub", It worked fine. 

This is the working "style.css" file
https://mega.co.nz/#!YsZiERAB!6mq1NVdazH90Ft5mA9aFLX87MVN4pVQHVJihlPRd7as

**Comment by AcidWeb** [comment]
Well that should not work...

Try this one: https://mega.co.nz/#!89tTTYSJ!ELkbjziCKdo7dvR2CJE6YyQhncxD88M4qJHQ3aMdpjw

**Comment by frozenworks** [comment]
The new sample displays 12 blank pages, when I tried replacing the :"style.css" file, the file started to display all  the pages.

**Comment by AcidWeb** [comment]
OK. So I need replace entire internal structure. Expect more files to test today/tomorrow.

It is sad that KOBO reader don't support normal generic EPUB 3.0 files.

**Comment by AcidWeb** [comment]
OK... Next one:
https://mega.nz/#!1x0VCCiS!8HRdjxSdmqUlPoMSIMKAROs3BfIdYbkXRXjIDllHbXA

This one should work so I have additional questions.
All images are intact? Nothing cut on top and bottom?
How the zoom?

**Comment by frozenworks** [comment]
Yes, this one works. I compared the images on my Kobo to the images in the epub and nothing looks like it is cut off. The zoom works correctly from my testing.

**Comment by AcidWeb** [comment]
OK. Then apparently I we succeed. 

Try these two and tell me if there are any quality difference. Not zoomed and zoomed:
https://mega.nz/#!tlMXnA5Z!Ys3bE5ZCUrtS-scxKm6Cya4452VeZWa_VgzVLmO7OVc
https://mega.nz/#!ZwU1zRoR!nKp8GMwuDbZsNFD-yHr1JXXmJGvmCPEUdaX9aD62Zuc

**Comment by frozenworks** [comment]
Ubunchu-B is sharper when zoomed in then Ubunchu-A. When looking at the full page Ubunchu-B looks to be slightly sharper then Ubunchu-A, but I'm not 100% sure.

**Comment by AcidWeb** [comment]
OK. Thank you. That is all I need from you.

Expect release with full EPUB support in next few days :-)
