### ISSUE TITLE
Convert with Add directory not parsing *.cbr (Archives)

### ISSUE THREAD

**Issue by schemen** [ciromattia/kcc#142]
I have in each Folder 1 *.cbr file for the chapter, but it says the directory is empty. If I use "Add file" it works without problem.

Image files are being parsed but archives aren't. Is there a way to quickly fix this and parse or count archive files in the "Add directory" option aswell??

**Comment by AcidWeb** [comment]
Add directory button don't convert by archives design.

Use "Add file" to add multiple files to queue.
