### ISSUE TITLE
TOC is not parsed correctly

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#145]
For some reason NCX and NAV files are completely ignored by Kobo e-reader. And that cause lack of properly working TOC in KEPUB output.

I failed to find the reason. Any feedback is appreciated.

**Comment by frozenworks** [comment]
The problem is in the nav.xhtml file. The html code for the TOC is located in the page list part of the code rather than under the TOC heading. I have attached the working nav.xhtml file.

https://mega.co.nz/#!NwomRDLI!WTHzddynrKMYa7VZ9KMxaFpq5UbVhTXPs1aIjCFiUTE

**Comment by AcidWeb** [comment]
Duh. What a stupid mistake. Thank you.
