### ISSUE TITLE
Comicrack summary metadata

### ISSUE THREAD

**Issue by frozenworks** [ciromattia/kcc#146]
Is it possible to add the comicrack  summary metadata to the the files created by the application, so they can be viewed as the synopses on our e ink devices.

**Comment by AcidWeb** [comment]
Parsing additional field is not a problem. But displaying it on e-reader might be.

Kindle probably don't display in anywhere.

**Comment by AcidWeb** [comment]
As expected <dc:description> is completely ignored by Kindle.

Anyway I will add parsing of ComicRack "Summary" field. Maybe some other e-reader parse <dc:description> field properly.
