### ISSUE TITLE
Comicrack Metadata Parsing

### ISSUE THREAD

**Issue by frozenworks** [ciromattia/kcc#148]
When Comicrack creates it's ComicInfo file it turns all "&" in the metadata into  ![capture](https://cloud.githubusercontent.com/assets/7309138/8521851/257cf7dc-23b6-11e5-9acb-7996b0c8c9fe.JPG)
For example a book called
"Stars & Stripes" in Comicrack
will have the title 
"Stars ![capture](https://cloud.githubusercontent.com/assets/7309138/8521852/2a7e857a-23b6-11e5-94c6-b2eab737fd3f.JPG) Stripes" in ComicInfo.xml
When KCC parses this data it turns the 
![capture](https://cloud.githubusercontent.com/assets/7309138/8521855/33924afc-23b6-11e5-97d7-1f987a28e309.JPG) back into "&" which causes the books to not be able to open on my Kobo reader.

**Comment by AcidWeb** [comment]
I will fix it in next release. No ETA.
