### ISSUE TITLE
Error generating mobi files - system cannot find x.mobi -> x.mobi_toclean

### ISSUE THREAD

**Issue by ianfhunter** [ciromattia/kcc#152]
The windows EXE works for me, but I wanted a cmdline interface so I cloned the source (master).

Unfortunately, after setting up, running "kcc-c2e.py -p KPW Test\" only gets as far as epub generation, and doesn't generate MOBI files afterwards.

I have v2.9 of kindleGen from the linked site so I presume that it's not the source of the problem. It's also the same one I use with the compiled version, which works.

Here's the log below (I added in some of my own logging in allcaps):

``
PS C:\Users\Ian\Code> C:\Python34\python.exe .\kcc\kcc-c2e.py -p KPW Test\
comic2ebook v4.6.3 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.

Checking images...

Processing images...

Creating EPUB file...

Creating MOBI file...
TEST (OUTPUT)  [[0, '', 'Test.epub']]
TEST MOBIPATH:  Test.mobi
Traceback (most recent call last):
  File "C:\Python34\lib\shutil.py", line 521, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'Test.mobi' -> 'Test.mobi_toclean'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\kcc\kcc-c2e.py", line 36, in <module>
    main(sys.argv[1:])
  File "C:\Users\Ian\Code\kcc\kcc\comic2ebook.py", line 73, in main
    outputPath = makeBook(source)
  File "C:\Users\Ian\Code\kcc\kcc\comic2ebook.py", line 1302, in makeBook
    output = makeMOBIFix(i)
  File "C:\Users\Ian\Code\kcc\kcc\comic2ebook.py", line 1315, in makeMOBIFix
    move(mobiPath, mobiPath + '_toclean')
  File "C:\Python34\lib\shutil.py", line 533, in move
    copy2(src, real_dst)
  File "C:\Python34\lib\shutil.py", line 244, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python34\lib\shutil.py", line 107, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'Test.mobi'
``

**Comment by AcidWeb** [comment]
Paths on Windows are not cleared correctly.
Remove "\" after target directory name.

**Comment by ianfhunter** [comment]
Yep, That seems to fix it.

Thanks!
