### ISSUE TITLE
problema con visualizzazione vignette kindle 5° generazione la funzione dei pulsanti è invertita 

### ISSUE THREAD

**Issue by sviluppoSoftware** [ciromattia/kcc#154]
ciao! ho notato che nelle ultime due versioni se uso la modalità manga, quando vado a leggere sul kindle per passare alla pagina successiva devo usare il tasto "indietro" mentre per tornare alla pagine precedente devo usare il tasto "avanti", volevo chiederti se si tratta di un bug dato che con le versioni precedenti non è mai successo, oppure è un problema del kindle, per la cronaca kcc lo uso su ubuntu 15.04 mentre la versione del software kindle è la 4.1.3 (l'ultima).
In attesa di una tua risposta ti ringrazio in anticipo per l'attenzione e in bocca al lupo per il progetto :)

**Comment by AcidWeb** [comment]
This is not a bug. KCC set flow direction headers for long, long time.

**Comment by sviluppoSoftware** [comment]
ok grazie per la risposta, ma allora per quale motivo con le versioni precedenti questo non accadeva?

**Comment by AcidWeb** [comment]
No idea. I don't know which version of Kindle firmware started to reverse page flow order. But I'm quite sure that Kindle 3 don't do that.

**Comment by sviluppoSoftware** [comment]
capisco, farò delle prove se trovo un metodo per tornare alla situazione precedente lo posterò

**Comment by ciromattia** [comment]
Ma per la modalità manga non è il comportamento atteso?
Nel senso che la direzione di lettura è invertita, quindi lo "sfogliare" ha anch'esso i tasti direzione invertiti...

**Comment by sviluppoSoftware** [comment]
concordo che a rigor di logica dovrebbe essere così, eppure non lo era, aggiungo qualche dettaglio:

PREMESSA 
il firmware del kindle offre una "visualizzazione a vignetta" che si attiva automaticamente quando leggi un fumetto (non fa distinzione tra manga o fumetto ), questa opzione non fa altro che suddividere la pagina che stai leggendo in 4 quadranti, ingrandendo il riquadro in alto a destra della pagina, dopodichè quando si preme il tasto per "sfogliare" la pagina ingrandisce il quadrante in alto a sinistra, premendo ancora ingrandisce il quadrante in basso a destra e infine quello in basso a sinistra, poi premendo ancora una volta si passa alla pagina successiva, che verrà nuovamente visualizzata ingrandendo il quadrante in alto a destra ecc... 
FINE PREMESSA

attivando la modalità manga in KCC si ottiene che la "visualizzazione a vignetta"  quando inizi a leggere un manga ingrandisca il quadrante in alto a sinistra poi premendo il tasto di avanzamento pagina ingrandisce il quadrante in alto a destra e così via, fin qui tutto ok fa il suo lavoro cioè permette di leggere da destra a sinistra la pagina di una manga, "il problema" che è sorto consiste nell'inversione dei tasti, ovvero per passare dal quadrante in alto sinistra a quello successivo, in alto a destra, devo premere il tasto "indietro" e non più il tasto "avanti"

**Comment by AcidWeb** [comment]
I admit that I dont understand what is the problem - probably something is lost during Google Translate translation.

So few facts about "Manga mode". This setting do three things.
* Set MOBI header so reader know that this content is read from right to left.
* Keeps an eye on order of splitting double pages (right side first - in this case).
* Set order of panels for Panel View (top right, top left, bottom right, bottom left - in this case).

This was implemented to KCC long, long time so this behavior not changed at all in last versions.

All new Kindle models after detecting header setting switch order of hardware buttons and touch zones.

Maybe @ciromattia will shed some light on this issue.

**Comment by sviluppoSoftware** [comment]
the "problem" that I have found for the kindle 5th generation is this: with the latest versions of KCC in particular from 4.5.1 (I'm done now to do the tests) to advance the page (with active panel view) I have to use the "back" button, while with version 4.5 and earlier, to advance in the pages (with active panel view) using the forward button (the bigger one), perhaps from a quick reading of the changelog, this change may be due this bug fixes implemented in version 4.5.1 https://github.com/ciromattia/kcc/commit/210747bbadb34c7eef27d439c9192c489e56bf19

**Comment by AcidWeb** [comment]
OK. In this case it was working incorrectly and now it is fixed.

**Comment by sviluppoSoftware** [comment]
Update: I have reviewed the file comic2ebook.py version 4.6.4 comparing with the same file version 4.5 I discovered the cause of the "problem", I replaced the lines from 355 to 358 with this f.write ("</ manifest> \ n <plugs toc = \ "NCX \"> \ n ") trying to convert some manga had no problems during the conversion process, , now to move to the next panel with the option "panel view " I can use the forward button rather than the back button
