### ISSUE TITLE
possible solution (for Linux systems) to the reversal of physical buttons with the "manga mode" in kindle 5th generation

### ISSUE THREAD

**Issue by sviluppoSoftware** [ciromattia/kcc#157]
I have reviewed the file comic2ebook.py version 4.6.5 comparing with the same file version 4.5 I discovered the cause of the "problem", I replaced the lines from 358 to 361 with this: 
f.write ("</ manifest> \ n \ n ") trying to convert some manga had no problems during the conversion process,  now to move to the next panel with the option "panel view " I can use the forward button instead of the back button

**Comment by AcidWeb** [comment]
Again - this is not a bug. It is expected behavior.
