### ISSUE TITLE
Gui issue on OSX (retina display)

### ISSUE THREAD

**Issue by kyuzumaki** [ciromattia/kcc#158]
See attached image. I think it's because the list boxes are not the default height. This does not affect functionality of the program, converts perfectly.
![gui_list_glitch](https://cloud.githubusercontent.com/assets/14652728/10007481/979d84fa-60bd-11e5-8ec2-cdaee2eb78b3.jpg)

**Comment by AcidWeb** [comment]
You are probably right. Not sure how to fix it.

**Comment by kyuzumaki** [comment]
Think I've fixed it now, made a pull request with the combo box height adjusted. Don't know how to compile into an OSX binary to test fully

**Comment by AcidWeb** [comment]
Well I would not call it a fix. A workaround at best.

It look like yet-another QT-OSX bug.

**Comment by AcidWeb** [comment]
OK. I can replicate this issue in my dev environment. We will see if I find any dirty hack to fix it.

**Comment by kyuzumaki** [comment]
Great much easier to fix something you can see, pity my hack didn't work.

**Comment by AcidWeb** [comment]
We are both right. It is QT bug and it is caused by non standard combo box height.

I tweaked GUI a little and this distortion will don't appear.
