### ISSUE TITLE
Option to convert .epub to .mobi

### ISSUE THREAD

**Issue by Splike** [ciromattia/kcc#160]
Let me explain my situation so you understand my feature request.

I have a Kindle Paperwhite 3
I use Calibre for managing my library
I use KCC for manga conversion from .cbz to .mobi, because calibre's conversion creates white unwanted margins.

The problem with using KCC for conversions, is that the table of contents are basically non-existent. And editing the ToC of .mobi files is not really possible. When doing the KCC conversion, I see that it first creates .epub files and then converts them into .mobi files. The ToC of epub files are actually editable with calibre!

So to sumarize, what I want to do:
1) Use KCC to convert .cbz to .epub.
2) Use Calibre to create a proper ToC for the .epub file.
3) Use KCC to convert .epub to .mobi (This is where the feature I'm requesting, is needed)

I hope this is possible. If not, is there any news on the plugin for calibre, which you mention here: http://www.mobileread.com/forums/showthread.php?t=203950

**Comment by AcidWeb** [comment]
KCC create TOC based on directory structure. Exactly what changes you want to make manually?

There will not be any Calibre plugin.

**Comment by Splike** [comment]
I actually didn't know KCC did that. Most comics have all the image files in the same directory, So I never noticed this feature.

I played around with it, and noticed a couple of problems with it.
Firstly, the order of the ToC entries. They are based off of the alphabetical order of the folder names, which means that the order of ToC entries will most likely be incorrect.
A solution to this could be, that since every image file contains a number. KCC, should look at the image files inside the folders, and make sure that the folders are sorted in the order of the image file names and not the actual folder names.

Secondly, folder naming limitations. I am not able to have a ToC entry with a colon, because folder naming rules will not allow this. This means, that "Chapter 1: Start of book" is not valid, whereas I have to write "Chapter 1 - Start of book". This is quite ugly notation and I would much rather prefer it with the  colon.
A solution to this:
If I write "Chapter 1- Start of book", KCC will change it to "Chapter 1: Start of book". So whenever KCC detects a ToC entry with a "-_" that comes right after some text and is immediately followed my a blank space, it will convert the "Text-_" into "Text:_".

(Underscores are used to display white spaces)

Hope these two problems will be solved. Thanks.

**Comment by AcidWeb** [comment]
I'm not going to change parse order. Input is parsed alphabetically as designed and most common model assume that directory name contain chapter number before chapter name. In this case after zero padding everything will be parsed in alphabetically order as designed.

But I have alternative solution for you. Use CBZ/CBR/CB7 files with flat directory structure + ComicRack metadata. **This feature was not thoroughly tested** but it will allow you to name TOC entries anyway you want.

**Comment by Splike** [comment]
Thanks for your help.
After playing around with ComicRack, I figured out the XML code for creating a ToC.

For anyone else, that might need to know how this works. Place an XML file called "ComicInfo.xml" in the root of the CBZ/CBR/CB7 file containing the images. The XML file has the the three important things that the kindle needs: Title, author and ToC. When using KCC to convert the CBZ/CBR/CB7 file into a .mobi, the kindle will display the the info given.

Here's the XML code I have for the first Dragon Ball manga 

```
<?xml version="1.0" encoding="utf-8"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <Series>Dragon Ball v01</Series>
   <Writer>Akira Toriyama</Writer>
   <Pages>
      <Page Image="0" Bookmark="Cover"/>
      <Page Image="4" Bookmark="Table of Contents"/>
      <Page Image="6" Bookmark="Tale 1: Bloomers and the Monkey king"/>
      <Page Image="36" Bookmark="Tale 2: No Balls!"/>
      <Page Image="50" Bookmark="Tale 3: Sea Monkeys"/>
      <Page Image="64" Bookmark="Tale 4: They Call Him... the Turtle Hermit!"/>
      <Page Image="78" Bookmark="Tale 5: Oo! Oo! Oolong!"/>
      <Page Image="92" Bookmark="Tale 6: So Long, Oolong!"/>
      <Page Image="106" Bookmark="Tale 7: Yamcha and Pu'ar"/>
      <Page Image="120" Bookmark="Tale 8: One, Two, Yamcha-cha!"/>
      <Page Image="134" Bookmark="Tale 9: Dragon Balls in Danger"/>
      <Page Image="148" Bookmark="Tale 10: Onward to Fry-Pan"/>
      <Page Image="162" Bookmark="Tale 11: ...And into the Fire!"/>
      <Page Image="176" Bookmark="Title Page Gallery"/>
   </Pages>
</ComicInfo>
```

AcidWeb, you're welcome to to use this example in your documentation, as it might help other people looking for a solution to the same problem I was.

**Comment by AcidWeb** [comment]
I'm glad we found solution for your problems.

I will add bare XML example to wiki. Rest is already there:
https://github.com/ciromattia/kcc/wiki/ComicRack-metadata
