### ISSUE TITLE
Have encountered 2 issues with latest update (5.0)

### ISSUE THREAD

**Issue by andyd1ck** [ciromattia/kcc#166]
First, each time just before a job is completed a windows prompt appears saying "There is no disk in the drive. Please insert a disk into the drive G:." After I close the prompt, I am notified by KCC.exe that the conversion is finished. I get the windows prompt regardless whether my kindle is connected to my pc or not. Also just for clarification, I believe that the G drive on my laptop is specifically reserved for the SD/MS port.

Second, when testing the newly converted comic I notice that the panel window no longer zooms in the general area of where I am tapping. On comics converted from previous versions of KCC, I could double-tap the bottom left of the kindle screen and the panel window would be zoomed on that corner of the comic. Now no matter which corner I tap, the panel window zooms on the top left corner of the comic(not sure if this occurs when using manga mode, have yet to test). Hope you can get these problems sorted out, thanks!

**Comment by AcidWeb** [comment]
That is interesting scenario. I understand why it might confuse Kindle detection code. I will try to fix it.

Definitely something is wrong with PV code creation. What Kindle model you use and extractly which KCC options?

**Comment by andyd1ck** [comment]
Sorry for late response; I'm using a kindle paperwhite 3 2015 model. My KCC options are: checked spread splitter, checked stretch/upscale, checked hq zoom, checked custom gamma set to 1.00. Also I have the conversion set for pw3/voyage, and mobi/azw3 selected.

**Comment by AcidWeb** [comment]
Hmm can't replicate this. Upload some where small batch of images that have broken PV and send me the link.

**Comment by andyd1ck** [comment]
Okay here are a couple of images from the comic.
![the walking dead 073 2010 fc](https://cloud.githubusercontent.com/assets/15617817/10902732/db67825c-81b6-11e5-92a9-7c9554cc407f.jpg)
![the walking dead 073 2010 ifc](https://cloud.githubusercontent.com/assets/15617817/10902733/db687504-81b6-11e5-9cd8-8bd7194a4b2d.jpg)
![the walking dead 073 2010 p01](https://cloud.githubusercontent.com/assets/15617817/10902731/db679c06-81b6-11e5-82c2-6f4447054630.jpg)
![the walking dead 073 2010 p02](https://cloud.githubusercontent.com/assets/15617817/10902734/db69f1ea-81b6-11e5-9bd6-395384bf7e8d.jpg)
![the walking dead 073 2010 p03](https://cloud.githubusercontent.com/assets/15617817/10902736/db6bfd50-81b6-11e5-90e8-da37397ca384.jpg)
![the walking dead 073 2010 p04](https://cloud.githubusercontent.com/assets/15617817/10902735/db6ae942-81b6-11e5-8490-cac11dd49dbd.jpg)
![the walking dead 073 2010 p05](https://cloud.githubusercontent.com/assets/15617817/10902737/db7c4142-81b6-11e5-99a1-96f4c908cfd4.jpg)
![the walking dead 073 2010 p06](https://cloud.githubusercontent.com/assets/15617817/10902738/db7c84f4-81b6-11e5-9a7f-1c19cacb0212.jpg)

**Comment by andyd1ck** [comment]
Here's a couple images.
![the walking dead 073 2010 fc](https://cloud.githubusercontent.com/assets/15617817/10902854/ee46da52-81b7-11e5-8261-0fdd83cc3885.jpg)
![the walking dead 073 2010 ifc](https://cloud.githubusercontent.com/assets/15617817/10902855/ee470d9c-81b7-11e5-8128-25c15cb5e28a.jpg)
![the walking dead 073 2010 p01](https://cloud.githubusercontent.com/assets/15617817/10902856/ee47bc9c-81b7-11e5-9eb7-cef34cd20fee.jpg)
![the walking dead 073 2010 p02](https://cloud.githubusercontent.com/assets/15617817/10902857/ee4acb9e-81b7-11e5-8c91-7e8d3a5e07c2.jpg)

**Comment by AcidWeb** [comment]
OK. Thanks. I will check them later.

**Comment by AcidWeb** [comment]
It look like panel view zones are created correctly but something is wrong with touch zones - all link to first panel.

I will fix it this week.

**Comment by andyd1ck** [comment]
Awesome, so glad you were able to locate the problem with the panel view. Were you able to determine why the windows prompt appears too? Doesn't necessarily break any functionality just kinda annoying. Aside from that I appreciate all the help and feedback, can't wait to get back into my comics!

**Comment by AcidWeb** [comment]
Yes. But don't have fix yet.

**Comment by AcidWeb** [comment]
Fixed in 5.0.1.
