### ISSUE TITLE
My reader won't open epub created with the latest (5.0) KCC

### ISSUE THREAD

**Issue by l0master** [ciromattia/kcc#168]
That's it. It simply pop's up an error "Error opening file" . Everything was fine with previous versions. Is there any place i could get 4.6.5 version back?

**Comment by AcidWeb** [comment]
And "my reader" is?

**Comment by l0master** [comment]
You probably haven't heard of. It's some chinese ONYX BOOX T76SML NEFERTITI 1080 × 1440

**Comment by AcidWeb** [comment]
We will confine this discussion on MR.
