### ISSUE TITLE
New PV problem

### ISSUE THREAD

**Issue by andyd1ck** [ciromattia/kcc#171]
I have a new issue involving panel view but affecting a different batch of images this time. On the cover (first image) the PV works but it's a bit wonky and doesn't seem to zoom well on the region that's tapped. The following images however do not go into PV mode at all when tapped, the image just flashes. To reiterate, my kindle is a PW3, my options are: set to convert for pw3/voyage to mobi/azw3, manga mode checked, spread/splitter checked, stretch/upscale checked, hq zoom checked, and custom gamma checked and set to 1.00. Thanks in advance!

**Comment by AcidWeb** [comment]
Yes. PV in first image is created incorrectly. I will check it out.
But rest working correctly. Original resolution is very similar to PW3 resolution so only two vertical panels panels are created.

**Comment by AcidWeb** [comment]
After additional check I change my opinion - First page is configured good too.
I agree that enabling PV on PW3 work much more "wonky" than older models. This model very often turn page instead enabling PV.
