### ISSUE TITLE
Option to disable/ loosen image cropping

### ISSUE THREAD

**Issue by urhereimnot** [ciromattia/kcc#172]
I often get one of the following image cropping issues, in order of severity. I'm using the Windows binary on Win7x64

* Images are cropped "uncomfortably close," with barely any margin between the last character and the edge of the view. Common.

* Images are cropped a bit too much, but still legible. Also somewhat common.

* Images are cropped way too much, making some characters completely illegible. I have one file where I've noticed this issue.

I think it might be an issue with combination of overzealous margin/image cropping and quality of the files, but an option to disable or loosen the edge detection would help with that.

I've attached links to original and generated files indicating the first and last issues. You can see the cropping issues at the bottom of first couple content pages (ie not cover, spine, TOC, etc)

https://dl.dropboxusercontent.com/u/891042/kcc%20crop%20issue/cropped%20too%20much%20generated.mobi
https://dl.dropboxusercontent.com/u/891042/kcc%20crop%20issue/cropped%20too%20much%20original.rar
https://dl.dropboxusercontent.com/u/891042/kcc%20crop%20issue/cropped%20uncomfortably%20close%20generated.mobi
https://dl.dropboxusercontent.com/u/891042/kcc%20crop%20issue/cropped%20uncomfortably%20close%20original.zip

**Comment by AcidWeb** [comment]
Cropping algorithms was never tuned for this type of content. KCC was never indented as LN scan converter. So overzealous cropping is not a surprise for me.

But I will add some options to tweak. **CLI** version only.

**Comment by urhereimnot** [comment]
Thanks!
