### ISSUE TITLE
KCC 5.0 & 5.0.1 PW3 all produced mobi files are zoomed in.

### ISSUE THREAD

**Issue by konkouba** [ciromattia/kcc#173]
Since upgrade to 5.0 and later 5.0.1 mobi ebooks produced by kcc have been rendering as zoomed in on Kindle Paperwhite 3. Using panel view shows that the full image is loaded, but the image is always centered and sized to extend out of frame on all sides. When comparing ebooks produced from the same source files and with the same settings but using different versions of the app (5.0 vs. 4.6.5), the newer files have this issue while the old ones do not.

**Comment by AcidWeb** [comment]
Disable upscaling or stretching.

**Comment by konkouba** [comment]
Issue persists despite disabling Stretch/Upscale.

**Comment by AcidWeb** [comment]
Please provide any samples. Do you edit created MOBI in any way before uploading?

**Comment by konkouba** [comment]
I change the cover sometimes on Calibre, the result is the same whether or not I use calibre and whether or not I change the cover.
Attached are images of the end results:
![dsc_0012](https://cloud.githubusercontent.com/assets/15934322/11303277/fe6791ac-8f99-11e5-989d-bed7728609dc.JPG)
![dsc_0009](https://cloud.githubusercontent.com/assets/15934322/11303278/fe698322-8f99-11e5-8d5e-521a8a3e9971.JPG)

**Comment by AcidWeb** [comment]
I need input, output file and information exactly what options you used.

**Comment by konkouba** [comment]
Link to zip containing files: https://drive.google.com/file/d/0BwBGGWPaTmI7cHdvSmlPOTR1Rkk/view?usp=sharing

On the recent file (よつばと! 01): all options are now disabled disabled except for Manga mode; on the older file (yotubato!01 - azumakiyohiko): Rotate, Upscale, PNG, and HQ are enabled as well.
Both are set to PW3 and MOBI in the dropdowns.

**Comment by AcidWeb** [comment]
It is suprising but both MOBI files work great on my Kindle.
Kindle Previewer is also display it correctly.

**Comment by konkouba** [comment]
That's very strange, those files are the same ones used in the images above. I'm pretty sure there's nothing going on during the transfer seeing as I've tried both using Calibre and drag and dropping directly onto the disk with the same results.

**Comment by AcidWeb** [comment]
What firmware version you have?

**Comment by konkouba** [comment]
Kindle 5.6.5 (2730300038)

**Comment by AcidWeb** [comment]
I tested that files on 5 PW3. No idea why it don't work only for you.

**Comment by konkouba** [comment]
I've tried resetting the Kindle, as well as reinstalling kindlegen, kcc and all the dependencies including python. The resulting files still produce the same issues, but files from 4.6.5 kcc still work as always. Will  soon try comparing the internals of files produced under the same settings to see if I can work out what may be causing the problem.

**Comment by AcidWeb** [comment]
Well I can already say you what changed internally - everything.

Give me that first 6 digits of your Kindle serial code.

**Comment by konkouba** [comment]
90C607

**Comment by AcidWeb** [comment]
Strange. Japan ones should start with G090G7.

**Comment by konkouba** [comment]
It's not a Japanese Kindle, it's just connected to a Japanese account.

**Comment by AcidWeb** [comment]
Try to open MOBI files created on your computer with: http://www.amazon.com/gp/feature.html?docId=1000765261

**Comment by konkouba** [comment]
Result with 5.0.1 ebook using Previewer:
![2015-11-23-190018_548x842_scrot](https://cloud.githubusercontent.com/assets/15934322/11372446/8ff4053c-92c5-11e5-9312-6897ccdbb612.png)

**Comment by AcidWeb** [comment]
And the same file display too big images on Kindle?

**Comment by konkouba** [comment]
Yes.

**Comment by AcidWeb** [comment]
I don't have explanation.

**Comment by konkouba** [comment]
There must be a difference in how Previewer displays the end file versus how the Kindle itself displays it.

**Comment by AcidWeb** [comment]
That is the same engine. Additionally if I take that your MOBI to any other PW3 it will work correctly.

**Comment by konkouba** [comment]
I have no explanation either then, looks to be a unique user error.

**Comment by Rad1iant** [comment]
same problem 
[img1](http://cs627121.vk.me/v627121480/2b9e0/AVvY9SDL-sE.jpg)
[img2](http://cs627121.vk.me/v627121480/2b9d7/IXQ2XlSoL58.jpg)

**Comment by AcidWeb** [comment]
You are sure you sure that you use PW2 profile?

**Comment by Rad1iant** [comment]
oh sorry, my fault
