### ISSUE TITLE
Broken HQ zoom - Kindle Keyboard

### ISSUE THREAD

**Issue by mcgravier** [ciromattia/kcc#174]
After updating from 3.1 to 5.01 comics in MOBI format wont allow page switching (Im stuck on first page. Page gets refreshed when pushing "next page" button). Zoom also does not work.

**Comment by AcidWeb** [comment]
That is quite big update...

Check if "previous page" button don't move you to next page.

**Comment by mcgravier** [comment]
Well it worked! I didnt expect that keys will be switched. Still no zoom however

**Comment by AcidWeb** [comment]
Option to enable panel view is not in the book menu?

**Comment by mcgravier** [comment]
I can enable that option, but it wont zoom. Page is refreshed every time i push next page button but no zoom. After pushing button few times, next page is loaded

For the record: I'm using manga mode when converting

**Comment by AcidWeb** [comment]
Sample file on KCC page also don't have zoom?

**Comment by mcgravier** [comment]
No zoom on sample file

**Comment by AcidWeb** [comment]
Try without HQ zoom.

**Comment by mcgravier** [comment]
Nope, kindle panel view still does not work.
Just to clarify: Whole time I was reffering to "zoom" I always meant Kindle Panel View. 
- Regular zoom option works with non HQ zoom conversion. 
- with HQ zoom conversion enabled, regular zoom option causes entire picture to move down

**Comment by AcidWeb** [comment]
Well apparently K3 (newer don't have problems) reader don't support methods I used to create HQ zoom pages.

Not sure when I will fix it.

**Comment by mcgravier** [comment]
Can you provide ver 3.1 installer on your webpage? It worked flawlessly with my device.

**Comment by AcidWeb** [comment]
Try this version: https://kcc.iosphe.re/Windows/KindleComicConverter_win_4.6.5.exe
