### ISSUE TITLE
Bottom of page crop is too aggressive

### ISSUE THREAD

**Issue by frozenworks** [ciromattia/kcc#175]
Hi, it appears that the crop at the bottom of the page is a bit too aggressive.
The original image
![p00120](https://cloud.githubusercontent.com/assets/7309138/11848836/d5090f4e-a3f2-11e5-8d72-444558bf8bee.jpeg)
The converted image
![p0120-kcc](https://cloud.githubusercontent.com/assets/7309138/11848845/e02eb22a-a3f2-11e5-86ea-7c2cadb6e24e.png)
As you can see at the top of the image the white-space is cropped away stopping at the word bubble, but at the bottom the crop goes through the word bubble removing text.

**Comment by AcidWeb** [comment]
Fully aware about it.

It is certain that some content will be cropped too aggressive. If you you relax thresholds some content will be not cropped enough.

Current values are the golden mean.

Next release will have CLI options to change them.
