### ISSUE TITLE
kindlegen stays open forever on very large conversion (100+ mb)

### ISSUE THREAD

**Issue by tamodolo** [ciromattia/kcc#178]
That's it. On single chapter kindlegen auto close and KCC continue the job while large files it has to be killed manually for kcc to continue.

**Comment by AcidWeb** [comment]
Heard about this issue. Never found the cause.

It is not connected to input size.

**Comment by tamodolo** [comment]
I was using the binary release and that don't show me the verboses. I'm downloading the py version and I'm setting the environment to run it on windows cmd to see what is happening. More info to come if I'm sucessful.

**Comment by AcidWeb** [comment]
Here is function that start kindlegen worker pool:
https://github.com/ciromattia/kcc/blob/master/kcc/comic2ebook.py#L1253
And worker itself:
https://github.com/ciromattia/kcc/blob/master/kcc/comic2ebook.py#L1223

I would start with printing kindlegen output and checking what is last message before it locks.

**Comment by tamodolo** [comment]
It's kindlegen fault. I added a pull request that terminate kindlegen as soon as mobi creation is finished.

Not a beautiful solution but it works now.

**Comment by AcidWeb** [comment]
Great job. I will merge it later.
