### ISSUE TITLE
mac OS X 10.11.2

### ISSUE THREAD

**Issue by irashadpro** [ciromattia/kcc#182]
Hi :)
i am running mac os x 10.11.2 ,unfortunately the tool did not work..i hope you are going to release an update soon!

Thanks :+1:

**Comment by AcidWeb** [comment]
Any details?

**Comment by irashadpro** [comment]
Well i am runong it on macbook pro 2009
Mac is x 10.11.2
The dmg file opens but the App close immediately.it shows the report error
window.


Am Dienstag, 5. Januar 2016 schrieb Paweł Jastrzębski :

> Any details?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciromattia/kcc/issues/182#issuecomment-169086272>.
>


-- 
Sent from Gmail Mobile

**Comment by AcidWeb** [comment]
Current KCC OSX build don't support Core2Duo CPU.

**Comment by irashadpro** [comment]
Are you going to support it later?

Am Dienstag, 5. Januar 2016 schrieb Paweł Jastrzębski :

> Current KCC OSX build don't support Core2Duo CPU.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciromattia/kcc/issues/182#issuecomment-169087500>.
>


-- 
Sent from Gmail Mobile

**Comment by AcidWeb** [comment]
https://github.com/ciromattia/kcc/issues/164#issuecomment-168489882
