### ISSUE TITLE
Directory multiselect won't work on Mac OS

### ISSUE THREAD

**Issue by leedashone** [ciromattia/kcc#183]
Issue: The "Add Directory" dialog multiselect won't work.
KCC Ver: 5.0.1
OS Ver: Mac OS 10.11.4 Beta 1 (15E27e)

Thanks for your great program!  It's really save my life.

**Comment by AcidWeb** [comment]
https://github.com/ciromattia/kcc/wiki/Known-issues

**Comment by leedashone** [comment]
Thanks for your quick reply , I found alternative way to do it:
"Just drag source folders then put in center box!"
Happy ;-)
