### ISSUE TITLE
manga on Kindle is "soomed out" (KCC V5.0.1)

### ISSUE THREAD

**Issue by Stoneman235** [ciromattia/kcc#185]
hi guys, 
im using the KCC now nearly for one year and everything was fine. now i updated to the latest version 5.0.1 and all mangas i convert ar like soomed out on kindle http://puu.sh/mKezn/e4afe5534f.jpg . i converted an older manga. the old file is all fine, the new one is like the image. i am using the KCC set to Kindle PW 1/2 and output to mobi. the options manga mode and hq zoom are enabled. thenn i put the mobi file to calibre and copy it to my kindle. i tried to use version 4.6.5 but it wont start...
so i dont know what im doing wrong, can you help me?

greetings stoneman
p.s sry for bad english, i hope you understand me :D

**Comment by AcidWeb** [comment]
This test file work correctly?

https://kcc.iosphe.re/Samples/Ubunchu!-KPW.mobi

**Comment by Stoneman235** [comment]
wow, you are fast. its the same problem with your test file

**Comment by AcidWeb** [comment]
Try uploading it manually without Calibre.

**Comment by Stoneman235** [comment]
i dindt do this ever before, which folder do i have to copy to?

**Comment by AcidWeb** [comment]
documents

**Comment by Stoneman235** [comment]
still the same

**Comment by AcidWeb** [comment]
What firmware version you have?

**Comment by Stoneman235** [comment]
updated this night 5.6.5

**Comment by AcidWeb** [comment]
You are sure that you have Paperwhite 1 or 2 and not 3?

**Comment by Stoneman235** [comment]
dont know o.O

**Comment by AcidWeb** [comment]
Logo on bottom is silver or black?

**Comment by Stoneman235** [comment]
black
im trying pw3 setting

**Comment by AcidWeb** [comment]
That is Paperwhite 3 :-)

**Comment by Stoneman235** [comment]
-.-

**Comment by Stoneman235** [comment]
thanks for your fast help and sry that im stupid :D
