### ISSUE TITLE
Add leading 0 in metadata to fix kindle's sorting

### ISSUE THREAD

**Issue by jgoux** [ciromattia/kcc#186]
Hello,
the kindle doesn't sort the books' names naturally, so when I convert my books from ComicRack, they're sorted like : 1, 10, 11...19, 2, 20, 21.
A fix would be to automatically add a leading zero if the number is between 1 and 9 : https://github.com/ciromattia/kcc/blob/4b1c7b3124ffc7a8ba0ece8d7420f9f4dc67c229/kcc/comic2ebook.py#L659

Thanks for this awesome software !

**Comment by AcidWeb** [comment]
You are right. I will fix it in next release.
