### ISSUE TITLE
Some covers shown some not on converted CBR's

### ISSUE THREAD

**Issue by Fasoulas20** [ciromattia/kcc#187]
Don't know if this is a bug, but some converted CBR's are shown with Covers on Kindle, some not. Don't know if this is how KCC converts the file or it has to do with the original CBR...

See attached image.
![kcc](https://cloud.githubusercontent.com/assets/17298853/13117905/2105f732-d5a2-11e5-8cd1-02095b95985d.png)

**Comment by AcidWeb** [comment]
Did you convert some of them with connected Kindle?

**Comment by Fasoulas20** [comment]
No. 

I will try converting the files in question with and without Kindle connected in a few hours and see the outcome.

**Comment by AcidWeb** [comment]
Then how you uploaded them?

**Comment by Fasoulas20** [comment]
1. I converted many CBR's in a batch on my PC into .mobi with KCC with default options.
2. Then I connected a Kindle with USB.
3. I copied the newly created .mobi files on the kindle with Total Commander.

I can attach original CBR or give you the link of it so you can try maybe? Here is the link http://www.mediafire.com/?pbwlnx43bcad7cb

**Comment by AcidWeb** [comment]
Well that is surprise because in this cause no KCC created book should show cover.

**Comment by Fasoulas20** [comment]
Do you want to say that in order to have covers, I should convert the files with Kindle connected?

I will try this as soon as I get home.

**Comment by AcidWeb** [comment]
https://github.com/ciromattia/kcc/wiki/Automatic-cover-upload

**Comment by Fasoulas20** [comment]
Then everything is clear, I most probably accidentally had Kindle connected for some of the files...

You can close this issue, thank you very much for the fast response, and keep up the awesome work you are doing! Cheers ;)
