### ISSUE TITLE
Multiple output format?

### ISSUE THREAD

**Issue by ducdigital** [ciromattia/kcc#188]
Hi, 

Is it possible to output multiple format with the kcc-c2e.py?

Thank you :D

**Comment by AcidWeb** [comment]
There is no option to do that. But adding that should be easy.

Why you need it?

**Comment by ducdigital** [comment]
This is cool since it helps not convert twice for the same comic on both my devices (ios and kindle). Some how mobi file converted by kcc not readable on my ios execpt the first page.

**Comment by AcidWeb** [comment]
It will not work. KCC output is optimized for single screen resolution. MOBI created for e-ink Kindle will look **bad** on iOS screen.

**Comment by ducdigital** [comment]
I see. However it will still be cool to convert all at once for multiple device ( Kobo + Kindle ) . Will you implement this?

**Comment by AcidWeb** [comment]
I will think about it.

**Comment by ducdigital** [comment]
:+1:
