### ISSUE TITLE
KCC can't upload any files but PDF 

### ISSUE THREAD

**Issue by Abdulaziz1985** [ciromattia/kcc#192]
Hello - I downloaded the KCC on my MacBook, then I uploaded KindleGen terminal file on the /usr/local/bin interface. I can see that KCC is working fine but when I want to add file only PDF file can be uplaoded. I can't choose PNG, JPEG, or TFF file. Even when I upload the PDF file, it can't be converted to the Kindle format (MOBI, Azw3). Can you please help me with this: a) make the KCC add PNG, JPEG, and TFF files; b) convert these files to Kindle format; c) make the PDF file convertable to kindle format? Please see the **attached files**. Thank you so much
![screen shot 2016-05-03 at 8 05 02 pm](https://cloud.githubusercontent.com/assets/19166515/14980280/e0e32648-116a-11e6-85e2-96e4e54477c3.png)
![screen shot 2016-05-03 at 8 08 33 pm](https://cloud.githubusercontent.com/assets/19166515/14980293/ef38f6e6-116a-11e6-9b17-ea75cabee8e1.png)

**Comment by AcidWeb** [comment]
Add directory containing all image files.

PDF support is symbolic and it will fail to parse most of files as it can only extract JPG files.
