### ISSUE TITLE
kcc start up just hangs

### ISSUE THREAD

**Issue by adriantoine** [ciromattia/kcc#193]
I have an issue and I can't find anything similar in the issues list. When I try to start kcc on Mac OS El Capitan, it just hangs. The app logo bounces in my dock just like it's being launched but nothing happens at all and I don't have any error, or stack trace, it just doesn't do anything. And I don't have a Core2Duo processor.

Here is my config:
<img width="322" alt="screen shot 2016-05-03 at 16 29 41" src="https://cloud.githubusercontent.com/assets/976570/14988564/51c59fd6-114c-11e6-9cfa-3073f55369a0.png">

It's weird because it seems like no one is having that issue but I've tried everything, even cloning the repo and running the python command, but it hangs as well...

**Comment by AcidWeb** [comment]
Well if even cloned version don't start something is very, very wrong.
Nothing is printed to console when you start bare python version?

**Comment by adriantoine** [comment]
Ok so I restarted my laptop and now it seems to work, I have no idea why it wasn't working, sorry!
