### ISSUE TITLE
Mobi files without cover

### ISSUE THREAD

**Issue by helderc** [ciromattia/kcc#194]
The wiki says "The first image found will be set as the book cover" but, I have converted several files and all of them doesnt have a cover.

I'm using Kindle Paperwhite with firmware 5.7.4.1.
In KCC's device combobox I select "Kindle PW 3", did I right?

Thank you for the great software.

**Comment by AcidWeb** [comment]
How you upload files to Kindle?

**Comment by helderc** [comment]
I plugged the Kindle on USB port and copy via Windows Explorer CTRL+C CTRL+V.

**Comment by AcidWeb** [comment]
https://github.com/ciromattia/kcc/wiki/Automatic-cover-upload

**Comment by helderc** [comment]
Oh I see. I'll check this later.
Thank you.

**Comment by helderc** [comment]
I just tested transfer the mobi file using yours KindleButler.
I worked just fine and the cover is shown on Kindle.
(Easier than use Calibre)

Thank you.
