### ISSUE TITLE
Epub file has more than one opf file

### ISSUE THREAD

**Issue by baldore** [ciromattia/kcc#195]
Hello! I'm trying to use this great tool but when kindleGen runs, it says:

`[1, 'Error(prcgen):E21027: Epub file has more than one opf file \r\n', 'hunter.epub']`

Do you know what am I doing wrong? I tried with the most basic command:

`kcc-c2e hunter`

Where `hunter` is a folder with the manga images. Thanks for your help.

**Comment by AcidWeb** [comment]
Well it look like EPUB creation went WRONG.
Try `kcc-c2e -f EPUB hunter`. And show me file structure of created inside EPUB file (is it normal ZIP file).

**Comment by baldore** [comment]
I don't know what happened but it's working excellent now. Looks like it was a issue with my computer... Thanks a lot and great job with this tool.
