### ISSUE TITLE
Corrupted file for Other device

### ISSUE THREAD

**Issue by MuminekM** [ciromattia/kcc#199]
After converting file for Other device (with different settings, i.e. size, options, output format) KCC produces corrupted file. On the device (Pocketbook) every page is blank - but number of pages and size  are correct. 

This happened after updating application to version 5. It didn't happen for Kindle device, only for PocketBook. Old converted files (with older version of KCC) still works perfectly.

**Comment by AcidWeb** [comment]
Well apparently Pocketbook don't support EPUB 3.0.1. Unless your device support CBZ too - you are forced to use old version.

**Comment by KSE2016** [comment]
Ah, that would explain a lot. Thanks for the information

**Comment by MuminekM** [comment]
Ah, that would explain a lot. Thanks for the information
