### ISSUE TITLE
Stuck at creating mobi files

### ISSUE THREAD

**Issue by mkhlee** [ciromattia/kcc#200]
I am converting folders with jpeg to mobi files for paperwhite 2, and KCC gets stuck at converting mobi files, after creating the epub ones. When I go to the folder, I see all the mobi and epub files, and they are all readable (including mobi), but KCC still says it is converting. This is annoying because I have to go into task manager to close it, then reopen in to continue converting. Any insights?

**Comment by AcidWeb** [comment]
Which version you use?

**Comment by mkhlee** [comment]
It should be the latest hosted at https://kcc.iosphe.re, since I installed it a few days ago. I tried reinstalling it with no success

**Comment by mkhlee** [comment]
I am on a Windows 10 system, btw

**Comment by AcidWeb** [comment]
When KCC is stuck. Check if kindlegen process is still running.

**Comment by mkhlee** [comment]
Yes it is, about 4 processes.

**Comment by AcidWeb** [comment]
Well that is quite old bug. But it should be fixed already :-/
What AV you use?

**Comment by mkhlee** [comment]
Its avast. I'll try converting without AV on.

**Comment by mkhlee** [comment]
No good, still stuck. If I delete some kindlegen process when stuck, it usually starts to complete the job.

**Comment by AcidWeb** [comment]
Well that is known KindleGen issue. It sometimes don't terminate after conversion. KCC should kill KindleGen in this case - no idea why it don't work for you.
