### ISSUE TITLE
I need the "No optimisation"item！Please add it back

### ISSUE THREAD

**Issue by beyondband** [ciromattia/kcc#201]
KCC Team:
        Hi,I want to convert some comic books，The image have been optimized，and they are already resized. 
       Would you please add the "No optimisation" item again？Thanks very  very very  very much!
       Kindle Comic Converter 4.6 has the "No optimisation" 。It useful for me。

**Comment by AcidWeb** [comment]
Sorry. This option is gone and it will not coming back.
