### ISSUE TITLE
URGENT need a copy of Win KCC Ver 5.0.1:

### ISSUE THREAD

**Issue by shinji16** [ciromattia/kcc#202]
![untitled](https://cloud.githubusercontent.com/assets/20621739/17082430/19156530-5176-11e6-8fc9-fc7ce4bb25be.png)

Version above 5.0.1: do not work at all for me. And it replaced my one installation. Ver 5.0 works good for me.

Please anyone who has a copy of Win KCC Vers 5.0.1: please pass a copy URGENTLY.

My Razor blade is win 8.1 on a x64 bit and it has some python and Visual c++ redistribution issues stopping the latest KCC to even launch.

I don't have time to fix why it won't work. It be great help if anyone can provide a copy.

**Comment by AcidWeb** [comment]
Install this manually:
https://github.com/ciromattia/kcc/raw/master/other/windows/vc_redist.x64.exe

If it not help you have bigger problems than not working KCC - your Windows installation is broken.

**Comment by mtv890** [comment]
For the record, I had a similar issue :
```
Error loading Python DDL: 
C:\Users\MyUser\AppData\Local\Temp\_MEI64202\python35.dll (error code 193)
``` 

tried diferent python version and nothing works. After i reach this page.
I changed my `MV C++ 2015 (x64) 14.0.24123` for the one @AcidWeb suggest here `(14.0.23026)` and it seems to be working now.

**OS:**  win7 & python3.4.4

hope it helps
