### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by Zanther** [ciromattia/kcc#203]
So I just spent a few hours over the last couple of days adding and editing metadata in Calibre after converting my collection with KCC to MOBI and I put everything on my kindle only to find that NONE of the Metadata was transferred...I could have sworn it worked before, but now it won't work at all. Just stays at the original name I converted it with KCC as the artist.  My question is, did I just do all that work for nothing?

**Comment by AcidWeb** [comment]
Sadly yes. And no - Calibre never could add metadata to KCC output.

This method will not work as Calibre need to reconvert file to modify metadata. And that process will destroy KCC work.

**Comment by AcidWeb** [comment]
Metadata need to be embedded in source CBZ/CBR/CB7 file. Check wiki.

**Comment by Zanther** [comment]
So you are saying there is no way to add Metadata onto a Mobi, I have to do CBZ/CBR/CB7 first in order to add ANY metadata.  I am on a Mac btw.  What is the best way to add meta data then to a mobi file.

**Comment by AcidWeb** [comment]
In this case - no.
https://github.com/ciromattia/kcc/wiki/Metadata
https://github.com/ciromattia/kcc/wiki/ComicRack-metadata
