### ISSUE TITLE
Comic to Ebook script performing glob expansion on arguments

### ISSUE THREAD

**Issue by badboybeyer** [ciromattia/kcc#205]
Most shells perform glob expansion on arguments already. The extra glob step inside the kcc-c2e.py script requires me to escape glob pattern characters twice. For example, if I have a comic folder named `manga [English]`, I would typically pass it to a CLI application as `manga\ \[English\]`.  I have to pass it to kcc-c2e.py as: `manga\ \\\[English\\\]` for the brackets to survive two glob expansions though. I recommend the following change:

    diff --git a/kcc/comic2ebook.py b/kcc/comic2ebook.py
    index a881e96..c70a95a 100755
    --- a/kcc/comic2ebook.py
    +++ b/kcc/comic2ebook.py
    @@ -64,7 +64,7 @@ def main(argv=None):
         if len(args) == 0:
             parser.print_help()
             return 0
    -    sources = set([source for arg in args for source in glob(arg)])
    +    sources = set(args)
             if len(sources) == 0:
             print('No matching files found.')
             return 1

Shell glob expansion is explained in the man page of a shell. It is typically not referred to as "glob". I have seen it called "pattern expansion", "special patterns", and "glob expansion".

**Comment by AcidWeb** [comment]
You are right. I need to change this for non-windows platforms.
