### ISSUE TITLE
Can't zoom after creating a mobi file

### ISSUE THREAD

**Issue by KiryuuKazuma** [ciromattia/kcc#209]
Hi, I've used the tool in the past to convert manga, without problems. I updated yesterday to 5.13 and redownloaded kindlegen, and after converting a manga for my PW2 I am unable to zoom with both fingers as I used to be able to. I checked an old manga converted before with KCC and it zooms flawlessly. I also went as far as using the same source files for this old manga and converting it again with the updated version, and the same thing happens, can't zoom.
If it helps, when I try to zoom it just kinda refreshes the screen and 4 black squares appear for a second on the lower right part of it.
Also, panel mode works, and I can -kinda- zoom if I'm inside a panel, but it gets weird most of the time.
I'm attaching one pic of the normal view and another pic of what happens when I try to zoom.

Thanks in advance for any help you can give me, love your app nonetheless.
![20160929_234020](https://cloud.githubusercontent.com/assets/22535053/18979069/486702d2-869e-11e6-804c-9f41151bd225.jpg)
![20160929_233959](https://cloud.githubusercontent.com/assets/22535053/18979072/4f97f156-869e-11e6-86c1-74763261b92f.jpg)

**Comment by AcidWeb** [comment]
Huh it look like panel view stuck. You getting that black screen on every page?

**Comment by KiryuuKazuma** [comment]
Yes, when I try to zoom. It comes back to normal after a second, it's not like I get stuck there.

**Comment by AcidWeb** [comment]
And on rectangular pages with graphic?

**Comment by KiryuuKazuma** [comment]
Yes, it's the same in every page. I can double tap the screen for panel view, and it works normally, separating the page into 4 zones that I can navigate, and I can zoom when I'm inside any of those zones (although it's somewhat buggy, I can't explain it clearly but the zoom resets to one of the corners sometimes). But if I exit panel mode (back to normal view), when I try to zoom, it just gives that black screen with the squares for a second and does nothing else. It doesn't hang kindle or anything, it simply does nothing. So, bottomline, I can't zoom normally, hahaha

**Comment by AcidWeb** [comment]
Pinch zoom was always buggy. It never worked correctly for me. I think that one of firmware updates changed pinch zoom behavior and in combination with 5.x KCC changes this function was crippled completely.

And I doubt it will be back. Sorry.

**Comment by KiryuuKazuma** [comment]
I thought as much and installed 4.x, which brought back the zoom, so I
guess I'm sticking to that version, hahaha. Thanks anyways for your help!

**Comment by AcidWeb** [comment]
Pinch zoom support will be back in 5.3.
