### ISSUE TITLE
KFX output

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#210]
This is very long term goal. Maybe not possible unless Amazon release some tools.

To enable two newest Kindle features - Better pinch zoom and ultra fast page changing - KCC need to create KFX files. At the time of the creation of this issue tools to achieve this don't exist.

EPUB creation process don't need any changes. Kindlegen part need to be replaced.

**Comment by AcidWeb** [comment]
Only available to the public method to create KFX files (Calibre connected with Kindle Previewer 3) don't work this this type of content - KP3 can't create fixed layout KFX at all.

So unless Amazon publish some additional tools or there will be major breakthrough in KFX reverse engineering don't expect pinch zoom and ultra fast page changing features soon.

**Comment by AcidWeb** [comment]
https://www.mobileread.com/forums/showpost.php?p=3520463&postcount=212

**Comment by AcidWeb** [comment]
Nothing new to add. KFX files created by publicly available methods still provide worse experience than KF8 ones.

**Comment by AcidWeb** [comment]
Dev branch now have experimental KFX output profile that create EPUB files that can be used with Calibre plugin KFX Output by jhowell.

**Comment by walterclozet** [comment]
I use the dev branch cli like this:
kcc-c2e.py -q -t "Kotori Cosplay" -f EPUB y:\001\
a epub can be generated, converting it to kfx by:
calibre-debug -r "KFX Output" -- y:\001.epub y:\001.kfx
and convertion failed, kfxgenapp error is:
 Error(YJConvValidator):E120003: Content containers are not supported for FL books. id: 4144662183618417252

Am I doing something wrong?

**Comment by AcidWeb** [comment]
Yes. `-f KFX`

**Comment by walterclozet** [comment]
I tested, kfx comic can be generated, virtual panel mode works, ultra fast page turning works on paper white 3.

**Comment by AcidWeb** [comment]
Also small PSA for people reading this: Currently KFX provide lower quality than AZW3. New features are not worth it.

**Comment by AcidWeb** [comment]
Nothing new to add. KFX rendering engine still decrease image quality.

**Comment by AcidWeb** [comment]
Nothing new to add. There is still no convenient toolchain to implement KFX support in KCC.
