### ISSUE TITLE
Images cut in half - Kobo mini

### ISSUE THREAD

**Issue by GASEYES** [ciromattia/kcc#211]
Downloaded Mob Psycho onto the computer, converted it, made sure it was set to Kobo mini. 
When i open the file on the Kobo i can only see the bottom half.
I attempted to convert it several times with different settings with the same result. 
I tried using the "other" setting for devices, set the resolution to 800x600, but with that i could only see the top half of the page. 
No clue what to do at this rate.

![20161029_225514](https://cloud.githubusercontent.com/assets/23143048/19832743/7e867f82-9e2c-11e6-8b16-35bb84aa0366.jpg)
![20161029_230116](https://cloud.githubusercontent.com/assets/23143048/19832741/784a0f9e-9e2c-11e6-983c-4cf831f4c4bc.jpg)

**Comment by AcidWeb** [comment]
How you upload ready file?

**Comment by GASEYES** [comment]
I downloaded the files with DomDomSoft Manga Downloader.
I then used KCC and selected the file Mob Psycho i had created.

>>>>
![step 1](https://cloud.githubusercontent.com/assets/23143048/19836519/1c874c54-9ea3-11e6-80dd-568eba54a497.PNG)

This is what it looks like inside the file. 

>>>>
![step 2](https://cloud.githubusercontent.com/assets/23143048/19836523/406ebfee-9ea3-11e6-93d8-26aaa688632e.PNG)

**Comment by AcidWeb** [comment]
That was not my question. How you upload ready file to your Kobo?

**Comment by GASEYES** [comment]
Ah ok sorry, i simply moved it using a USB cable.

**Comment by AcidWeb** [comment]
Is the file extension is .kepub.epub?

**Comment by GASEYES** [comment]
i tried using both, the kepub version shows me the bottom half, while the normal epub shows me the top half.

**Comment by AcidWeb** [comment]
It should be ".kepub.epub". Both at once.

**Comment by AcidWeb** [comment]
You running newest firmware?

**Comment by GASEYES** [comment]
The firmware on the Kobo? hmmm, no, ill check and update it.

**Comment by AcidWeb** [comment]
Cutting image in half is quite common problem on Kobo if e-reader don't open file using KEPUB renderer.

https://github.com/ciromattia/kcc/issues/184

**Comment by GASEYES** [comment]
Alright i updated the firmware and i installed ADE 3.0 to authorize the files and now everything works fine, thanks for the help.
