### ISSUE TITLE
[Request] Split manga-mode in two options

### ISSUE THREAD

**Issue by occivink** [ciromattia/kcc#212]
Hi,

As far as I can tell, the manga mode currently does two things: 
* Change reading order (next page is left)
* Determine which is the first image when splitting horizontal images

The second feature is pretty much necessary if you're reading manga, but I'm not really interested in the first one (because page turn is now a different gesture than when reading traditional book). Would it be possible to split the two into two different options?

Thanks.

**Comment by AcidWeb** [comment]
Technically I could be possible but I'm not going to do that.

**Comment by occivink** [comment]
Okay, I don't mind keeping my own patch. If anybody else is not interested in right-to-left page turns, you should modify the code (here)[https://github.com/ciromattia/kcc/blob/master/kcc/comic2ebook.py#L274]

**Comment by occivink** [comment]
Would you maybe accept a pull request with the proposed feature, or are you opposed to it conceptually? 
I'd keep it CLI only.

**Comment by AcidWeb** [comment]
There are two reasons why I don't want to touch it:
- Some of casual users are already confused by number of options and I don't want to dilute options even more.
- KindleGen is a black box and I already had some anomalies that discourage me to experiment with new header combinations. It is QA nightmare.
