### ISSUE TITLE
All outputs have over cropped images

### ISSUE THREAD

**Issue by hakarune** [ciromattia/kcc#217]
I've tried about 15 different ways to convert comics to epub for Kobo and android eBook readers, but every result ends in over cropped images that cut off large chunks of pages. Tested the sample outputs on github and all of them do the same thing on any Android device I have, don't work on my nook or computer ereader..

Posted a screen shot of what page 1 looks like on my devices (some have epub3 reading, but it's even worse looking).

![screenshot_20161129-004602](https://cloud.githubusercontent.com/assets/2251942/20702606/5c8d1c48-b5cd-11e6-86f2-de35a3ab97e6.png)

**Comment by AcidWeb** [comment]
What is your target device?

**Comment by hakarune** [comment]
I need correct my issue comment, it's not a kobo, it's a nook. Sorry, it's brand new and forgot the brand.

**Comment by AcidWeb** [comment]
Well then is not a surprise that sample files don't work correctly. KCC output is not generic. You need to experiment with "Other" profile. I don't even know if Nook can parse correctly EPUB 3.0.1 created by KCC.

We officially not support other devices than Kindle and Kobo.

**Comment by AcidWeb** [comment]
I would love too hear if you found any way to display it correctly on Nook. Some time ago KCC output was compatible with it but there have been many changes since then.

**Comment by hakarune** [comment]
I never got it to work for Nook or other Android readers and I returned the Nook after a month with it. I bought one of the newest Kindles instead, KCC works great on it.

**Comment by Link-Satonaka** [comment]
This is not the nook's fault, this is a problem with your css stylesheet, @AcidWeb 
I guess, for whatever reason, the other readers are simply ignoring or correcting for errors in the stylesheet.

You can demonstrate this by opening the various `OEBPS/Text/0002-uapfsic-kcc.xhtml` pages in a browser. 
![1485714167](https://cloud.githubusercontent.com/assets/4342746/22406723/10830a54-e626-11e6-97ad-2a5317846028.png)

**Comment by AcidWeb** [comment]
It should look like this.

**Comment by Link-Satonaka** [comment]
Why is that?

Changing from
`background-position: center center;`
to
`background-position: center top;`

fixes it.
![1485714714](https://cloud.githubusercontent.com/assets/4342746/22406801/86790ff0-e627-11e6-94ca-de1c358801fc.png)

**Comment by AcidWeb** [comment]
In browser - yes. But KCC output is not open by browser.

**Comment by Link-Satonaka** [comment]
If you're saying this is part of epub spec, fine.

However, the nook has the same rendering error. You can create a nook profile with an alternate stylesheet.

**Comment by AcidWeb** [comment]
I could. But I don't support Nook officially. I would not do anything else than creating profiles if I had to fix every e-reader quirk.

**Comment by AcidWeb** [comment]
Also `background-position: center top;` is not a solution as it would not center properly pages that are lower than the resolution of device.

**Comment by Link-Satonaka** [comment]
Would you like to collaborate to find a workable solution, then? I would be happy to help fix this.

**Comment by AcidWeb** [comment]
Next major release (ETA unknown) will drop usage of `background` as image holder. That also should fix Nook parsing.

**Comment by AcidWeb** [comment]
@Link-Satonaka Fix is already in dev branch. If you can check it.

**Comment by Link-Satonaka** [comment]
Success! Thank you.

As a side note, the current release's ePubs could not be opened by zathura (no pages found)- but ePubs from the dev branch kcc work fine. Whatever you did seems to have generally improved the validity of the ePubs in general.

**Comment by AcidWeb** [comment]
Great to hear that.
