### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Shadowmoo** [ciromattia/kcc#219]
Trying to kindleify a cbr that I merged in comicrack. It is about 207MB I keep getting List  index out of range.

**Comment by AcidWeb** [comment]
Please upload this file somewhere and send me e-mail with link and our KCC configuration.

**Comment by AcidWeb** [comment]
I can't fix it without it.

**Comment by AcidWeb** [comment]
Closed due to lack of feedback.
