### ISSUE TITLE
KCC with Win 10

### ISSUE THREAD

**Issue by Stoneman235** [ciromattia/kcc#220]
hi, im using win 10 since today and the KCC needs the kindlegen.exe and it looks like this do not work on win 10. am i doing something wrong or is it just not working with win 10?

**Comment by AcidWeb** [comment]
Yes. You doing something wrong.

**Comment by Stoneman235** [comment]
i did just like every time and he is too long creating epub files

**Comment by AcidWeb** [comment]
Any error appear? Progress bar move?

**Comment by Stoneman235** [comment]
progress bar moves, but nothing happens. no error

**Comment by AcidWeb** [comment]
Then define "too long". Because it might work quite long on older computers.

**Comment by Stoneman235** [comment]
i can not abort it.

**Comment by Stoneman235** [comment]
aah im stupid, need to run as admin. /close
