### ISSUE TITLE
Damaged File

### ISSUE THREAD

**Issue by thesticker** [ciromattia/kcc#225]
Hello,
I am running a macbook air, osx yosemite. I downloaded the binary version of the newest update, but whenever I try to run the program I get a message which states it is "damaged and cant be opened."It then gives me the option to delete the file. Any help would be appreciated.

**Comment by AcidWeb** [comment]
Anybody else can confirm this problem? Can't replicate it on any OS X machine.

**Comment by chokchai** [comment]
I got the same problem.

Macbook Air Mid 2012 
OSX Sierra 10.12.3

**Comment by AcidWeb** [comment]
I just uploaded new build - check it out.

**Comment by chokchai** [comment]
It fixed ! 
Thank you very much.
