### ISSUE TITLE
Cover Image's ratio is not preserved.

### ISSUE THREAD

**Issue by AlphaFactory** [ciromattia/kcc#226]
I'm using Kindle Paperwhite 32GB Manga version release in Japan.
But cover image's ratio is not preserved.

There is no problem to read the book, but cover art's ratio is the only minor problem.

**Comment by AcidWeb** [comment]
You talking about cover in the book or in the library view?

**Comment by AlphaFactory** [comment]
Yes.
When i read the book, it's ok.
But the problem is the library view, as you told.
When I make fixed-layout epub file for comic personally and convert it using kinglegen, it works ok.
Maybe something wrong in KCC.

![asdf001](https://cloud.githubusercontent.com/assets/3192805/23066102/36b19f48-f55c-11e6-9f3f-4c8b737dc899.jpg)
this is original photo.

![20170217_215714](https://cloud.githubusercontent.com/assets/3192805/23066180/91e68fe0-f55c-11e6-8f41-2f060ac237f5.jpg)
Left is what i make, right is made by KCC.

**Comment by AcidWeb** [comment]
Yeah all cover thumbnails are resized to 300x470 for better compatibility. Some time ago Kindle started to allow bigger thumbnails. I need to check it and tweak output size.

**Comment by AcidWeb** [comment]
After additional testing I noticed that 300x470 still work best. So I'm leaving this unchanged.
