### ISSUE TITLE
Mobi files cover kindle email

### ISSUE THREAD

**Issue by exejutable** [ciromattia/kcc#227]
I see this issue https://github.com/ciromattia/kcc/issues/194 and the wiki https://github.com/ciromattia/kcc/wiki/Automatic-cover-upload.

When I send my mangas by email it does not have cover ,any idea how i can fix this?

thanks for the awesome library!

**Comment by AcidWeb** [comment]
You can't fix it. Amazon e-mail delivery system just work this way.

**Comment by exejutable** [comment]
Create a .mobi without using your library, send it in the same way and the cover appears , i think is a library issue maybe?

**Comment by AcidWeb** [comment]
KCC need to create special MOBI files that simply work this way with Amazon e-mail delivery system.
