### ISSUE TITLE
File damaged linux mint

### ISSUE THREAD

**Issue by aragornito** [ciromattia/kcc#228]
Recently update to the latest version and now the app it's not working.
Can you upload a new one for linux.
Thanks!

**Comment by AcidWeb** [comment]
Please elaborate "not working".

**Comment by aragornito** [comment]
The app doesn't run after the installation.

**Comment by AcidWeb** [comment]
Start it from command line (`kcc`). Any errors appear?

**Comment by aragornito** [comment]
Traceback (most recent call last):
  File "kcc.py", line 70, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "kindlecomicconverter/KCC_gui.py", line 27, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
ImportError: /tmp/_MEIaV2IWu/libX11.so.6: undefined symbol: xcb_poll_for_reply64
Failed to execute script kcc

**Comment by AcidWeb** [comment]
Well that is something new. And I can't replicate it in any of testing environment.

**Comment by aragornito** [comment]
ok

**Comment by AcidWeb** [comment]
Please try this one:
https://mega.nz/#!h4FwkZIb!vQAlXVs9_hfxlWqNsQpySl9WE44oEry-WWKez6UIscM

**Comment by AcidWeb** [comment]
Closed due you lack of feedback.

**Comment by GuihToledo** [comment]
Hello, I have the same problem, tried this link, but doesn't work

**Comment by aragornito** [comment]
Finally I quit from kcc and now I read my comics on my tablet.

**Comment by AcidWeb** [comment]
I can only suggest to use pip or source code version.
