### ISSUE TITLE
Permission errors on Windows

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#230]
Some users still get random `PermissionError`, `[WinError 5] Access is denied`, `[Errno 13] Permission denied` exceptions during work on temporary files created by KCC.
I can't replicate this problem in any environment and failed to workaround this issue. It is probably caused by some specific AV software.

Any feedback would be appreciated.

**Comment by mccartykim** [comment]
I have a Windows environment and some Python experience, and would like to contribute if possible.  Not sure how exactly I'd go about recreating it if it calls on proprietary antivirus software.

**Comment by AcidWeb** [comment]
I have no idea how to reproduce this issue.

**Comment by AcidWeb** [comment]
Issues are caused by faulty multithreading support.
It will be hopefully fixed in 6.0.
