### ISSUE TITLE
KCC crash whenever try to browse for a file or directory

### ISSUE THREAD

**Issue by alexr4y** [ciromattia/kcc#232]
![error](https://cloud.githubusercontent.com/assets/26669111/24320931/a2734d44-1159-11e7-8863-7c67b891d802.png)

Hi KCC is keeping crashing KCC crash whenever try to browse for a file or directory, I have tried to reinstall and tried admin permission, compatibility but no avail.

below the application error in windows log

Windows 8.1 64 Bit

Faulting application name: KCC.exe, version: 5.3.1.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 6.3.9600.18438, time stamp: 0x57ae642e
Exception code: 0xc0000005

``
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2017-03-25T08:48:13.000000000Z" /> 
  <EventRecordID>46334</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DELL-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>KCC.exe</Data> 
  <Data>5.3.1.0</Data> 
  <Data>00000000</Data> 
  <Data>ntdll.dll</Data> 
  <Data>6.3.9600.18438</Data> 
  <Data>57ae642e</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000057474</Data> 
  <Data>3fc4</Data> 
  <Data>01d2a5446ff2a384</Data> 
  <Data>C:\Program Files\Kindle Comic Converter\KCC.exe</Data> 
  <Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
  <Data>c769a87c-1137-11e7-8297-acd1b8daa704</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>``

**Comment by AcidWeb** [comment]
It look like bug in QT/PyQT itself. Can't really help you.

**Comment by AcidWeb** [comment]
Please check if 5.4 still crashing.
