### ISSUE TITLE
KCC not working on Windows 10

### ISSUE THREAD

**Issue by lillumultipass** [ciromattia/kcc#236]
Dear Sir, 

I can open KCC but as soon as I try to select a file or a directoryI get an error message saying it has ceased to function. 
I am using Windows 10 64bits Pro version 14393.1358

I have also tried at home on my Macbook pro but I haven't been able to install it with Brew up to now, but that's another issue. 

thanks for your help.

best, 

Frederic

**Comment by AcidWeb** [comment]
It look like some QT problem. I will try to check it out.

**Comment by AcidWeb** [comment]
Next release should fix it.
