### ISSUE TITLE
Panel View Still broken on Kindle 3.

### ISSUE THREAD

**Issue by TheRadziu** [ciromattia/kcc#237]
Hello, 
Recently I obtained Kindle 3 (k3gb version) and I wanted to test out manga reading on that device. 
Found your program and sadly Panel View is broken. After enabling HQ panel view manga is still displayed in full screen without any zoom AND it now requires me to press next page button 5 times (4 times it just refreshes the page). 
Same happens on sample file I downloaded from your website.

**Comment by AcidWeb** [comment]
And without HQ mode?

**Comment by AcidWeb** [comment]
I presume you using newest firmware.

**Comment by TheRadziu** [comment]
Yeah, im on 3.4.2 (latest FW available for this device)
HQ: as described in first post (5 presses to go to the next page)
2: 3 button presses with 2 refreshes 
4: as in HQ but file is smaller
of course, there is no panel zooming or anything, im still seeing full page.

**Comment by AcidWeb** [comment]
Well unless somebody fix it probably this is end of K3 support. Current code generate proper Panel View code for all devices newer than K3.

**Comment by TheRadziu** [comment]
Sure, I can cope with manual zooming in cbz file (using Q/W/F keys) 
but, someone mentioned that it worked in older version of KCC:
https://github.com/ciromattia/kcc/issues/174
Perhaps you still have kcc 3.1 installer/files I could try?

**Comment by AcidWeb** [comment]
No. But if you really want to use it you always can use this git repository and rewind it to right moment.

Im closing this issue and creating separate one.

**Comment by axu2** [comment]
@TheRadziu Might be fixed in above PR
