### ISSUE TITLE
Kindle Keyboard and Kindle Touch - Panel View support

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#238]
Current HTML code created by KCC is compliant with Amazon standards. After conversion to KF8 format Panel View feature is available on all readers that support it not counting Kindle Keyboard.

Apparently KF8 renderer work differently on K3. And one of many changes in page structure that made KCC output more generic broken PV support.

I'm planning to disable PV support in K3 profile until somebody want invest time to find workaround and/or proper fix.

**Comment by ciromattia** [comment]
I'm still on my beloved Kindle Keyboard ;)
I'll try to look at it in a while, but don't hold your breath!

**Comment by AcidWeb** [comment]
Im quite sure there is something wrong with PV divs/css. They are detected and page flow is OK. But they should be displayed on top of main image and they are not.

I don't have access to K3 anymore so can't check it.

**Comment by AcidWeb** [comment]
Apparently 4th generation of Kindle devices is also affected by this problem (#239). 5th and newer are working correctly.

**Comment by AcidWeb** [comment]
@ciromattia @YeahThatGuy Had a chance to check it up on real hardware. 

Only Kindle Keyboard (3.4.2) and Kindle Touch (5.3.7.3) is affected. All 5th gen (and newer) devices are working correctly. Even Kindle 5 with 4.1.3 firmware!

On these two models Panel View work correctly. Entire structure is detected and flow is working as expected. Even image inside panel is displayed but for some reason height and width parameters of <img> are ignored and image don't overflow the screen - so there is no zoom.

I failed to found any workaround. But I'm quite sure some HTML/CSS hack is required for that models.

**Comment by AcidWeb** [comment]
Kindle Keyboard is now 9 old. Lets stop pretending that anybody will do anything with this issue.
