### ISSUE TITLE
Panel View doesn't work for Kindle Touch

### ISSUE THREAD

**Issue by YeahThatGuy** [ciromattia/kcc#239]
Hi, I've got kindlegen.exe in the root folder of KCC.
Tried converting as per instructions (image -> rar -> cbr -> mobi), but the panel view will simply not trigger at all. The same issue persists with the samples that you've provided.
Attack on Titan from Amazon works fine, so maybe it's a metadata issue?
Can you please check?

**Comment by YeahThatGuy** [comment]
Also, I didn't notice a Kindle Touch profile, so I tried converting with the profiles for both "Kindle" and "Kindle PW 1/2".

**Comment by AcidWeb** [comment]
Kindle Touch should use "Kindle" profile.

Could you elaborate "doesn't work"? How you trying to use it?

**Comment by YeahThatGuy** [comment]
Hey mate, yes I can.
I'll list my steps. Hopefully that will help.

1. Archive the manga images folder (just 1 chapter) to either .rar or .zip
2. Change the extension to .cbr for .rar and .cbz for .zip
3. Convert the .cbr or .cbz to .mobi via KCC (all options by default, Kindle profile)
4. Paste the resulting .mobi into the "documents" folder in Kindle
5. Open the file and double tap to activate the panel view
6. The page slightly extends in width (literally like 1%)
7. The panel window appears in the bottom right corner, but the page does not get zoomed in
8. As a result the panel window looks empty inside and by swiping to the next page, the current page flickers around 3-4 times
9. So basically it is interpreted as panel view, but the panels don't get zoomed in
10. So I get the same full scale page 4 times, instead of each of the 4 corners being zoomed in sequentially.

Thank you

**Comment by AcidWeb** [comment]
And this problem appear in sample file too?

**Comment by YeahThatGuy** [comment]
Yes, it also persists on Ubunchu!-K45.mobi

**Comment by AcidWeb** [comment]
Apparently 4th generation of Kindle devices is also affected by unknown regression. Closing it as duplicate.

**Comment by AcidWeb** [comment]
One more question. Which firmware version you use?

**Comment by YeahThatGuy** [comment]
It's version 5.3.7.3. I believe it's the latest for Touch.

**Comment by axu2** [comment]
@YeahThatGuy Might be fixed in above PR
