### ISSUE TITLE
Cannot find KindleGen

### ISSUE THREAD

**Issue by glupiowyszlo** [ciromattia/kcc#245]
I installed Kindle Comic Converter on macOS Sierra. It says "Cannot find KindleGen". Install it using Brew". I guess I installed the Brew by copying the right command from their webstite to Terminal but I got stuck on KindkeGen things. Please be humans and explain it step by step (or link me some tutorials maybe) how to do it to total noob :( Thanks a lot!

**Comment by AcidWeb** [comment]
Exactly what error you getting when you execute `brew cask install kindlegen`?

**Comment by glupiowyszlo** [comment]
Actually... I never tried this command. Tried many other (as I said I totally don't get the coding things) I found at Brew. Thanks a lot for fast answer. Now it works exactly like it should. I don't know if I have to delete this Issue or maybe it will be useful for other people who are not familiar with coding magic :) Thank You very much!
