### ISSUE TITLE
Option to merge chapters togheter

### ISSUE THREAD

**Issue by mojimi** [ciromattia/kcc#246]
Anyone that owns a 8th gen Kindle knows that it has no support for multi chaptering, and it's a pain in the ass to read one after another.

The easiest solution is to merge everything in one ebook, but I couldn't find a way to do this in kcc

**Comment by AcidWeb** [comment]
https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting

**Comment by AcidWeb** [comment]
Just convert archive or directory that contain your chapters.
