### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by jmgant** [ciromattia/kcc#247]
When I change the metadata of the KCC mobi files with Calibre, the change is not reflected on my Kindle. I was informed that metadata can not be changed for the mobis KCC generates. If this is the case, can that be changed so that plugboards which sort by series can better organize KCC files on the reader?

**Comment by AcidWeb** [comment]
No. It can't. Calibre don't support editing metadata in hybrid MOBI files created by KindleGen that KCC use.

You need to set all metadata before conversion.
