### ISSUE TITLE
Panel View HQ stretches image

### ISSUE THREAD

**Issue by adelin07** [ciromattia/kcc#248]
Hello! 

I own a kindle paperwhite 2 and using the target device as Kindle PW 1/2, Manga mode checked, Spread splitter checked, Panel View checked(for 4 HQ panels) results in a [stretched image](https://user-images.githubusercontent.com/29884255/30775275-02f7b794-a099-11e7-844d-4ccf2682de83.png), even thought it auto-forces the upscale option which should prevent stretching.

I've tried this with more mangas and the result is always a stretched image. Both unchecked and intermediate settings work [correctly](https://user-images.githubusercontent.com/29884255/30775276-02f809b0-a099-11e7-8b7b-fb0504ad9400.png), outputting the proper aspect ratio(stretch/upscale setting works as intended).

**Comment by AcidWeb** [comment]
I presume you tested it on real device too?

**Comment by adelin07** [comment]
Yes, of course. It looks the same on my device as it does on the screenshots I took.

**Comment by AcidWeb** [comment]
OK. I not touched that part of code for some time and for now I'm not 100% sure if it is a bug or expected behavior.

I will check it out.

**Comment by AcidWeb** [comment]
Found the problem. It will be fixed in next release.

**Comment by adelin07** [comment]
Thank you! Looking forward to it!
