### ISSUE TITLE
Support for New Kindle Oasis 2nd Gen

### ISSUE THREAD

**Issue by notdevinclark** [ciromattia/kcc#249]
There was a new Kindle announced today that has a 7 inch screen and a 300dpi screen. 

Here is a link to the [Amazon Page](https://www.amazon.com/All-New-Kindle-Oasis-reader-Built/dp/B06XD5YCKX).

Still trying to find documentation on the exact pixel size of the screen. It can hold up to 32GB so it is a great option for holding lots of comics and if it (should) support a higher resolution which is always welcome with tiny text in comics.

I thought that I would put a note here as a question of whether this will be included in a future roadmap.

**Comment by AcidWeb** [comment]
There will be KCC release with new profile before Oasis 2 launch.

**Comment by AcidWeb** [comment]
Screen resolution: 1264x1680

**Comment by notdevinclark** [comment]
Nice, that's awesome. Thanks for the super fast reply. Where did you find the official resolution? Was trying to find it to add it to the ticket to help out.

**Comment by AcidWeb** [comment]
https://s3-us-west-2.amazonaws.com/customerdocumentation/EC9/Kindle%20Users%20Guide%20EN-US.pdf

Page 45.

**Comment by notdevinclark** [comment]
Awesome. Didn't realize the manuals were available since the product was not available just yet. Good to know. Thanks again.
