### ISSUE TITLE
Some CBZ can't fit content width correctly

### ISSUE THREAD

**Issue by seacatwu** [ciromattia/kcc#252]
I have used kindle comic converter to convert comics, and use some eink device which installed KOreader.
And I found that KO can't fit the content width correctly of these comics.
Is the KCC's output not suit for the KO?

**Comment by seacatwu** [comment]
![image](https://user-images.githubusercontent.com/9783549/31976093-e85350aa-b967-11e7-98ca-df4e4d131b8e.png)
I have zipped this pic and tested again.
Still cant't fit by content width.

**Comment by AcidWeb** [comment]
KCC output was never tested with KOReader. What is "some eink device"?

**Comment by seacatwu** [comment]
@AcidWeb 
Ireader Plus (android eink）,kobo aura h2o and kobo aura one.

**Comment by AcidWeb** [comment]
Can't say anything about Ireader Plus but you should use KEPUBs on Kobo.

**Comment by seacatwu** [comment]
@AcidWeb I like Koreader, for it can fit content width.

**Comment by AcidWeb** [comment]
Make sure that upscaling is enabled.

**Comment by seacatwu** [comment]
I have tried all the options in the row 2, but nothing help.

**Comment by AcidWeb** [comment]
I never used Koreader so can't really help.

**Comment by seacatwu** [comment]
@AcidWeb ok
