### ISSUE TITLE
Mobi/AZW3 Table of Contents

### ISSUE THREAD

**Issue by Ceroes** [ciromattia/kcc#254]
Im not sure if this is limited to the Kindle 3 Keyboard, but when I convert a folder with folders inside it doesn't give me a table of contents when loaded onto the kindle I can see the dots in the bar but I cannot "go to" the table of contents and they Aren't at the end of the file either. I copy directly through windows explorer, and nothing but dots no real table of content. If I convert it in Calibri or even just view it in there it will show the table of contents except the file now shows as a picture in books. is it just that I am using a Kindle 3 or is there something I am doing wrong

**Comment by AcidWeb** [comment]
I don't seen any K3 for long, long time. I can just confirm that files created with K3 profile have proper TOC.
I don't remember if K3 fully support TOC in comic type e-books.
