### ISSUE TITLE
Large conversion on small C drive

### ISSUE THREAD

**Issue by webster58** [ciromattia/kcc#257]
There is a feature I would like to propose.
When converting large manga Volume ( 1gb + ) whole cache goes to C:/ drive which in mine case is tiny and always full. Is there any possibility to add custom folder as Temp on other drive for cache files ?
Also this would reduce write strain to SSD drive for users who care about it.
I wouldn’t even dream of an option to store whole cache in RAM if enabled. RAM amount is not a problem :)

**Comment by AcidWeb** [comment]
Write strain of SSD drive is not a problem in 2018 year.

If your system drive is always full you have bigger problems than KCC :-)
KCC use standard multi-platform temporary file handling and in case of Windows it will use directory declared in environmental variable `TEMP`.
