### ISSUE TITLE
[Feature Request] Two-page spread support

### ISSUE THREAD

**Issue by gianlucaparadise** [ciromattia/kcc#258]
Option to rotate two-page spread.

### Feature Description
The KCC should recognize a two-page spread and rotate it vertically instead of splitting it in two pages.

### Motivation and Context
This is useful because when a two-page spread is split, it's really difficult to read. If it is rotated, you can rotate your e-reader and read it easly.

**Comment by AcidWeb** [comment]
Options to do that already implemented. Check tool-tip of "Spread splitter" option.
