### ISSUE TITLE
Release 5.4.3 dosen't has No Splite/rotate

### ISSUE THREAD

**Issue by guoqingaa** [ciromattia/kcc#259]
I don't have see [No Splite/rotate]
Disable page splitting and rotation.
Can increase this option。

**Comment by guoqingaa** [comment]
I need Horizontal mode.
Disable splitting of two-pages spreads.

not rotated, no Splite Image, images real resolution size.

**Comment by guoqingaa** [comment]
My non-Kindle device, same resolution as PW3.
Set as follows, a single picture will be split into two halves. In addition, the picture has also been cut, can not cut.
Do not want to split the picture and rotation, can I?
thank you！

![设置](https://github.com/guoqingaa/ImageTmp/blob/master/20180223162105.png?raw=true)
![导出](https://github.com/guoqingaa/ImageTmp/blob/master/20180223162106.png?raw=true)

**Comment by AcidWeb** [comment]
I don't understand you.

If you want only to rotate image then check "Spread splitter" option. Then images will be displayed horizontally without cutting.

That is best than KCC can do.

**Comment by guoqingaa** [comment]
I don't want  to rotate image.
Then images will without cutting.
The image retains its original size.

**Comment by AcidWeb** [comment]
KCC can't do that.

**Comment by guoqingaa** [comment]
checked 【Spread splitter】
checked 【Stretch/Upscale】
![图1](https://github.com/guoqingaa/ImageTmp/blob/master/20180223164452.png?raw=true)
![图2](https://github.com/guoqingaa/ImageTmp/blob/master/20180223164528.png?raw=true)

**Comment by guoqingaa** [comment]
rotated image.
images cutting.
so bad.
