### ISSUE TITLE
webp input

### ISSUE THREAD

**Issue by n30na** [ciromattia/kcc#263]
Add support for webp images in input files.

**Comment by n30na** [comment]
I'm unsure if this would be useful for many others, but at least in my particular workflow I have a source that always uses webp images. I'm currently batch converting them to png, but if KCC supported the format directly it would certainly be helpful.

**Comment by AcidWeb** [comment]
Current WebP implementation in Pillow have memory leaks so lets put on back burner for now.

**Comment by jgoux** [comment]
This would be awesome. I have more and more webp based cbz to convert and I always have to rely on a third party app before KCC. 😭
