### ISSUE TITLE
Error E21027 while creating mobi file from images

### ISSUE THREAD

**Issue by as3ii** [ciromattia/kcc#269]
I've a zip file that contain some comics images. When I start the conversion with `"kcc-c2e -p KPW ./file.zip"` it print the following text ending with the error line. How can I resolve the problem?
![screenshot_2](https://user-images.githubusercontent.com/29260716/40612804-42ba1d36-627c-11e8-89cb-0fd7ab528987.png)
OS: linux ubuntu 16.04 (WSL)

**Comment by AcidWeb** [comment]
What is in file.zip? Only images? Something else?

**Comment by as3ii** [comment]
in the zip file there is only .png files

**Comment by AcidWeb** [comment]
Add `-f EPUB` option and upload created EPUB file somewhere I want to check its structure.

**Comment by as3ii** [comment]
command used: `kcc-c2e -f EPUB tokyo_ghoul_re_1-2.zip`
output: ![screenshot_2](https://user-images.githubusercontent.com/29260716/40615172-f43b9cac-6285-11e8-92a6-c67db97d0fe2.png)
output file: http://www.mediafire.com/file/4qcxybb7w6zngwe/tokyo_ghoul_re_1-2_kcc0.epub

**Comment by AcidWeb** [comment]
This file was valid and could be converted to MOBI without any problem.

Make sure there is no EPUB files in directory that contain your input file and try to convert it again. kcc-c2e -p KPW file.zip`. After it crash check if there is any epub file there and upload it if there is.

**Comment by as3ii** [comment]
this is the only file made with `kcc-c2e -p KPW tokyo_ghoul_re_1-2.zip` : http://www.mediafire.com/file/sxy1eiw982puzuo/tokyo_ghoul_re_1-2.epub
same error as before while converting in .mobi

**Comment by AcidWeb** [comment]
This file was OK too.

Upload me source ZIP file.

**Comment by as3ii** [comment]
source file: http://www.mediafire.com/file/52evzy8r1yuq50z/tokyo_ghoul_re_1-2.zip

**Comment by AcidWeb** [comment]
Can't replicate this crash on Windows - I will check Linux later.
ZIP don't contain only images. There is also empty directory called "." there. Maybe that cause some issues with paths.

**Comment by as3ii** [comment]
ok, problem solved. kindlegen have some problem when working on wsl. Using native linux there is no problem
