### ISSUE TITLE
Kindle 5.9.5.2 displays duplicate entries of KCC generated file

### ISSUE THREAD

**Issue by 29988122** [ciromattia/kcc#270]
Steps to reproduce:
1. KCC 5.4.5 GUI, manga mode, Kindle Oasis 2, mobi/AZW3.
2. Upload generated mobi file to kindle cloud - "Personal Document". As an experiment, I added it to a collection(categorize/label/tag).
3. On Web page "Device Content Management" it's normal, no duplicate entries. 
4. On Kindle Oasis 2 with system software version 5.9.5.2, before download you first saw one entry, normal.
5. Download the KCC generated document to your kindle.
6. After download/sync finished, it will show TWO entries where one cannot be deleted and edited. 
![2018-06-12 16 32 12](https://user-images.githubusercontent.com/5474709/41279333-bfa42808-6e5e-11e8-8252-f9b0d4f5e7df.jpg)
![2018-06-12 16 32 20](https://user-images.githubusercontent.com/5474709/41279334-bfd27280-6e5e-11e8-9b49-96e0ea95a0d3.jpg)
![2018-06-12 16 32 03](https://user-images.githubusercontent.com/5474709/41279336-c013594e-6e5e-11e8-91a4-65938b058512.jpg)

7.The blank entry has the correct parameter(collection label), but cannot be edited or opened as you can see in the pictures above; while the viewable entry does not have the correct collection parameter.

Expected results:
Only one entry on Kindle

Possible solution:
It is perfectly normal on cloud, and I deleted all the remains and regenerated mobi a few times in case it's some remain files in kindle which caused the bug. 

So it's probably some strange metadata / format parsing behavior on Kindle Oasis 2 5.9.5.2. 

Because Kindle Comic Creator(bad piece of software btw, yours are a ton better)generated normal mobi file for Kindle, I guess it's whether the mobi creation behavior of KCC does not follow kindle azw3 standard, or Amazon's Kindle Comic Creator has some hidden behavior that will make devs hate them.

I can provide logs or other information to you in order to help solve this bug, thank you for your hard work!

**Comment by AcidWeb** [comment]
It looks like Amazon Cloud don't like changes in file header that are made by KCC.

I will check it out but there is high chance this is unfixable. I highly suggest to upload KCC output over USB.

**Comment by 29988122** [comment]
Wow that was lightning fast, thank you.
I agree if Amazon Cloud changed the file header/metadata we sent then there's hardly anything we can do to bypass that behavior.

**Comment by AcidWeb** [comment]
As expected Amazon Cloud really dislike my metadata changes. When _Personal Document Archiving_ option is disabled (and send books are not saved to cloud) everything is working correctly.

I'm not planning to fix it.

**Comment by 29988122** [comment]
I can totally live with that, thank you for the magnificent piece of software!
