### ISSUE TITLE
epub as a source file

### ISSUE THREAD

**Issue by linuxrecon** [ciromattia/kcc#271]
I bought the recent Humble Manga Bundle and downloaded a bunch of the ePub files with my slow internet connection (~150MB for a ePub file and ~1.2GB for a CBZ file). Unfortunately KCC doesn't support ePub as the input source. Sending the downloaded ePubs from Humble Bundle directly to my eReader (a Tolino Shine 2 HD in this case) results in too big pages making almost 50% rendering off screen and therefore unreadable.

Is there any possibility that you may add ePub as the source as well?

**Comment by AcidWeb** [comment]
EPUB is a zip file. You can unpack image files.

**Comment by ciromattia** [comment]
Did you try using directly kindlegen on your ePub files?

**Comment by linuxrecon** [comment]
I'm a Tolino Shine 2 HD user. It looks like that kindlegen only works for Kindle devices. You can't pass height and width to the kindlegen command and therefore I'm unable to change those to the one my Tolino expects.
