### ISSUE TITLE
detectCorruption should be more specific when it encounters a problem

### ISSUE THREAD

**Issue by zackw** [ciromattia/kcc#272]
KCC's [`detectCorruption`](https://github.com/ciromattia/kcc/blob/master/kindlecomicconverter/comic2ebook.py#L848) function simply tries to load each page using PIL, and if that throws any exception at all, it converts that to the nonspecific error message "Image file %s is corrupted".  I had to load up a Python interpreter and manually execute the code in there to find out what was actually wrong with my input images (which several other programs were perfectly fine with).

Please include `str(err)` in the error message, or better still, ditch all of that and just reraise the original exception after cleaning up:

                try:
                    ...
                except Exception:
                    rmtree(os.path.join(tmppath, '..', '..'), True)
                    raise

**Comment by AcidWeb** [comment]
It makes sense.
