### ISSUE TITLE
Increase Image.MAX_IMAGE_SIZE or make it configurable

### ISSUE THREAD

**Issue by zackw** [ciromattia/kcc#273]
PIL has a fixed (but configurable) upper limit on the size of images it will process, in order to limit the risk of [decompression bomb attacks](https://en.wikipedia.org/wiki/Zip_bomb) in casual usage.  It is reasonable to want to feed extremely large images to KCC -- I have here a PDF-format comic book that was created by scanning the print version at something like 1600dpi:

```
$ identify arslan-v1_Page_184.png 
arslan-v1_Page_184.png PNG 11060x16590 11060x16590+0+0 8-bit sRGB 41.462MiB
```

This causes KCC to barf in `detectCorruption` because PIL won't even load the file:

```
>>> Image.open("arslan-v1_Page_184.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2577, in open
    im = _open_core(fp, filename, prefix)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2568, in _open_core
    _decompression_bomb_check(im.size)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2507, in _decompression_bomb_check
    (pixels, 2 * MAX_IMAGE_PIXELS))
PIL.Image.DecompressionBombError: Image size (183485400 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

If I increase `MAX_IMAGE_PIXELS` it loads fine:

```
Image.MAX_IMAGE_PIXELS = 1600 * 1600 * 10 * 10
>>> Image.open("arslan-v1_Page_184.png")
<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=11060x16590 at 0x7F781FD232E8>
>>> _.verify()
>>> 
```

Please add code at an appropriate place in KCC to increase this limit, and ideally make it adjustable from the GUI.

**Comment by 0xDedSec42** [comment]
I just tried to convert a quite large PDF and got the same error message. Is there a way to change the MAX_IMAGE_PIXELS other than editing the source code?

**Comment by axu2** [comment]
@0xDedSec42 how big we talking about?

If it's from humble bundle or fanatical check the readme.

**Comment by 0xDedSec42** [comment]
Yes, it's from Humble and about 1.11 GB. 

Are you referring to #680 when mentioning the readme?

**Comment by axu2** [comment]
@0xDedSec42 

Yes. Can you tell me which humble comic you are using?

**Comment by 0xDedSec42** [comment]
Sure. It's the book "the world of cyberpunk 2077".

**Comment by axu2** [comment]
@0xDedSec42 Did you get the humble method working? Humble is super high resolution stuff and the text isn't stored as part of the image, so "flattening" it to a cbz with mutool is a needed first step.

**Comment by 0xDedSec42** [comment]
Yes, I just converted the book successfully. I'm using a PocketBook Era Color, so I set the resolution to 1680 pixels. This reduced the file size from 1.1 GB to around 400 MB. The other books I converted using KCC are much smaller though. Does it make sense to do another conversion with the usual settings I use in KCC?

**Comment by axu2** [comment]
@0xDedSec42 just try

**Comment by 0xDedSec42** [comment]
I did. At first glance, the result looks very good. File size reduced by about 80 %.
