### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lolex565** [ciromattia/kcc#274]
![przechwytywanie](https://user-images.githubusercontent.com/40698402/42102981-ee5f1e3e-7bc7-11e8-9a17-a0d4b6ae4cec.PNG)
i tried to google solution and i couldn't find anything, reinstall didn't work
my pc is
intel core i 5 7500
radeon hd series 7850
8gb ram

**Comment by AcidWeb** [comment]
What OS?

**Comment by AcidWeb** [comment]
I don't even try to debug so old OS. There are too many possible cases.

**Comment by lolex565** [comment]
found solution, problem was non-latin character in path to file
