### ISSUE TITLE
Problem image resolution with Pocketbook Inkpad 3

### ISSUE THREAD

**Issue by kepohe** [ciromattia/kcc#275]
Hello,

I have a new ereader Pocketboot inkpad 3 8inch. The screen is the same than Kobo Aura One screen (Same resolution: 1872x1404.

I have tried to convert a CBR manga into EPUB with KCC. I choosed Kobo Aura One model. But when i open this EPUB on my Inkpad 3, pages are cut down on 1CM.

How can I configure the output resolution? 

Thanks.

**Comment by AcidWeb** [comment]
You need to set custom profile and find resolution that work correctly. Same screen resolution don't mean the same screen space is available in reader.
