### ISSUE TITLE
Allow file size targets and spiting [Enhancement]

### ISSUE THREAD

**Issue by macravin** [ciromattia/kcc#276]
It would be great to allow file size targets for splitting files and/or compressing images. This would be useful for using Kindle Cloud Sync with the comics as they need to be under 50mb.

Because Kindles don't have that much memory, it would be very nice to be able to store the converted comics in the cloud and download them as desired.

**Comment by AcidWeb** [comment]
Cloud usage is not officially supported by KCC as we don't have control over header modifications made on Amazon side.
