### ISSUE TITLE
Disable extra folders created on kindle

### ISSUE THREAD

**Issue by henriquebach** [ciromattia/kcc#278]
I have Kindle Paperwhite 2, when i'm connected to PC and make a convertion, folders are created in the documents folder of the kindle. Since i put my mangas in a manga folder, i would like to be enable to not create these folder. 
Thank You!

**Comment by AcidWeb** [comment]
KCC don't create any folders.

**Comment by henriquebach** [comment]
![kcc](https://user-images.githubusercontent.com/14010593/44590559-cca10000-a791-11e8-8553-d77293aae933.png)

**Comment by AcidWeb** [comment]
Covers are not uploaded to `documents` directory.

That directory name ends with `.sdr`?

**Comment by henriquebach** [comment]
Yes, it is .sdr.

**Comment by henriquebach** [comment]
yes, i know, always when i put a manga into the kindle, an folder .sdr is created IN the files folder. this problem i'm facing is even before i copy anything to kindle, he creates this folder just because i have the kindle connected to the pc during the convertion. so i always have to remember to disconnect the device before convert anything.

**Comment by AcidWeb** [comment]
KCC don't create this directory.
