### ISSUE TITLE
Win10 Setup issues

### ISSUE THREAD

**Issue by fiveseven808** [ciromattia/kcc#279]
I'm running Python 3.7.0, Win10, did a setup install and got this error
`ERROR: PyQt 5.6.0+ is not installed!`

..when trying to run kcc.py

I can do an import PyQt5 just fine from the python console, and Python is in my path. What am I missing?

**Comment by AcidWeb** [comment]
Can't replicate this issue. I don't know your environment to make even a educated guess.
