### ISSUE TITLE
KCC don't see exe files in it's directory

### ISSUE THREAD

**Issue by Azraelless** [ciromattia/kcc#282]
![image](https://user-images.githubusercontent.com/24431227/46177103-51fc6080-c2ba-11e8-983d-a233e390b617.png)
![image](https://user-images.githubusercontent.com/24431227/46176863-7c99e980-c2b9-11e8-8f8e-cc3304056ad7.png)
I have both 7za.exe and kindlegen.exe in the proper folder, but KCC can't see them for some reason.
I used older versions of the KCC some time ago, but was unable to find older versions to try them.
I tried reinstalling, to the different folder, run as admin. Nothing helped.
I'm on Windows 10.

**Comment by AcidWeb** [comment]
Can't replicate this issue. I have no idea what is wrong.
