### ISSUE TITLE
Compatibilty with inkpad3  (from tea and pocketbook) : the image is too hight by 25 pixels 

### ISSUE THREAD

**Issue by lostin70s** [ciromattia/kcc#283]
The profile is basically the same as the  kobo aura one but need a slid up of 25pixel for all  images

I've tested by modifying the style.css file in OEBTS/text of an epub 
@page {
margin: 0;
}
body {
display: block;
margin: 0;
margin-top:-25px;
padding: 0;
}

And it works fine !

Maby it can be corrected here :
(in comic2ebook.py line 403 I can add "margin-top:-25px" just for inkpad3)
 f.writelines(["@page {\n",
                  "margin: 0;\n",
                  "}\n",
                  "body {\n",
                  "display: block;\n",
                  "margin: 0;\n",
                  "padding: 0;\n",
                  "}\n"])

**Comment by AcidWeb** [comment]
Thanks but I don't plan to implement a profile for InkPad3.
