### ISSUE TITLE
Issues with macOS binary

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#288]
We have multiple reports about crashing macOS binary on macOS older than 10.14.

I have no idea what changed and started to cause this crashes... I hope that new version will fix this issue - No ETA.
For now bare Python version should work correctly.

**Comment by GigaDanMan** [comment]
For dummies like me, how would one run the bare Python version? :-/

**Comment by josephrooks** [comment]
@AcidWeb Would an older Mac version work, and if so, could you make those available?

**Comment by AcidWeb** [comment]
Just uploaded to page a new binary that should work with 10.12+. 10.10 and 10.11 is no longer supported.
