### ISSUE TITLE
fails to build from source on Debian 9 arm64

### ISSUE THREAD

**Issue by tidux** [ciromattia/kcc#290]
```
Searching for PyQt5>=5.6.0
Reading https://pypi.python.org/simple/PyQt5/
No local packages or working download links found for PyQt5>=5.6.0
error: Could not find suitable distribution for Requirement.parse('PyQt5>=5.6.0')
```

But...

```
$ dpkg -L python3-pyqt5 | head
/.
/usr
/usr/lib
/usr/lib/aarch64-linux-gnu
/usr/lib/aarch64-linux-gnu/qt5
/usr/lib/aarch64-linux-gnu/qt5/plugins
/usr/lib/aarch64-linux-gnu/qt5/plugins/designer
/usr/lib/aarch64-linux-gnu/qt5/plugins/designer/libpyqt5.so
/usr/lib/python3
/usr/lib/python3/dist-packages
```

Something is clearly broken with setup.py here.  Installed version is 5.7.

https://packages.debian.org/stretch/python3-pyqt5

**Comment by AcidWeb** [comment]
Make a venv and don't use system packages.

**Comment by tidux** [comment]
That's non-applicable.  Pip doesn't have PyQt5 packaged for ARM.  This is why system packages exist in the first place, and if software doesn't work with a system package of an explicitly allowed package (5.7 >= 5.6) it is wrong.

**Comment by AcidWeb** [comment]
Welcome in PyQt world - this type of problems are sadly normal.
Extractly what you trying to do? `python3 setup.py install`?

BTW KCC will not work fully on ARM as it require kindlegen - and that is closed source blob that don't have ARM binary.

**Comment by tidux** [comment]
I don't care about kindlegen.  I have an ereader that speaks epub natively.  

I have tried `pip3 install KindleComicConverter` both in and out of venvs, I have tried `python3 setup.py install` both in and out of venvs, I have tried `pip3 install -r requirements.txt` both in and out of venvs.  This is not a problem with my system, this is a problem with the build system failing to find PyQt5.  

If detecting PyQt5 can not be made reliable, then it must be made optional.  Splitting the package into a headless version and a Qt version that depends on the headless version would be a reasonable workaround.

**Comment by AcidWeb** [comment]
I agree that is a problem with build system but I'm using plain setuptools without any additional modifications on my side.

If you have any idea how improve detection of system PyQT5 on ARM - I'm all ears.
If you need only CLI version you can drop PyQT from requirements. `kcc-c2e` will work without it.

**Comment by tidux** [comment]
>  If you need only CLI version you can drop PyQT from requirements. kcc-c2e will work without it.

Wrong.  It throws a stack trace whining about qt5 being missing if you install and run kcc-c2e from PATH, even with PyQt5 removed from requirements.txt.
