### ISSUE TITLE
Need append the "-dont_append_source" argument to kindlegen

### ISSUE THREAD

**Issue by ueinohakono** [ciromattia/kcc#291]
The mobi created by kindlegen is so huge because kindle will append the source files to the mobi file.
We can use the script kindlestrip.py to make the mobi be small.
But  the author said we shouldn't use the kindlestrip.py to make mobi file be small now because it may make the wrong mobi formater. We should use the arguemt "-dont_append_source" when we use kindlegen.exe to generate mobi file.
For, example "kindlegen.exe -dont_append_source xxxxx.epub".
And the mobi file will be small.

So how can I append the "-dont_append_source" argument to kindlegen.exe when I use kcc to create mobi?

**Comment by AcidWeb** [comment]
KCC already use "-dont_append_source" option during MOBI creation.
