### ISSUE TITLE
Automatic batchsplit doesn't work

### ISSUE THREAD

**Issue by DarkDeyus** [ciromattia/kcc#292]
Hello.
I was converting some comics and some of them were failing to get converted: "Error: KindleGen failed to create MOBI!" Epubs that were being generated were too big (700 - 800 MB), despite using the -b 1 (autosplit) option.

**Comment by AcidWeb** [comment]
You probably get a warning that automatic split was unsuccessful due to unsupported directory structure.

**Comment by DarkDeyus** [comment]
There is no warning about unsupported directory structure, that was the case.  Automatic split failed due to the wrong structure.

However i found the -t (setting title) option not working, it still defaults to the folder name. Should i just close this issue and open another one?
