### ISSUE TITLE
Please add support for new "Kobo Forma" device

### ISSUE THREAD

**Issue by chokchai** [ciromattia/kcc#294]
Kobo is release new model called "Kobo forma" for a while.
(8.0" 300 PPI E Ink Carta display, 1440 × 1920 resolution)
https://gl.kobobooks.com/products/kobo-forma?utm_source=Kobo&utm_medium=TopNav&utm_campaign=Forma

Please add this device to Converter options.

Thank you,
Chokchai

**Comment by AcidWeb** [comment]
I will add it in long overdue maintenance release.

**Comment by chokchai** [comment]
Thank you very much
