### ISSUE TITLE
Issues with big pages convertions with some manga.

### ISSUE THREAD

**Issue by TheSpartan94** [ciromattia/kcc#297]
Some manga title have big screen in the beginning featuring the names of translator or teams looking for staff.

These big screens are the only output of the conversion. These are often high-resolution images and landscape pages. As an example of this, here is a file.

I tried then to crop out these pages using a webtool, but the conversion then fails. Here is the cropped file:
`<snip>`

P.S. seems like i can submit only one file at a time. Sorry, i'll submit a new issue in the future.

**Comment by AcidWeb** [comment]
You use PDF as input?

**Comment by TheSpartan94** [comment]
Of course. Here is the file:
[Op Capitolo 929.pdf](https://github.com/ciromattia/kcc/files/2753090/Op.Capitolo.929.pdf)

**Comment by AcidWeb** [comment]
I highly doubt that image size is the cause. PDF support is very simple and it most probably fail to extract rest of images - that why rest of images are missing after conversion.

**Comment by TheSpartan94** [comment]
What should i do then?

**Comment by AcidWeb** [comment]
Extract images from PDF file with other tool and then convert them.
