### ISSUE TITLE
Input/Output error when converting cbz, zip or folder

### ISSUE THREAD

**Issue by anzetal** [ciromattia/kcc#299]
I'm on Kubuntu 18.10 with KCC 5.4.5.
Whenever I try to create a mobi/azw3 for the paperwhite, it displays the "creating epub files" then displays the error:

```5
Traceback:
Input/Output Error
````
![kcc](https://user-images.githubusercontent.com/35098870/52187266-7f51b000-2852-11e9-9d2d-6698122a4442.png)
I tried it in December on the same folder and it worked perfectly fine then
Python version : Python 3.6.7
kindlegen is also installed to `/usr/local/bin/kindlegen`
The cbz files are ~230 MB each

**Comment by AcidWeb** [comment]
I/O errors are caused by something above KCC.
