### ISSUE TITLE
kf8 only output?

### ISSUE THREAD

**Issue by torxt** [ciromattia/kcc#300]
Hey! 
calibre has a problem with the joined mobi file that kcc produces. 
> https://bugs.launchpad.net/calibre/+bug/1432257

i want to create my manga files with kcc and organize them with calibre, sadly calibre cannot update the metadata of files produced by kcc. i have to use kindleunpack to get a awz3 and mobi file. the awz3 file can get added back to calibre and will have proper updating metadata.

can kcc add export to awz3 only, so that calibre can directly update metadata?

**Comment by AcidWeb** [comment]
This feature was removed from KCC long ago. Splitting big MOBI files that are output of kindlegen take longer than entire conversion process. You always can set metadata before conversion.
