### ISSUE TITLE
Add support for pngquant

### ISSUE THREAD

**Issue by skewerr** [ciromattia/kcc#301]
I don't know how well PIL is able to compress both JPEG and PNG, but I've been using [pngquant](https://pngquant.org/) for applying lossy compression on my PNG files recently, and it performs really well.

Given it is lossy compression, it probably shouldn't be used alongside `--hq`, but I'd very much like the option to `--forcepng` and, say, use `--pngquant` with some default but configurable options passed to it.

**Comment by AcidWeb** [comment]
Last time I checked Kindle failed to render files created by pngquant. But I will check it out again.

Additionally usage of PNG is output is somewhat embivalent as we are not 100% sure what extractly KindleGen do with these files.

**Comment by AcidWeb** [comment]
Yeah issues are still there. `pngquant` is still no-go.
