### ISSUE TITLE
pdf rotation handling

### ISSUE THREAD

**Issue by AndCycle** [ciromattia/kcc#304]
I am new to kcc,

my collection are personal scan by ScanSnap iX500, 

here is few page of the pdf for demonstrate the issue,
https://1drv.ms/b/s!ArlB91L9JmXYu1LDVm7-k7Wey7zw

I usually feed the page into the scanner side-way to prevent page jamming/tearing during the process,
which looks fine in pdf format,
but unfortunately it seems `kcc-c2e` doesn't handle the page rotation info in pdf,

after some googling looks likd `pdfinfo` is able to extract the info to tackle this problem

https://stackoverflow.com/questions/12050743/how-to-find-whether-pdf-has-landscape-orientation-or-portrait

**Comment by AndCycle** [comment]
the info can be retrieved by `PyPDF2`, which will introduce extra dependency

`  PyPDF2/PyPDF2/pdf.py `
```
class PageObject(DictionaryObject):
...
    def _rotate(self, angle):
        rotateObj = self.get("/Rotate", 0)
```

**Comment by AcidWeb** [comment]
There is no plans for improving PDF support.
