### ISSUE TITLE
Linux binary builds are unavailable

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#307]
Due to migration of build pipeline Linux binary builds are currently unavailable.

Please use PyPI version.

**Comment by gelatinbomb** [comment]
@AcidWeb Hey, sorry for the inconvenience but.....how do i execute this?, i installed with pip3 and i have no idea how to run the kindle comic converter. pls help i'm on linux.

**Comment by AcidWeb** [comment]
If it is installed correctly just execute command: `kcc`

**Comment by gelatinbomb** [comment]
ooh.....that explain it xD
I think it was something like "kindlecomiccreator",  i use kde so...well i have a lot of "k" weird name binaries.

**Comment by anzetal** [comment]
hello @AcidWeb pip3 stil shows 5.4.5. Will the update be pushed out later?

**Comment by mthsgrc** [comment]
~_$ kcc
Traceback (most recent call last):
  File "/home/mthsgrc/.local/bin/kcc", line 6, in <module>
    from kindlecomicconverter.startup import start
  File "/home/mthsgrc/.local/lib/python2.7/site-packages/kindlecomicconverter/startup.py", line 24, in <module>
    from .shared import dependencyCheck
  File "/home/mthsgrc/.local/lib/python2.7/site-packages/kindlecomicconverter/shared.py", line 23, in <module>
    from html.parser import HTMLParser
ImportError: No module named html.parser


Any help?

**Comment by AcidWeb** [comment]
This is Python 3 script.

**Comment by mthsgrc** [comment]
> This is Python 3 script.

Thank you! Newbie Linux User here. 
Changing Python version in use did the trick.

**Comment by CrownCrafter** [comment]
I installed everything... but how do i open kcc?
Typing kcc in the shell gives command 'kcc' not found.
I am on Ubuntu 20.04

**Comment by masmiguel** [comment]
> I installed everything... but how do i open kcc?
> Typing kcc in the shell gives command 'kcc' not found.
> I am on Ubuntu 20.04

Try this:
 I get to install kindle comic converter in ubuntu mate 19 and in linux mint 20:

First of all i put this in the terminal:

sudo apt-get install python3 python3-dev python3-pip python3-pyqt5 libpng-dev libjpeg-dev p7zip-full unrar

sudo pip3 install --upgrade pillow python-slugify psutil scandir raven

After, I dowload the kindlegen from:
https://ia801700.us.archive.org/14/items/kindlegen/kindlegen

And i put in:
usr/local/bin

Finally download the master version of kcc ( kcc-master.zip) and decompress.

For execute kcc open a terminal in the kcc-master folder and put: python3 kcc.py

I hope this help you

**Comment by CrownCrafter** [comment]
That worked, but you really need to have some binaries...

**Comment by Lvaskz** [comment]
Can you provide appimages as binaries
See what appimages is:
https://appimage.org/

https://docs.appimage.org/introduction/advantages.html

**Comment by CrownCrafter** [comment]
> Can you provide appimages as binaries See what appimages is: https://appimage.org/
> 
> https://docs.appimage.org/introduction/advantages.html

Sry, it's been a while, I was busy. I would like to provide appimages for kcc.

**Comment by darodi** [comment]
@CrownCrafter 

Could you provide the recipe yml?

**Comment by darodi** [comment]
- will be fixed in #457 on next release
