### ISSUE TITLE
Image filename starts with dot(.) will be ignored

### ISSUE THREAD

**Issue by ShinonomeHana** [ciromattia/kcc#310]
> .01.jpg
> .02.jpg
> .03.jpg
> 0001.jpg
> 0002.jpg
> ...

When  convert zip to ebbok, the image files `.01.jpg` `.02.jpg` `.03.jpg` will be ignored, and epub or mobi file will not contain these images.

Maybe the reason of glob module.

> Note that unlike fnmatch.fnmatch(), glob treats filenames beginning with a dot (.) as special cases.

https://docs.python.org/3/library/glob.html

**Comment by AcidWeb** [comment]
On Windows?

**Comment by ShinonomeHana** [comment]
> 
> 
> On Windows?

Yes

**Comment by AcidWeb** [comment]
It will be fixed in next minor release.

**Comment by ciromattia** [comment]
Are you sure for this?
On Linux and macOS files starting with a dot are hidden files and there are a number of cases where the system creates sort of hidden aliases for existing files.
This change may lead to duplicate pages on *nix systems.
I think that no legit file

**Comment by AcidWeb** [comment]
Yes.
