### ISSUE TITLE
Saturation option

### ISSUE THREAD

**Issue by Wiredframe** [ciromattia/kcc#312]
KCC is really handy and it's awesome for converting CBR comics for the iPad. Many of my comics though are oversaturated so it would be really awesome if there was an option to control saturation.  I'd be really glad if such an option would be added. Thanks 👍

**Comment by AcidWeb** [comment]
Sorry enhancing tablet support is out-of-scope.

**Comment by Wiredframe** [comment]
Sorry, but it's not about an iPad version, it's about an additional saturation slider for controlling saturation (along gamma) when converting a comic. Thanks :)
