### ISSUE TITLE
Is there a detailed tutorial?

### ISSUE THREAD

**Issue by kanhuangats** [ciromattia/kcc#313]
On the code page, it was stated it was self explanatory....it is NOT.

I have a folder with JPGs in it and would like to use KCC command line to convert it into one mobi book.  Not a single example to follow....I'd avoid to read through codes to find what I need to do in order to use it.

Can someone point a direction?

**Comment by AcidWeb** [comment]
GUI is self-explanatory. CLI version is for power users.

Minimal example: `kcc-c2e -u (most of devices need to upscale images) -p <target device profile name> -m (if you convert manga) directory_with_jpg`

**Comment by kanhuangats** [comment]
Gee, that works like a charm....I am hoping you can have a detailed tutorial for power users. For example, those device profile I had to guess KV is short for my Kindle Voyage....
Thanks for your help.
