### ISSUE TITLE
Automatic metadata/filename generation using source folder names?

### ISSUE THREAD

**Issue by JohnEdwa** [ciromattia/kcc#314]
Right now I use the following file structure: `G:/Manga/Berserk/v40/c351/001.jpg`. If I add the parent "Berserk" folder, KCC will produce single volume files with wrong names (`Berserk 1.mobi`, `Berserk 2.mobi`) with the metadata "Author: KCC, Title: Berserk 1", or if I add each individual volume folder, will create `v39.mobi`, `v40.mobi` with "Author: KCC, Title: v40" and so on.

But KCC already knows the folder names, in this case, "Berserk" and "v40", so why doesn't it generate a `Berserk - v40.mobi` file with "Author: Berserk, Title: v40" metadata, or am I missing something here? 

(I know that KCC supports the metadata embedded in .cbz files, but that's only usable if you source them as full volumes or repack them manually as such yourself.)

**Comment by AcidWeb** [comment]
Because that is only one of 324890572349082373 possible cases. Implementing that impractical.

I'm currently thinking about major overhaul how metadata are handled in KCC.

**Comment by JohnEdwa** [comment]
Isn't it [one out of only three possibilities, according to your documentation?](https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting) I do understand that the naming conventions could be different, but the structures would still be these.

Anyhow, here's how I would do this:

With the three folder structures KCC supports and the basic "Author" and "Title" metadata it generates, you can only ever have a maximum of six variables in total: inputs of base folder name "Title", first sub-folder name "Volume", the second sub-folder "Chapter", and the outputs of the "Author" and "Title" metadata, and the generated file name.

These could be split into folder name variables %1, %2 and %3 with text boxes for the metadata generation: "Author: 'Kentaro Miura'", "Title: %1 - %2" and having the output be generated based on the folders like it now is as "%1 - %2.mobi", or also giving the user a possibility to set the filename to include the %author and %title variables generated from the metadata.

For better usability, adding a way to preview the output showing what exact folders will get packaged into what file before converting would help a ton to catch any errors, especially with the "Output Split" setting.

**Comment by AcidWeb** [comment]
I will think about it during overhaul.
