### ISSUE TITLE
Why can't we keep KindleGen OOB?

### ISSUE THREAD

**Issue by KartSriv** [ciromattia/kcc#315]
**Quick Question:** Why do we have to **download** and **place** [_**KindleGen**_](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211) in the _source folder_? **_Can't we just keep it out of the box_**? I think you guys would have _thought_ about this but would have had **_some obstacles doing it._** _I am not aware of any limitations Amazon has given but am always ready to learn._  

_PS: Great fan of your tool. I've read hundreds of comics converted by this tool._

**Comment by AcidWeb** [comment]
KindleGen license don't allow redistribution.
