### ISSUE TITLE
Please add Output destination option to GUI version.

### ISSUE THREAD

**Issue by tallos** [ciromattia/kcc#316]
Currently the GUI version only outputs to the same folder the files are added to convert from. This can make it quite inconvenient when converting many files in separate source folders, as the user needs to go into each individual source folder to collect the KCC converted files for upload to their device.
Please add an option to send all output files from KCC to a user-specified destination folder.

**Comment by AcidWeb** [comment]
Shift+click _Convert_ button.

**Comment by tallos** [comment]
oh, i was looking all over the wiki for that but it wasnt mentioned anywhere

**Comment by AcidWeb** [comment]
SECRET UNLOCKED ;-)
