### ISSUE TITLE
Turn off auto crop white background

### ISSUE THREAD

**Issue by Exia-Ti885** [ciromattia/kcc#317]
hello, can you turn off the auto crop white background? or give a option to turn it on/off?, it messup the page when I convert it to epub, here the original image https://imgur.com/4q50jCB, and after converting https://imgur.com/8k1P4ia, and can I keep the same size images all page after converting into epub file? very sorry for my bad english, thank you in advance, your app its awesome.

**Comment by AcidWeb** [comment]
Only CLI version have options for that.
