### ISSUE TITLE
Fix Mobi files without cover

### ISSUE THREAD

**Issue by wiltonsr** [ciromattia/kcc#318]
Hello everyone,

First, thanks a lot for kcc.

Next, I was reading the [Automatic Cover Upload](https://github.com/ciromattia/kcc/wiki/Automatic-cover-upload) session after see the discussion in #194 even being an old issue and already closed. I "wrote" (just changed the actual behavior) a [small adaption](https://github.com/wiltonsr/kcc/commit/275f9c68e4f8df4dc555ef341d48f6e51d6ce5b5) in comic2ebook.py file, just for testing purposes.

With this, when I run the command line tool:
`$ kcc-c2e -p K34 -f MOBI images-folder`
A folder starting with `KCC-` will be created in `/tmp`. In my casw was `/tmp/KCC-5hqj_gu7` and inside it will be the file `/tmp/KCC-5hqj_gu7/OEBPS/content.mobi`. This file can be transfered for you Kindle using USB method without need of using Calibre or conect your device while the `.mobi` conversion was done.

Unfortunately this doesn't resolve the Kindle email cover problem cited in #227.

**Comment by AcidWeb** [comment]
This don't make any sense. Please elaborate.

**Comment by wiltonsr** [comment]
Hi, thanks for reply. Sorry if I was not clear.  I'm not a native speaker.

The current behavior of the KCC is to create a `.epub` file and use Kindlegen to generate a `.mobi` file. In this scenario, the e-book cover does not work if you copy the `.mobi` file to the Kindle `documents` folder and one of the procedures listed in the Automatic Cover Upload link is required. However, if the`.mobi` file is generated from the `.opf` file this problem does not happen.

**Comment by AcidWeb** [comment]
Yes it "works" because it load wrong low-res cover. This is not a solution for this issue.
