### ISSUE TITLE
macOS 10.15 & 64-bit Compatibility 

### ISSUE THREAD

**Issue by ScherisMarie** [ciromattia/kcc#319]
Unless something radically changes before release, it looks like macOS 10.15 "Catalina" will be removing 32-bit compatibility for applications.

I'm assuming the current macOS application for KCC is 32-bit based, as I've gotten quite a number of "this application will not work in future versions of macOS".

Is there a plan to migrate to a 64-bit based application before the release of macOS 10.15 later this year?

**Comment by AcidWeb** [comment]
Binary is 64bit. There can be tons of other reasons why "this application will not work in future versions of macOS" pops. We will see what future holds.

**Comment by AcidWeb** [comment]
Well KindleGen is 32bit. If Amazon will not release new version for macOS then KCC will no longer support it.

**Comment by AcidWeb** [comment]
As Catalina release is close I'm reopening this issue to not forget about it.

If they will drop 32bit support completely, there will not be any workarounds and Amazon will not release new KindleGen this is the end of macOS support.

**Comment by ScherisMarie** [comment]
https://kdp.amazon.com/en_US/contact-us

After getting passed around a number of different departments, from what I've been told this department is apparently the one in charge of KindleGen development/support.

I sent a contact form email to them regarding the issue, so hopefully I will receive an email indicating things either way in the next day or two.

I will post a follow-up comment once I hear back from them.

**Comment by rowebot78** [comment]
This workaround works :)
https://www.literatureandlatte.com/forum/viewtopic.php?p=284621#p284621

**Comment by ciromattia** [comment]
Apparently it's included both in Kindle Previewer and in Kindle Comic Creator; both installable via `brew cask`.
The latter, though, weights 114MB against the 900MB of the former, so I think that we can instruct the users to install it with
```
$ brew cask install kindle-comic-creator
```
and add it to the PATH
```
# add the following to your ~/.zshrc or ~/.bashrc, depending on which shell do you use
export PATH="/Applications/Kindle Comic Creator/Kindle Comic Creator.app/Contents/MacOS:$PATH"
```

The latest build (5.5.1), though, fails to detect `kindlegen` even if I have it in PATH :/

**Comment by AcidWeb** [comment]
I'm currently rewriting KCC 6.0.0 (ETA unknown) and I'm not planing to make any maintenance release to fix it.

**Comment by ciromattia** [comment]
mmm nope, I got rid of every other version:
```
$ which kindlegen
/Applications/Kindle Comic Creator/Kindle Comic Creator.app/Contents/MacOS/kindlegen
```

I noticed too that if I run KCC from CLI (with `python3 kcc.py`) it correctly gets my profile settings, detecting `kindlegen` and even displaying dark interface; building and launching the binary displays light GUI and does not detect kindlegen, so I think it's python that fails to source the user environment from the app.
If I have some more time I'm going to investigate further.

<img width="612" alt="Screenshot 2019-10-15 15 10 00" src="https://user-images.githubusercontent.com/125366/66834564-264c2700-ef5e-11e9-83d7-ce09eed7481c.png">

**Comment by ciromattia** [comment]
In the meantime, OSX skilled users can workaround by manually copying the *kindlegen* executable from _Kindle Comic Creator_ app into the *Contents/Resources* directory of _Kindle Comic Converter_ app.

**Comment by AcidWeb** [comment]
Theme issue is normal in frozen apps currently.

**Comment by b6332293** [comment]
Thank you, @ciromattia and @rowebot78 ! You made my day.

Here is a step by step guide every beginners like me can follow (for v5.1.1)
(In this explanation, the Browser's download location is the default "Downloads" folder.)
①Get KindlePreviewer.pkg file from [kdp.amazon](https://kdp.amazon.com/en_US/help/topic/G202131170)
②Take kindlegen out of the pkg
`$ pkgutil --expand ~/Downloads/KindlePreviewerInstaller.pkg ~/Downloads/temp`
`$ ditto -x --bom ~/Downloads/temp/KindlePreviewer.pkg/Bom  ~/Downloads/temp/KindlePreviewer.pkg/Payload ~/Downloads/`
③Copy kindlegen from Kindle Previewer 3 to KCC's Resources folder
`$ cp ~/Downloads/Kindle\ Previewer\ 3.app/Contents/MacOS/lib/fc/bin/kindlegen /Applications/Kindle\ Comic\ Converter.app/Contents/Resources`

**Comment by AcidWeb** [comment]
Well work on 6.0 will take way more time I expected.
I will release 5.5.2 soon to fix this issue.
