### ISSUE TITLE
<meta> viewport width is too small for new Kobo Aura H2O firmware

### ISSUE THREAD

**Issue by reinux** [ciromattia/kcc#320]
For this line:

`
<meta name="viewport" content="width=1080, height=1430"/>
`

In the sample document, the width is always 1080, but it's smaller for actual files generated using KCC, correctly matching the actual width of the document.

This seems to cause a problem for the new firmware, which makes it shrink even more, and it creates a margin around the edges.

My workaround right now is to simply take a regex and replace all instances of `content="width=\d+` with `content="width=\d+` .

**Comment by reinux** [comment]
Never mind, it seems to have something to do with Stretch/Upscale, though that's slightly

**Comment by NiLuJe** [comment]
Sidenote: the actual physical viewport on the H2O is 1080x1429 (top 11 pixels behind the bezel).

**Comment by reinux** [comment]
It looks like Calibre may be doing something to the output. Will continue testing stuff and doing diffs etc.

> Sidenote: the actual physical viewport on the H2O is 1080x1429 (top 11 pixels behind the bezel).

Oh really? Maybe it's scaling the image and margining the sides by a pixel or two, or just clipping.

**Comment by reinux** [comment]
I think it's something on Calibre's side.
