### ISSUE TITLE
Major refactoring in progress

### ISSUE THREAD

**Issue by AcidWeb** [ciromattia/kcc#327]
Hello,
I'm currently working on KCC 6.0 - major internal refactoring plus new GUI.

Branch 5.x is considered EOL and bugs reported for it will be most likely ignored.
There are no plans for another 5.5.x release.

No ETA for the 6.0 release.

**Comment by KaMyKaSii** [comment]
@AcidWeb no ETA but i wonder if you're still working on it? Thank you

**Comment by clach04** [comment]
@AcidWeb is the in-progress v6 branch available anywhere? I just saw this and now realize the PRs I posted are after when this was posted so not likely to get reviewed. An update to the readme would be helpful as there are some PRs from this year as well so I'm not the only one who missed this.

I'm happy to look at code that's not ready yet :)

Thanks for making this tool available!

**Comment by axu2** [comment]
V6 has been dropped. https://github.com/ciromattia/kcc/issues/456#issuecomment-1381798395_
