### ISSUE TITLE
Can you upload the dmg's of previous macOS versions?

### ISSUE THREAD

**Issue by oudajosefu** [ciromattia/kcc#330]
I recently updated to the newest version but my mac is not fully updated in its OS, being only on High Sierra. Before I knew it, the app was replaced with the newer version and working version was unretrievable. As there are reasons I haven't updated yet, I would like there to be the option to revert back to an older version of the app so that I can use the GUI again. I am not a fan of the CLI at the moment.

Honestly, only the most stable version for macOS 10.13 is necessary, because who's using an older version than High Sierra, am I right?

**Comment by AcidWeb** [comment]
You can try to open application package and edit `LSMinimumSystemVersion` key in `Info.plist`.

Theoretically it might run correctly on older macOS.

**Comment by felicialiu** [comment]
@oudajosefu @AcidWeb I'm on Sierra (10.12.6) and edited the `LSMinimumSystemVersion`, tried opening the app but it automatically closes itself. Is there any way to get access to dmgs?

**Comment by AcidWeb** [comment]
Supporting macOS is agony.

https://drive.google.com/open?id=1IbUg6VtnUkPObyTaVeeIlqwL9OUa1OLp

@oudajosefu That will not help you as previous version required 10.13+
