### ISSUE TITLE
Having trouble converting .cbr files

### ISSUE THREAD

**Issue by SirGodzilla** [ciromattia/kcc#332]
Hi!

I just downloaded and set up the kcc and I am having a lot of trouble converting my .cbr files. 

It will say "converting EPUB files" then "None" and then "Error during conversion". But I don't find an explanation to the error in the guide of FAQ.

Please help!

Thank you,

**Comment by AcidWeb** [comment]
Unpack it and try to convert the directory maybe you will get error that will have any description.

**Comment by ivmilicevic** [comment]
Hello, I'm having the same problem but unpacking .cbr file and then adding directory to kcc works fine. Is there any more verbose log of what exactly failed, or anything else I can provide to debug this?

**Comment by AlicesReflexion** [comment]
This might be a distro issue! What distro are you using, @SirGodzilla and @ivmilicevic? I'm on Fedora, and Fedora's version of `7z` is compiled without rar support because it's patent-encumbered. I'll make a fork that falls back to trying `unrar` instead, if y'all would want to try that.

**Comment by ivmilicevic** [comment]
@AlicesReflexion It's been a while so I'm not sure in specifics but OS was Kubuntu, version 19.04 or 19.10. I will try to reproduce again

**Comment by ivmilicevic** [comment]
Everything works correctly after installing p7zip-full and p7zip-rar packages on Kubuntu 20.04. 
I haven't tried Your pull request, I don't currently have python environment set up for development
