### ISSUE TITLE
No matching files found when specifying a folder in kcc-c2e.exe 

### ISSUE THREAD

**Issue by CrystalBear45** [ciromattia/kcc#333]
The first thing that happened to me when i typed `kcc-c2e.exe "恄乆偺嶳椾 01姫"`
The output was `No matching files found`
I tried specifing everything but it kept showing me this `No matching files found` even though the folder has 200 jpeg images in it. Do you have any idea on how to fix this?

**Comment by AcidWeb** [comment]
No idea from where you have `kcc-c2e.exe` as we don't distribute that binary.

Try using directory without Chinese characters.
