### ISSUE TITLE
KCC and macOS Catalina

### ISSUE THREAD

**Issue by frmouza** [ciromattia/kcc#334]
Hi everybody,
Since I've upgraded to MacOS 10.15 Catalina, I'm not able any longer to use KCC.
When placing KindleGen, downloaded from Amazon in the same directory (as I used to do) as KCC, it does not seem to recognize the library.
I thought it was related to the fact that library was not a 64 bit version. But I succeeded in downloaded the 64bit version and the issue remains the same.
If you have any idea how to solve this issue, I'm really interested.

**Comment by AcidWeb** [comment]
KindleGen on macOS was never checking directory of .app for KindleGen.

Binary need to be in one of these directories: `./../Resources:/Applications/Kindle Comic Creator/Kindle Comic Creator.app/Contents/MacOS:/usr/local/bin:/usr/bin:/bin`
Make sure that KindleGen binary you downloaded manually have execution permissions.
