### ISSUE TITLE
/tmp is not cleaned after conversion

### ISSUE THREAD

**Issue by lapwat** [ciromattia/kcc#335]
Is it possible to stop using /tmp or at least clean it after you have performed the conversion?

**Comment by lapwat** [comment]
Certainly related to this issue: https://github.com/ciromattia/kcc/issues/256

**Comment by AcidWeb** [comment]
`tmp` should be cleaned after any error or completed conversion. Additionally it is cleaned before any conversion.

If files are not gone something is actively blocking the removal.

**Comment by lapwat** [comment]
I have found that this is happening when converting to mobi only. I guess that `kindlegen` is not clearing its cache properly.
