### ISSUE TITLE
Kindlegen not clearing /tmp when called through KCC

### ISSUE THREAD

**Issue by lapwat** [ciromattia/kcc#336]
I have made an investigation about why the `/tmp` is not cleared when converting to MOBI.

![2019-12-21-224704_1920x1080_scrot](https://user-images.githubusercontent.com/7073651/71314688-0432c180-2445-11ea-8a3e-2338beff0f0b.png)

First line top right is the original /tmp usage.

Second line is the same after performing an EPUB conversion: **cache usage did not change**.

The last line is the same after performing a MOBI conversion: **cache usage increased**, kindlegen could not clear its cache. Was it or its job killed to early? Did several kindlegen commands were thrown at the same time?

Can you reproduce?

This issue may be related to one of those `makeMOBI` functions here https://github.com/ciromattia/kcc/blob/259800e48b8622233d0a415d7a025f087de7e3cd/kindlecomicconverter/comic2ebook.py

PS: Tried to run `kindlegen file.epub` in my terminal and the cache was successfully cleared.

**Comment by AcidWeb** [comment]
I will check it during refactor.

**Comment by whtsky** [comment]
Reproduced on my server. 

Installed `kindlecomicconverter==5.5.2` using pip, and calling it using
```python
subprocess.run(
    'kcc-c2e -m -f MOBI -o "{output_path}" "{folder}"'.format(
        output_path=output_path, folder=str(folder)
    ),
    shell=True,
    check=True,
)
```

in a long-running Python script run as root.

**Comment by lapwat** [comment]
https://github.com/jisaacks/GitGutter/issues/284#issuecomment-257291258

May be related to this issue, it happens when working with temporary files. Sometimes the temporary files are not deleted because they do not exist already.

**Comment by as3ii** [comment]
I've found that kcc don't delete either his own temporary file (jpeg) or the kindlegen-related ones

**Comment by darodi** [comment]
@as3ii @lapwat 

is this bug still present after https://github.com/ciromattia/kcc/pull/459 ?
waiting feedback in version v5.6.1

**Comment by as3ii** [comment]
tested the v5.6.1 appimage: temporary files are deleted successfully

**Comment by darodi** [comment]
@as3ii 
Thanks,
closing this
