### ISSUE TITLE
Issue: can't install kcc on (MX) Linux through pip even with the proper dependencies

### ISSUE THREAD

**Issue by Apollucas** [ciromattia/kcc#340]
So I just wanna quickly preface by saying I'm still pretty new to Linux, so the solution might be easier than I thought.

I want to install the PyPI version of KCC, but even when installing the right dependencies, I get this chunk of code:

`$ pip install --user KindleComicConverter
Collecting KindleComicConverter
  Using cached https://files.pythonhosted.org/packages/c9/6e/4f505433628dbe45b38227ae8b388bf14cf1344824b938663ecaf97a8b97/KindleComicConverter-5.5.2.tar.gz
Collecting PyQt5>=5.6.0 (from KindleComicConverter)
  Could not find a version that satisfies the requirement PyQt5>=5.6.0 (from KindleComicConverter) (from versions: )
No matching distribution found for PyQt5>=5.6.0 (from KindleComicConverter)`

And also, I noticed a problem when installing the second line of dependencies through pip:

`$ pip3 install --user --upgrade pillow python-slugify psutil pyqt5 raven
Collecting pillow
  Using cached https://files.pythonhosted.org/packages/f5/79/b2d5695d1a931474fa68b68ec93bdf08ba9acbc4d6b3b628eb6aac81d11c/Pillow-7.0.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting python-slugify
  Using cached https://files.pythonhosted.org/packages/92/5f/7b84a0bba8a0fdd50c046f8b57dcf179dc16237ad33446079b7c484de04c/python-slugify-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nm8qdu4w/python-slugify/`

Any idea what I should do to get this working?

**Comment by alannssantos** [comment]
`sudo apt install python3 python3-dev python3-pip libpng-dev libjpeg-dev p7zip-full`
`sudo -H pip3 install PyQt5==5.14.0`
`sudo -H pip3 install KindleComicConverter`

The last version of PyQt5 dont install on debian based.

**Comment by PedePanoOriginal** [comment]
> `sudo apt install python3 python3-dev python3-pip libpng-dev libjpeg-dev p7zip-full`
> `sudo -H pip3 install PyQt5==5.14.0`
> `sudo -H pip3 install KindleComicConverter`
> 
> The last version of PyQt5 dont install on debian based.

After running this commands u said I keep getting the same results.


Collecting KindleComicConverter
  Using cached https://files.pythonhosted.org/packages/c9/6e/4f505433628dbe45b38227ae8b388bf14cf1344824b938663ecaf97a8b97/KindleComicConverter-5.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vhht859s/KindleComicConverter/

**Comment by darodi** [comment]
@Apollucas @alannssantos @PedePanoOriginal 

is the problem still present with the last version?
some dependencies have been fixed and there is a new testPyPi
https://github.com/ciromattia/kcc/blob/master/README.md#pypi

**Comment by darodi** [comment]
flatpak is now the recommended version for linux

https://flathub.org/apps/details/io.github.ciromattia.kcc
reopen issue if needed
