### ISSUE TITLE
How do I keep the content ratio so it doesn't stretch no matter what in KCC?

### ISSUE THREAD

**Issue by kvassmacncheese** [ciromattia/kcc#346]
I'm very frustrated that no matter how I tried, all the content images will be stretched so it fits the screen... I mean I would like to have a margin rather than having the image stretched to a certain point of ugly...
   The stretch/upscale option doesn't work because the jpg I am converting seems to be a little bit sharper than my kindle paperwhite 3's resolution... and I just want to keep the aspect ratio(the margin will be small to notice), not having the image being stretched vertically or horizontally... pls help

**Comment by ursbraem** [comment]
Thanks! Not sure if I get this right: will KCC _automatically_ stretch images to the device (unless custom dimensions are applied)? Can this be the intention?

**Comment by ursbraem** [comment]
Oh wait sorry 😬 

![Screenshot-29 08-001814](https://user-images.githubusercontent.com/1446443/187296476-fa201d71-84fb-4a77-9184-6995ae87b7cc.jpg)

**Comment by darodi** [comment]
might be fixed in the last release in 
https://github.com/ciromattia/kcc/pull/457/commits/2c198989528fc536b811b4da47a9cf17913cb9c1

Is the problem still present?
If so, could you give some information?
what reader device, input file and settings used?
