### ISSUE TITLE
CBZ to MOBI conversion consistently failing

### ISSUE THREAD

**Issue by DilsDoes** [ciromattia/kcc#348]
On Windows 10, kindlegen and 7z are both in directory, every time I try to convert CBZ files, whether in a batch or individually to MOBI I get a message stating EPUB files are being created, and then an alert stating the source directory is empty and a message which reads "Error during conversion! Check the wiki for more details." The wiki states that this error is due to the selected directory not containing image files and that it does not work for CBR files or the like, however I am not using the directory feature, I am using the Files feature. I mistakenly attempted to open a file with the directory, but reinstalled the program completely. I extracted the files in the CBZ folder to ensure that there was not an error, they are all jpg files.
EDIT: I should add that extracting the archive and attempting to extract the directory returns the same error.

**Comment by guillim** [comment]
any way to solve this ?
