### ISSUE TITLE
Manga mode not working

### ISSUE THREAD

**Issue by GianluC03** [ciromattia/kcc#351]
Basically the manga mode doesn't able the right-to-left reading, and when I transfer the file to my kobo clara hd it's like a normal book, from left to right. i also tried not utilizing calibre, because i read that it can corrupt the file sometimes. Maybe I'm missing something?

**Comment by Zanther** [comment]
Works for me on Kindle and Kindle for iPad. Also in Books as well.

**Comment by l-l-l-l-l-l** [comment]
AFAIK what manga mode does (at least for me) is just change the order in which halves of split pages are saved. IDK if there's a way to have the page flip buttons on a western device to work in reverse (and even if there was, most likely it wouldn't work with every device).

**Comment by KYG-yaya573142** [comment]
I think the right-to-left of works on kindle not kobo, since the metadata `<meta name="primary-writing-mode" content="horizontal-rl"/>`  is a Kindle-specific metadata. I don't know if there's another way to achieve the same behavior on kepub though.

**Comment by darodi** [comment]
May be linked to https://github.com/ciromattia/kcc/pull/328
Could someone check with a kobo? I don't own one.

you Kobo model can be added here

https://github.com/ciromattia/kcc/blob/b71d056559651b94eae7eb97397affe0493b6edf/kindlecomicconverter/comic2ebook.py#L1045-L1046

**Comment by axu2** [comment]
@nodscrim

Maybe this thread will help? https://www.mobileread.com/forums/showthread.php?t=339910

Or use EPUB/KEPUB instead. Or use koreader.
