### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by TLN2306** [ciromattia/kcc#352]
I'm trying to edit out the unwanted pages from a manga by extract the cbz file out and delete the trash ones out. On top of that, I also edit the comicinfo.xml file to add bookmarks for chapters and such. 

It's been working so far for the first few chapter but one keeps popping out "index out of range" issue. I tried again and again with the conversion process, thinking the issue might have been there but nothing happened.

**Comment by darodi** [comment]
we can't guess without the folders structure/content.
reopen with all needed info if the problem is still there
