### ISSUE TITLE
The cover disappears after 2 sec

### ISSUE THREAD

**Issue by Picasbas** [ciromattia/kcc#357]
when I convert a file in the eReader the cover appears and disappears right after, whereas I had never had this problem before.

**Comment by Roadcrosser** [comment]
Kindles recently started doing some kind of DRM thing, [this](https://www.reddit.com/r/kindle/comments/glvmtk/fix_for_problem_of_cover_art_disappearing/) may help you.

**Comment by Picasbas** [comment]
Thanks a lot, the first method does not work but the second yes (the thumbnail method)
