### ISSUE TITLE
KCC not achieving to convert cbr archives.

### ISSUE THREAD

**Issue by jthulhu** [ciromattia/kcc#358]
Whenever I try to convert some cbr archives to any format,
I get `Error during conversion! Please consult wiki for more details.`, no other precisions.
I've tried to do it command-line

> $ kcc-c2e -p mykindle MyComic.cbr
> comic2ebook v5.5.2 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.
> Preparing source images...
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/kindlecomicconverter/comic2ebook.py", line 600, in getWorkFolder
>     path = cbx.extract(workdir)
>   File "/usr/local/lib/python3.5/dist-packages/kindlecomicconverter/comicarchive.py", line 53, in extract
>     raise OSError('Failed to extract archive.')
> OSError: Failed to extract archive.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/kcc-c2e", line 8, in <module>
>     sys.exit(startC2E())
>   File "/usr/local/lib/python3.5/dist-packages/kindlecomicconverter/startup.py", line 49, in startC2E
>     sys.exit(main(sys.argv[1:]))
>   File "/usr/local/lib/python3.5/dist-packages/kindlecomicconverter/comic2ebook.py", line 74, in main
>     makeBook(source)
>   File "/usr/local/lib/python3.5/dist-packages/kindlecomicconverter/comic2ebook.py", line 1076, in makeBook
>     path = getWorkFolder(source)
>   File "/usr/local/lib/python3.5/dist-packages/kindlecomicconverter/comic2ebook.py", line 603, in getWorkFolder
>     raise UserWarning(e.strerror)
> UserWarning: None
> $

I've noticed other conversion tools stuck at these archives too.
I've tried different comics, they all stuck.
I tried to do it by hand eg. write a 10 lines bash script, it works quite well.
So, my guess, trying to debug few of the conversion tools I've tried is that they all take for given that the images in the cbr archive are at the top level, which is not the case for mine, which are in
`Name of my archive_nodrmi7/mobi7/Images/`.
In any case I could try to move all the images at top level, but I still think it should be an automatic behaviour of any conversion tool, because many reading tools achieve to read these comics, and so I'd classify this as a bug even if it could be considered a feature request.

If you need the archives, tell me, I'll find a way to give them to you, because by default github doesn't support rar archives.

**Comment by darodi** [comment]
@jthulhu 

more information is welcome
input file example, settings used for conversion

Is the problem present too when you unrar that cbr file and work with directories instead?

**Comment by darodi** [comment]
@jthulhu 
OK thanks, I'm closing the issue then.
reopen if needed

**Comment by aliafshany** [comment]
> @darodi so I guess unrar and directory stuff Just Worked.

@darodi 
i have had the same issue and then noticed the quote from @darodi.
yes, it works!
it seems KCC has problem with unzipping CBZ files in my case.
I'm using macOS Ventura 13.3.1 and the Manga name is : Mashle - Magic and Muscles 02.cbz

<img width="612" alt="image" src="https://user-images.githubusercontent.com/40741745/233829587-e9a98733-7b05-4301-8672-bc2ec353f881.png">
