### ISSUE TITLE
Support true full-screen on Kobo devices

### ISSUE THREAD

**Issue by flying-sausages** [ciromattia/kcc#360]
Kobo has their own extended KePub format, which allows comics and manga to show without any of the footers and headers, as well as stretched fully to the size of the sdges of the screen. Below is an example preview file downloaded from the kobo store.

[26496db7-e3b1-4c17-96ce-2724622f6c87.zip](https://github.com/ciromattia/kcc/files/4747845/26496db7-e3b1-4c17-96ce-2724622f6c87.zip)

Here is a comparions of KCC output and a Kepub from the store 
![image](https://user-images.githubusercontent.com/23618693/84067082-cb6cb180-a9be-11ea-984b-1f393a09d87a.png)
![image](https://user-images.githubusercontent.com/23618693/84067114-d7f10a00-a9be-11ea-8d2b-800ef8b2761b.png)

**Comment by darodi** [comment]
@flying-sausages 

Is the problem still present with the last version (v5.6.1) with options to control cropping?
