### ISSUE TITLE
List Index Out Of Range

### ISSUE THREAD

**Issue by crevopunch** [ciromattia/kcc#368]
Hi,

i was trying to convert some cbz/cbr files to mobi files (it's comics) but i got an unexpected issue. 

![image](https://user-images.githubusercontent.com/68196309/87251638-6567c400-c46d-11ea-8524-441ee7cb3864.png)

If someone can help me it will be a pleasure.

Thanks

**Comment by darodi** [comment]
@crevopunch 

Is your question still open?
What input are you using?
