### ISSUE TITLE
KindleGen detection on linux

### ISSUE THREAD

**Issue by JHerseth** [ciromattia/kcc#369]
https://github.com/ciromattia/kcc/blob/515b83637fd0e531b1b21cac39a7fa42ed0a3f27/kindlecomicconverter/KCC_gui.py#L839

KindleGen is not detected correctly on linux (Manjaro) with kindlegen in KCC root folder.
Changing this line to 
`kindleGenExitCode = Popen('./kindlegen -locale en', stdout=PIPE, stderr=STDOUT, stdin=PIPE, shell=True)`
fixes the issue.

**Comment by aspieln3r** [comment]
same issue on archlinx when using flatpak package. open a pull request?

**Comment by Y0seph** [comment]
I don't even know if I have the right file for KindleGen, nor if it is in the right place. I'm still a noob, anyone able to help?

**Comment by ReViDiSwO** [comment]
> I don't even know if I have the right file for KindleGen, nor if it is in the right place. I'm still a noob, anyone able to help?

same here, could someone help us ?

**Comment by darodi** [comment]
same problem even if kindlegen is in your path?

**Comment by darodi** [comment]
adding to your path should fix it. 
reopen if needed
