### ISSUE TITLE
Kindlegen no longer available for download

### ISSUE THREAD

**Issue by jasonriv** [ciromattia/kcc#371]
![chrome_4031T0sKeU](https://user-images.githubusercontent.com/13947154/91375685-bd764200-e7f1-11ea-9f1f-d7733aeaa80c.png)

It looks like kindlegen is no longer available for download and is replaced with Kindle Previewer. I don't see anything about this on the wiki or recent issues so I'm guessing this change from them is recent - what should I do instead?

**Comment by Jrockzdev** [comment]
I just used the wayback machine to pull the file from here: https://web.archive.org/web/20190817070956/https://www.amazon.com/gp/feature.html?docId=1000765211

[kindlegen_win32_v2_9.zip](https://github.com/ciromattia/kcc/files/5133667/kindlegen_win32_v2_9.zip)


This is v2.9 of kindlegen, you need to take the kindlegen.exe from inside and use that. Hope this helps

**Comment by Nomeji** [comment]
The file wasn't even on web archive for Linux. If anyone is looking for it, I've got it from an old hard drive.
I've uploaded it here : https://archive.org/details/kindlegen

**Comment by WesleyMPG** [comment]
I created a docker image setted up for kcc. Actually I don't know for sure how to run gui applications in a docker container. So basically I use the kcc CLI  (kindlegen already on the image). If some one got iterested here is the image: https://hub.docker.com/r/wesleympg/kindle-comic-converter-cli

Creating a container and attaching:
```
$ docker run -ti --name kcc-cli -v <pathToYourComicsDir>:/comics wesleympg/kindle-comic-converter-cli /bin/bash
```
The you need to enter in the comics dir and convert:
```
$ cd comics
$ kcc-c2e (or kcc-cli) <options> * 
```
\* means all the files and directories in the current directorie. You might just convert one file as well. See the CLI usage and be happy :D

**Comment by ulfgj** [comment]
i'm gonna just use calibre...

**Comment by Grauen** [comment]
Kindle Previewer also allows mass convertion

`USAGE:
kindlepreviewer <input> <-command(s)> [-option(s)]
kindlepreviewer -update

input
        Specify the input file name here when processing a single file, or the
        input folder when processing multiple files.

-command(s)
        Include at least one of the commands specified below.

-option(s)
        Choose any of options specified below (optional).

-update
        Download and install the latest software update for Kindle Previewer.

COMMANDS:
-convert
        Create a KPF file in the specified output path, or a Mobi file when the
        book does not support Enhanced Typesetting. Use the Enhanced Typesetting
        compatible KPF file to open the book on Kindle Previewer's graphical
        user interface without reconverting it.

-showpreview
        Open the converted book in Kindle Previewer's graphical user interface.
        This will first convert the book, and then open it for preview.

-log
        Use this option to generate only the log files for validation without
        generating a KPF or a Mobi file.

-qualitychecks
        Use this option (beta) to validate external links, internal links, and
        footnotes in your books.

OPTIONS:
-output <output path>
        Path to the output folder. Use this option to specify a preferred path
        to store output file(s) instead of the default path (input folder).

-locale <locale-option>
        Specify your preferred locale. Use this option to set the language for
        conversion log messages and the Kindle Previewer user interface.
        Supported locales are en : English, de : German, fr : French,
        it : Italian, es : Spanish, zh : Chinese, ja : Japanese,
        pt : Portuguese, nl : Dutch.

EXAMPLES:
kindlepreviewer inputfile.epub -convert
kindlepreviewer inputfolder/  -convert -output outputfolder/
kindlepreviewer inputfile.epub -showpreview
kindlepreviewer inputfolder/ -log`

So it should be possible to add support of kindle previewer to kcc :)

**Comment by Nomeji** [comment]
What about manga/comics mode? Does the tool support it?

-------- Original Message --------

**Comment by Grauen** [comment]
@Nomeji ,
What exactly does "manga mode" mean? 

I converted my input file to epub using kcc. 
After that I converted the epub using Kindle Previewer.  I just converted it via cli without any further configuration:

`
 kindlepreviewer . -convert  -output .
`
The result looks splendid on my kindle. Also you have to swipe from left to right, like you would read a real manga. Quality looks great and loading times are quite fast. So this is exactly what I need.

But no, you cannot pass any "manga" or "comic" parameter with kindle preview. However - I'm satisfied with the result and supporting Kindle Preview would be better than relying on deprecated software and archive.org as primary download source .

**Comment by Nomeji** [comment]
For my Kindle model, manga/comics mode remove margins (usually used to diplay page count). This is the most usefull since the screen is very small. Even removing the slightest margin can improve image size a lot since it scale better. It's clearly a must have.

The other "not very usefull" feature is that it allow to zoom on different sections of the page. kcc allow to configure 4 zoom split or 2 zoom split options.

-------- Original Message --------

**Comment by Grauen** [comment]
@Nomeji my output files look perfectly cropped. When I doubletab the screen, it switches to 'split zoom'. Why don't you just give it a try yourself? 

Kindlegen is gone. You should definitely consider  supporting Kindle Previewer.

**Comment by HermesPasser** [comment]
> I just used the wayback machine to pull the file from here: https://web.archive.org/web/20190817070956/https://www.amazon.com/gp/feature.html?docId=1000765211
> 
> [kindlegen_win32_v2_9.zip](https://github.com/ciromattia/kcc/files/5133667/kindlegen_win32_v2_9.zip)
> 
> This is v2.9 of kindlegen, you need to take the kindlegen.exe from inside and use that. Hope this helps

It can be found in "_Amazon Kindle Previewer 3 Folder\lib\fc\bin_" too but using the Wayback Machine is the fastest way to get it since no installation is needed.

**Comment by silentguy256** [comment]
After seeing that people said it's installed with Amazon Kindle Previewer and I noticed you don't even have to install it. I just opened KindlePreviewerInstaller.exe with 7-zip and extracted it from KindlePreviewerInstaller.exe\lib\fc\bin\

**Comment by nosovk** [comment]
[kindlegen.exe for windows version from 11/18/2021](https://ipfs.infura.io/ipfs/QmdnHah5NroTaiaDMf3ztTPyEDQEdoWimPREPrR8rdjQnq?filename=kindlegen.exe)

**Comment by darodi** [comment]
closing this
many answers have been given and the [README](https://github.com/ciromattia/kcc#readme) has been adapted.
I will create another issue to manage kindle previewer
