### ISSUE TITLE
Some pages are inverted in color

### ISSUE THREAD

**Issue by jameiame** [ciromattia/kcc#375]
Has anyone ever had this issue? I get some pages inverted in color randomly (90% of the pages arent, 10% are and are scattered throughout the volume. )How to fix?

**Comment by darodi** [comment]
please give an input image with that problem

**Comment by axu2** [comment]
I bet you are in dark mode on your kindle, which is funky with manga.

**Comment by darodi** [comment]
closing this
reopen if needed
