### ISSUE TITLE
How to install in ubuntu mate & linux mint 20

### ISSUE THREAD

**Issue by masmiguel** [ciromattia/kcc#377]
The only purpose of this post is to share how I get to install kindle comic converter in ubuntu mate 19 and in linux mint 20:
First of all i put this in the terminal:

sudo apt-get install python3 python3-dev python3-pip python3-pyqt5 libpng-dev libjpeg-dev p7zip-full unrar

sudo pip3 install --upgrade pillow python-slugify psutil scandir raven

After, I dowload the kindlegen from:
https://ia801700.us.archive.org/14/items/kindlegen/kindlegen

And i put in: 
usr/local/bin

Finally download the master version of kcc ( kcc-master.zip) and decompress.

For execute kcc open a terminal in the kcc-master folder and put: python3 kcc.py

I hope this help for the linux users.

**Comment by inwonakng** [comment]
Just to update, I was able to get it working by installing the python package, and then running `which kcc` and placing the file linked above in that directory

**Comment by darodi** [comment]
thanks.
the readme has been updated 

https://github.com/ciromattia/kcc#readme
