### ISSUE TITLE
Kindle thinks each Chapter is a Book, not a Comic - Spamming the books list

### ISSUE THREAD

**Issue by Harmonised7** [ciromattia/kcc#378]
Options used to convert:
Stretch/Upscale
Output split

Device:
Kindle Paperwhite

Issue:
Each Mobi file was been counted as a Book, instead of Comic, forcing me to either group almost 400 chapters one by one, or search for each book that's not the comic throughout ~80 pages

**Comment by Laumser7** [comment]
Your folder structure was incorrect/incompatible with the "split output" setting - please refrain from using the split setting in cases where the comic/manga folder structure is organized with chapter folders.
Convert your content volume by volume without the output split setting enabled.

**Comment by darodi** [comment]
see
https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting
