### ISSUE TITLE
Kobo Aura H20 - eReader not Authorized to open this book

### ISSUE THREAD

**Issue by BMRX** [ciromattia/kcc#379]
"This book is protected by Adobe Digital Rights Management..."

I'm not sure how a zip file full of only images is protected by DRM after running through KCC but here we are.

I've looked over the Wiki and here for this issue and it seems like it hasn't shown up yet. Any help is greatly appreciated thank you.

**Comment by darodi** [comment]
@BMRX 

Is this issue still ongoing? 
What is the content of your zip file?
Have you tried using the unzipped directory as input instead? With the same result?
