### ISSUE TITLE
Adding a way to make "volumes" from chapters

### ISSUE THREAD

**Issue by Xqua** [ciromattia/kcc#380]
Here's the reasoning, I can get Chapters off MangaDex (or else). But chapters are very annoying on an ereader because of the time needed to read the next one. 
So I've been using Calibre to do -> CBZ -> EPUB -> EPUB Merge into Volumes -> PDF 
Then take the PDF and finally run it through KCC to get a MOBI file. 

It would be reallllllyy nice if we could get a small UI or one more level to the file list to group chapters into volumes.

**Comment by Laumser7** [comment]
This workaround is redundant and not needed - pulling all chapter files into a single folder and dropping that folder into KCC with the split output option disabled will result in a merging of all chapters into a single file.

**Comment by Xqua** [comment]
Ohh I did not know this, it might be worth it to write it in the documentation or the GitHubreadme ?

**Comment by TatianaC** [comment]
I actually am unable to add zip files (or folders) to KCC. I receive an error saying that the source directory is empty. Are there any workarounds for this error? Thanks!

**Comment by darodi** [comment]
TatianaC's comment has been solved in another issue.

@Xqua 
ghost's proposition is correct.
The simplest way is to use a directory with sub directories inside for each chapter

everything is already there:
https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting
