### ISSUE TITLE
CBZ to MOBI conversion "unsupported directory structure" error

### ISSUE THREAD

**Issue by LarsOlt** [ciromattia/kcc#384]
![image](https://user-images.githubusercontent.com/32353679/107862319-535b6300-6e4c-11eb-90a1-cf76099373ba.png)

Tried with and without manga mode but both give the error "unsupported directory structure". I tested this with multiple files.

**Comment by FulyaDemirkan** [comment]
Have you checked the folders? If there is a nested folder then KCC gives this error. For example, you cannot have a folder for a volume and subfolders inside of it for each chapter.

**Comment by darodi** [comment]
@LarsOlt 

Is this issue still open?
cbz file is just a zip file, unzip it and convert the directory instead, with images in the parent directory, it should work.

**Comment by LarsOlt** [comment]
Sry for the late reply

> Have you checked the folders? If there is a nested folder then KCC gives this error. For example, you cannot have a folder for a volume and subfolders inside of it for each chapter.

Sorry for the late reply. This was the problem. You can close it. @darodi
