### ISSUE TITLE
Error - But can't find reason

### ISSUE THREAD

**Issue by mthsgrc** [ciromattia/kcc#389]
I used to convert my mangas to use in Kindle before, now I'm trying to convert some Tex comics, but I got an error.
Problem is I don't see any error messages to give me more info about what's is happening.

I'm on PopOs, installed it through Pip. KindleGen is there. 

![Screenshot from 2021-02-23 16-03-46](https://user-images.githubusercontent.com/13367706/108894583-39124980-75f1-11eb-82f1-dff344be39e8.png)

**Comment by Laumser7** [comment]
Please provide further information about your source files - KCC will panic with certain configuration files being present in the CBZ/CBR in addition to the image files - should this be the case please open the archive and clear out everything that isn't an image file.

**Comment by mthsgrc** [comment]
Hello, 
I've partially solved the case by extracting the files into a folder and then using it.
The CBR file itself has a folder and then the images. Maybe that's the problem. 

Haven't tested it yet with a CBR with only image files.

**Comment by Laumser7** [comment]
Sometimes images also exceed the normal specification of color values - even when grayscale - this can be fixed with microsoft powertoy's resize feature, which will push the images back into spec.

**Comment by darodi** [comment]
> Hello, I've partially solved the case by extracting the files into a folder and then using it. The CBR file itself has a folder and then the images. Maybe that's the problem.
> 
> Haven't tested it yet with a CBR with only image files.

issue closed.
If needed, reopen a new one with more information about your input file.
