### ISSUE TITLE
Pocketbook Inpad 3 Pro Comic Setting ?

### ISSUE THREAD

**Issue by Rider71-del** [ciromattia/kcc#390]
I would like to ask what is the optimal setting for the Pocketbook Inpad 3 Pro for reading comics and manga?

**Comment by Laumser7** [comment]
Select Profile "other" - input following settings:
Custom Gamma: 0.8
Resolution: 1404 x 1872

Checkmark next to "Stretch/Upscale"
No Checkmark next to "Color mode"

Adjust other settings per your preference.

**Comment by darodi** [comment]
@Rider71-del 

can this be closed?
