### ISSUE TITLE
Add Page Fill Option

### ISSUE THREAD

**Issue by axu2** [ciromattia/kcc#391]
Hey! Longtime mangle user, recent discover of kcc.

Would love a feature like filling screen by cropping when source files are only slightly skinnier.

I implemented it myself for mangle.

https://github.com/FooSoft/mangle/pull/33

It would also be cool to be able to specify where to crop from, though the default is good enough for most cases.

In hindsight, should have called it `fill` not `scaleCrop`

**Comment by darodi** [comment]
Cropping mode has been added in version v5.6.1 is this enough?
If not, please describe what you would like.

**Comment by axu2** [comment]
![image](https://user-images.githubusercontent.com/20757319/214487124-eca11e1b-f5ca-41db-ad5f-18b39b64da9d.png)

Just cropping margins or page numbers is not what I want.

I want to crop the image from the top/bottom or left/right so the remaining image fills the screen.

Here is one example from the PR in my original post:

![image](https://user-images.githubusercontent.com/20757319/214488304-fb59a79e-daec-4101-8325-8bb2efb832aa.png)


In my PR, I replaced the stretch feature with a crop, since I can't imagine anyone wanting to change the aspect ratio.

![image](https://user-images.githubusercontent.com/20757319/214487861-ec1d58fc-a4dc-40fe-bfda-9bf1da943b7a.png)

**Comment by axu2** [comment]
I made a barebones implementation in #471

**Comment by darodi** [comment]
Good idea!

We should maybe rethink the GUI a bit.
There are a lot of checkboxes for everything.
Maybe a simple mode and an advanced mode?

**Comment by axu2** [comment]
Will close this since I already have a pending PR in #495
