### ISSUE TITLE
How to enable landscape mode when reading manga on kindle?

### ISSUE THREAD

**Issue by Kolakona** [ciromattia/kcc#392]
As per title. I am converting the jpeg files to mobi using KCC but I am unable to rotate it to landscape mode. 
when use old version like v2.7 ,it works.But in v5.5.2,the converted mobi file can't be read in landscape mode.
Thanks!

**Comment by darodi** [comment]
> the converted mobi file can't be read in landscape mode

What is expected and what is the current behaviour?

**Comment by axu2** [comment]
Epubs from humble bundle have landscape orientation when using Send To Kindle. So it means I can read two pages side by side in landscape mode. There's probably something in the epub metadata that enables this. I don't have epub experience myself.

**Comment by darodi** [comment]
- fixed with #567
