### ISSUE TITLE
kcc-c2e command not found

### ISSUE THREAD

**Issue by lucas-marx** [ciromattia/kcc#398]
I've been using kcc for a loong time on linux mint, recently I've reinstalled and now I'm on mint 20.1 and today I installed everything following the readme.md file but when I run kcc-c2e -p KPW -f MOBI -b 0 -u -r 1 -c 1 "Jujutsu Kaisen" (for example) i get that the command wasn't found. Any ideas of what is wrong? 
Thanks!

**Comment by darodi** [comment]
new version v5.6.1
Do you still have that problem?

**Comment by darodi** [comment]
see 
- https://github.com/ciromattia/kcc/issues/492#issuecomment-1485948428
