### ISSUE TITLE
KCC doesn't open

### ISSUE THREAD

**Issue by Duhhmas** [ciromattia/kcc#399]
I'm not sure what else to say about this, but the application just doesn't open (I'm using the application version, no idea how to even run the python version). I've tried running as administrator, nothing. I don't know if kindlegen has something to do with it, but I've tried with and without it. I think it happened first around when kindlegen stopped being provided, or working, whatever happened. I just deleted it and came back after 6+ months. Anyone know what's going on?

**Comment by darodi** [comment]
@Duhhmas 

What version are you using? on which platform? 
Have you tried running the app from a command line?

**Comment by axu2** [comment]
Check #544

**Comment by darodi** [comment]
closing this. old stuff.
reopen if needed and provide more information this time.

**Comment by Duhhmas** [comment]
> closing this. old stuff. reopen if needed and provide more information this time.

Really? You show up 2 YEARS after I posted this and told me to post more info? Are you serious?

**Comment by axu2** [comment]
Sorry, development has only recently restarted, so a lot of older issues were buried in the pile.  I'm also just a guy who only recently started submitting PRs and just trying to help. 

Let me know if you still have issues with the latest version.
