### ISSUE TITLE
cover is not the first page 

### ISSUE THREAD

**Issue by unicorn0225** [ciromattia/kcc#400]
my .cbz file contain the cover,and this is not the first page,how can I set the cover just cover,not the page1,because it will broke the manga to a strange design,and I use iBook.
in the .cbz file: cover.jpeg,page0001.jepg,page0002.jepg...

**Comment by KaMyKaSii** [comment]
Try to extract the cbz, rename cover.jpeg to page0000.jpeg and then select this folder on KCC

**Comment by darodi** [comment]
reopen if needed
