### ISSUE TITLE
ERROR: KindleGen is missing!

### ISSUE THREAD

**Issue by lucas-marx** [ciromattia/kcc#402]
It's not working anymore? I've installed on ubuntu using pip and then tried using it but i get the error "ERROR: KindleGen is missing!"
I've downloaded the kindlegen 2.9 and put it on the kindlecomicconverter folder but still doesn't work

**Comment by JHBoricua** [comment]
See this for a solution: https://github.com/asciidoctor/asciidoctor-epub3/issues/363#issuecomment-684794354

I did this on my Windows 10 system (I opted to add the directory where Kindle Previewer drops the kindlegen binary to my system PATH) and KCC works fine for me.

**Comment by fisik-yum** [comment]
@lucas-marx Make sure your kindlegen binary is in `/usr/local/bin/` . If that doesn't work, try downloading the linux version at https://kcc.iosphe.re/Linux (.deb, works for ubuntu) instead of using pip.

**Comment by bran112299** [comment]
I can confirm that with kindegen.exe in the KCC folder as well as 7z.exe that my GUI is unable to find both of them. Even adding them both in PATH didnt work. I'm on Windows 11

**Comment by darodi** [comment]
@bran112299 @lucas-marx 

is your problem still present?
Is there an output when you run KCC in command line?
Where is you KCC located? Where is your kindlegen located? (windows path)

**Comment by cobblepot1** [comment]
Hi, I am having a similar problem on Win 10. KCC and kindlegen.exe are both in `C:\Program Files\Kindle Comic Converter`. I don't know how to run KCC in command line. I also installed Kindle Preview and have kindlegen.exe in `C:\Users\user\AppData\Local\Amazon\Kindle Previewer 3\lib\fc\bin'. I tried to set PATH to the exe and rebooted, but KCC still doesn't find it. I didn't know whether to put PATH in the user or system variables. Thanks for help.

**Comment by nosovk** [comment]
@cobblepot1 I've made a separate folder `%userfolder%/.bin`, added it to path, and stored kindlegen there. It helped, now kcc works with it.

**Comment by cobblepot1** [comment]
Thanks! Do I add to PATH in the User or System variables?

**Comment by darodi** [comment]
adding to your path should fix it. 
reopen if needed
