### ISSUE TITLE
Do KCC need any refinment for support kindle paperwhite 2021 (6.8 inch)?

### ISSUE THREAD

**Issue by anirugu** [ciromattia/kcc#403]
Does KCC require any changes for support Kindle paperwhite 5. There is no option for this in KCC for now.

**Comment by Einlar** [comment]
It needs a different resolution. I have added a PR that adds a profile for the PW5 #404, with instructions of how to install it. It works on my device.

**Comment by comicrocharly** [comment]
I followed preciselly your istruction and get a series of errors when converting, as reported from a user under your pull request. I'm on Windows 10. I even get the same errors just git cloning the last relese and trying to run the python script as itself.

**Comment by darodi** [comment]
should be fixed with #405 
reopen if needed

**Comment by anirugu** [comment]
@darodi Happy to see your PR merged. Do you have plan to release new build anytime soon?

**Comment by darodi** [comment]
@anirugu 

still waiting for some configuration on the repository to activate the build pipeline in github actions
see
https://github.com/ciromattia/kcc/issues/456#issuecomment-1382835883

**Comment by darodi** [comment]
@anirugu 

you can get the build here in the meantime
https://github.com/darodi/kcc/releases

**Comment by anirugu** [comment]
Thanks @darodi I got the build. I will try my best to test it out this weekend :)
