### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Ceroes** [ciromattia/kcc#408]
Getting an "Acess is denied, Error during conversion" Please consult wiki message when trying to convert a CBZ to Mobi/azw3. but I dont see anything on the wiki about it?

Folder structure is made from a group of folders zipped.

Title.cbz>Folders>webp

**Comment by Ceroes** [comment]
I found it was just cause zip did not make the structure like that it put it into another folder...

**Comment by Ceroes** [comment]
NM I thought it was working now its telling me when I have it in the proper folder structure that its unsupported...

Using Title.cbz>Folders>webp which looks like

**Comment by Ceroes** [comment]
https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting

The middle list.

**Comment by joaobosconff** [comment]
is there a workaround?

**Comment by darodi** [comment]
I'm not sure I understand your issue.
Could you elaborate and give an example of the folder structure?

in windows:
`dir /s your_folder`
in linux
`find ./your_folder`

**Comment by axu2** [comment]
Unsupported directory structure usually means you have a loose cover page among chapter folders. Move the cover page to the first chapter folder, renaming as needed to ensure its first in order. 

This has been added the wiki linked in the error message.

**Comment by axu2** [comment]
Access is denied is because windows hasn't let go of the file yet after downloading probably.

**Comment by axu2** [comment]
Solved in #630 by unzipping first
