### ISSUE TITLE
Pages outputted as out of order.

### ISSUE THREAD

**Issue by VictorGamerLOL** [ciromattia/kcc#409]
In every file explorer, the pages are in what order they are supposed to be. Windows file explorer and 7 zip have the correct alphabetical order.

I have discovered that this is due to the program putting the character of "#" before a space, which causes stuff like extras to come before the final chapter of a volume.

Who am I kidding this has not been updated in 2 years..

**Comment by darodi** [comment]
Here is an original directory with images 

```
$ls -1 images_orig/
'0 0.png'
'0 2.png'
01.png
03.png
04.png
05.png
06.png
07.png
08.png
09.png
10.png
```

I converted it to cbz.

Here is the result of the extract:

```
ls -1 images_converted/
0000-0000-kcc.jpg
0000-0002-kcc.jpg
0001-kcc-a.jpg
0001-kcc-b.jpg
0001-kcc-c.jpg
0003-kcc.jpg
0004-kcc.jpg
0005-kcc.jpg
0006-kcc.jpg
0007-kcc.jpg
0008-kcc.jpg
0009-kcc.jpg
0010-kcc.jpg
```

Where do you see the character "#"? :raised_eyebrow:

Expecting a proper example/description in an issue... who am am I kidding? :smirk:

**Comment by VictorGamerLOL** [comment]
Some sources where I get my images label chapters and page numbers using \# . Sometimes it is for all of them, sometimes for special sections like extras. The fact that some sources put # after the chapter number for extras in fact causes the extras to show up before the actual chapter and not respect the index if any. What I think my past self thought is that KCC considered a \# to come before a space in page ordering, which I find strange since \# comes after space in ASCII, causing it to not be the same order as explorer would otherwise display. This also happened for pages labelled like 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 instead 01, 02, 03, 04, 05, 06, 07, 08, 09, 10 although I can understand why that happens. Also sorry for my unfavorable message back then I really did not expect any response at all.

**Comment by darodi** [comment]
Do you mean something like this?

Even in OSes, the order is # before the number

![image](https://user-images.githubusercontent.com/4682830/217621985-0057ab95-2722-4cfe-a2a0-98d3d1c494c1.png)
![image](https://user-images.githubusercontent.com/4682830/217622169-fc021c0a-7e8d-413d-a444-76fffa9e4ce8.png)

**Comment by darodi** [comment]
KCC is just using the OS order, and '#' comes before ' '.

renaming using another char would fix it

```bash
$ sudo apt install rename
$ ls -al
total 10092
drwxrwxrwx 1 rodi rodi     512 Feb  8 20:14 .
drwxrwxrwx 1 rodi rodi     512 Feb  8 19:29 ..
-rwxrwxrwx 1 rodi rodi 1020406 Feb  5 12:52 chapter00#06.png
-rwxrwxrwx 1 rodi rodi  858301 Feb  5 12:51 chapter00.png
-rwxrwxrwx 1 rodi rodi  797510 Feb  5 12:51 chapter01.png
-rwxrwxrwx 1 rodi rodi  990863 Feb  5 12:51 chapter02.png
-rwxrwxrwx 1 rodi rodi 1028155 Feb  5 12:51 chapter03.png
-rwxrwxrwx 1 rodi rodi  911087 Feb  5 12:51 chapter04.png
-rwxrwxrwx 1 rodi rodi  926159 Feb  5 12:52 chapter05.png
-rwxrwxrwx 1 rodi rodi 1020406 Feb  5 12:52 chapter06.png
-rwxrwxrwx 1 rodi rodi 1053624 Feb  5 12:52 chapter07.png
-rwxrwxrwx 1 rodi rodi  833632 Feb  5 12:52 chapter08.png
-rwxrwxrwx 1 rodi rodi  865251 Feb  5 12:52 chapter09.png

$ rename -v 's/#/z/g' *
chapter00#06.png renamed as chapter00z06.png


ls -al
total 10092
drwxrwxrwx 1 rodi rodi     512 Feb  8 20:14 .
drwxrwxrwx 1 rodi rodi     512 Feb  8 19:29 ..
-rwxrwxrwx 1 rodi rodi  858301 Feb  5 12:51 chapter00.png
-rwxrwxrwx 1 rodi rodi 1020406 Feb  5 12:52 chapter00z06.png
-rwxrwxrwx 1 rodi rodi  797510 Feb  5 12:51 chapter01.png
-rwxrwxrwx 1 rodi rodi  990863 Feb  5 12:51 chapter02.png
-rwxrwxrwx 1 rodi rodi 1028155 Feb  5 12:51 chapter03.png
-rwxrwxrwx 1 rodi rodi  911087 Feb  5 12:51 chapter04.png
-rwxrwxrwx 1 rodi rodi  926159 Feb  5 12:52 chapter05.png
-rwxrwxrwx 1 rodi rodi 1020406 Feb  5 12:52 chapter06.png
-rwxrwxrwx 1 rodi rodi 1053624 Feb  5 12:52 chapter07.png
-rwxrwxrwx 1 rodi rodi  833632 Feb  5 12:52 chapter08.png
-rwxrwxrwx 1 rodi rodi  865251 Feb  5 12:52 chapter09.png
```


another option would be to adapt this to use the sort method you would like

https://github.com/ciromattia/kcc/blob/3a1737e8d0052bc993a5767a8033c8ff12ff1007/kindlecomicconverter/shared.py#L55-L60

**Comment by darodi** [comment]
- Duplicate #362

**Comment by Scotsguy** [comment]
For anyone else stumbling over this problem, here's the simplest patch I could come up with that just disables the renaming. Will break generating chapter titles for epub from folder names.

```diff
diff --git a/kindlecomicconverter/comic2ebook.py b/kindlecomicconverter/comic2ebook.py
index e1941be..7ea4f65 100755
--- a/kindlecomicconverter/comic2ebook.py
+++ b/kindlecomicconverter/comic2ebook.py
@@ -744,6 +744,7 @@ def getPanelViewSize(deviceres, size):
 
 
 def sanitizeTree(filetree):
+    return {}
     chapterNames = {}
     for root, dirs, files in os.walk(filetree, False):
         for name in files:
```
apply using `git apply`

**Comment by axu2** [comment]
@cyberbad @4AM-Campfire @VictorGamerLOL @Scotsguy

I'll need some further testing, but looks like disabling the `slugify` function fixes it too.

```
def slugify(value, isdir):
    return value
```
