### ISSUE TITLE
Use MozJPEG as the JPEG encoder

### ISSUE THREAD

**Issue by winstonma** [ciromattia/kcc#415]
It seems to me that the quality of MozJPEG can create a 10-20% smaller JPEG file, with the same image quality.

**Comment by darodi** [comment]
I tried it.


- source directory:
   - 38M, 183 files
- conversion
  - spread splitter: indeterminate
  - stretch/upscale: checked
  - kindle PW5
  - mobi target

results

- Without MozJPEG :
  - time taken : 1min10s
  - size 70M
- With MozJPEG :
  - time taken : 2min17s
  - size 66M


I'm not sure everybody would like a processing time multiplied by 2.
We should at least make it optional with a parameter

**Comment by darodi** [comment]
@winstonma 

While waiting for the pull request merge, 
I built a version with this change here
https://github.com/darodi/kcc/releases

**Comment by darodi** [comment]
I made a second test, the last code is not using PIL for preprocessing (PR and built version)

- -With MozJPEG :
  - time taken : 1min53s
  - size 52M

much better

**Comment by winstonma** [comment]
@darodi Thanks for this

Actually MozJPEG is 10-20% smaller is based on comparison with [cjpeg](https://siipo.la/blog/is-webp-really-better-than-jpeg). I guess the original PIL library is not as good as cjpeg therefore it can get 25% smaller. But still it is not conclusive as the quality setting for default PIL and MozJPEG may not be the same.

I heard that Quality setting of 75 to 80 would be a sweet value

**Comment by AcidWeb** [comment]
This even was checked how it works on real device? Kindlegen might not support it and it re-encode images again.

**Comment by darodi** [comment]
@AcidWeb 

The epub is smaller and works on kobo.
The epub -> mobi creates a smaller file too
It works fine on my kindle PW

**Comment by AcidWeb** [comment]
Run kindlegen in debug mode and make sure it not reconvert images again - as that probably double the processing time.
