### ISSUE TITLE
Converted books not showing in Kindle

### ISSUE THREAD

**Issue by ali-oem** [ciromattia/kcc#421]
Hi, using the latest KCC version with the latest Kindelgen extract from Kindlepreviewer folder, my Kindle wasn't able to show the converted books once copied there, the comics however are perfectly working on my PC.
Using a Kindle Paperwhite 3 with latest software update.
Thanks .

**Comment by darodi** [comment]
We need more information to be able to assist

**Comment by ali-oem** [comment]
> We need more information to be able to assist

It's been long ago that this happened, but resetting my kindle to factory settings solved the problem, I guess a full Paperwhite 3 can have a hard time processing comics.
