### ISSUE TITLE
Source Directory Empty

### ISSUE THREAD

**Issue by TatianaC** [ciromattia/kcc#422]
Hello. I looked at the wiki but the suggestion didn't solve my problem. 

I am trying to upload a zip to KCC so that I can read an entire volume at once (and also read it manga style), but when I go to add the file manually, I receive an error telling me that the source directory is empty. I also receive this error when dragging and dropping zip files directly of the cbz files into KCC. 

Is there another option? Or a solution available for this? 

Thank you.

**Comment by darodi** [comment]
It should work with zip files.
What is the structure inside your zip? What is the file format for images?

**Comment by TatianaC** [comment]
How do you mean by "structure inside the zip"?

It is all the images, with a cbz extension that I put into a single zip
folder.

**Comment by darodi** [comment]
cbz is the same as a zip file.
There is no point in doing a zip of a zip.
Test for yourself, if you rename the extension to zip, you'll be able to extract it and see images.

So just drag and drop your cbz files to KCC instead. KCC will find the images in them.

If you have a cbz for each chapter and want a volume,
if you are using windows:
- put the cbz files in a directory, 
- use 7zip, select all of them, 
- right click, choose `7zip`
- choose `extract to *\`,  It will create a subdirectory for each chapter
- move the cbz files out of the directory
- drag and drop the directory to KCC.

KCC will process the directory and the subdirectories with images inside.

**Comment by TatianaC** [comment]
I dont think I understand these last two steps. Is there a video I can
watch?


   - move the cbz files out of the directory
   - drag and drop the directory to KCC.


I extract the files to 7z and then I get different folders for each
chapter. Inside the folders are the images.

When I drag the folders to KCC it converts them but doesnt create a volume.
They are individual files.

I dont understand how to create one large volume. I just kee getting
seperate files that cant be combined into one file to read all at once.

**Comment by TatianaC** [comment]
Oh!!! I figured it out!

Thank you so much!!! I am not very tech savvy so I was struggling for a
bit.

But it works!!! Sorcery!!!

THANK YOU.

**Comment by darodi** [comment]
You're welcome. 🧙‍♂️
You can close the issue then  
Have a good read!😉
