### ISSUE TITLE
Install KindleGen on Linux

### ISSUE THREAD

**Issue by Y0seph** [ciromattia/kcc#424]
So, I'm a noob, and I can't figure out how to get KindleGen (ik it has been discontinued)
Where do I get the files, where do I have to move, and are there any commands I should write to get it running?

**Comment by darodi** [comment]
[KindleGen](https://www.amazon.com/gp/feature.html?docId=1000765211) – which offers a command line interface and supports [Linux](https://archive.org/details/kindlegen2.9), [Mac OSX](https://web.archive.org/web/20190905040839/https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211) and [Windows](https://archive.org/details/kindlegen_win32_v2_9) – has been deprecated, but binaries can still be found on the internet.)

**Comment by Y0seph** [comment]
What should I look for (I meant it when I said I was a noob 😅)
If you can give me any advice will really great xD

**Comment by ReViDiSwO** [comment]
> What should I look for (I meant it when I said I was a noob 😅) If you can give me any advice will really great xD

Did you find a solution ?

**Comment by Y0seph** [comment]
Nope, nada... Nothing at all

**Comment by Y0seph** [comment]
> Did you find a solution ? 

Nope, nada... Nothing at all 🙃

**Comment by Eitetsu0** [comment]
😁 https://archive.org/download/kindlegen2.9/kindlegen_linux_2.6_i386_v2_9.tar.gz

URL above is used by the ARU package https://aur.archlinux.org/packages/kindlegen

**Comment by hhtien1408** [comment]
> > Did you find a solution ? 
> 
> Nope, nada... Nothing at all 🙃

> Download kindlegen from archive website
```
$ wget https://archive.org/download/kindlegen_linux_2_6_i386_v2_9/kindlegen_linux_2.6_i386_v2_9.tar.gz

```

> Extract kindlegen from archive to $HOME folder

```
$ unzip kindlegen_linux_2.6_i386_v2_9.tar.gz

```
> Copy kindlegen into '/usr/local/bin'(you should change 'h2t' for your user name)

```
$ sudo cp -R '/home/h2t/Desktop/kindlegen' '/usr/local/bin'
``` 
> Grant full permission to read/write/excutive to kindlegen for MOBI conversion.
```
$ sudo chmod +rwx '/usr/local/bin/kindlegen' 
```
Tested on Linux Mint 20.3 but it will work with other Linux debian distros.

![image](https://user-images.githubusercontent.com/49115404/196299561-908467ff-1d37-4733-8641-c4a4313f2f01.png)

**Comment by darodi** [comment]
reopen if needed

**Comment by duykhanh471** [comment]
There is a better way to do so imo.
First, install Kindlegen using this link : https://archive.org/download/kindlegen/kindlegen (it will install the binary file).
Next, open the terminal and `cd Downloads` (or whatever directory you've downloaded the binary file). Then follow the installation instructions on the wiki : https://github.com/ciromattia/kcc/wiki/Installation#appimage (Skip the X11 part if you're on Wayland like me). Here is the result 
![image](https://github.com/ciromattia/kcc/assets/119519461/7b792e4f-4c9f-44a3-99fd-479e2ae7c013)
