### ISSUE TITLE
Can't figure out how Spread Splitter works

### ISSUE THREAD

**Issue by Nurovek** [ciromattia/kcc#425]
Hello everybody, 

**Kindle Comic Converter 5.5.2**

I've converted several cbr/cbz to .mobi thanks to this very helpful program.
But I can't manage to make spread splitter work. In the generated mobi files, the double-pages are always two single pages even when I fully check the box.

_The only time it "worked" was because the double page was litterally two pages on one jpg._

I'm not sure what I'm missing here therefore I need help. Thanks
Maybe I just misunderstood the intent of this feature and instead of gathering two pages two be full, it's rather splitting a full-width double-page in two single pages ?

For instance, here is a "double-page" not displaying as a spread. 
![00013](https://user-images.githubusercontent.com/5867791/169785156-5d43d76f-cb11-4f14-9d75-414f8d8e9a25.jpeg)

![00012](https://user-images.githubusercontent.com/5867791/169785167-84ada2bd-b0d2-44c1-a323-3a7568f27836.jpeg)

**Comment by darodi** [comment]
> _The only time it "worked" was because the double page was litterally two pages on one jpg._
> 


> I'm not sure what I'm missing here therefore I need help. Thanks Maybe I just misunderstood the intent of this feature and instead of gathering two pages two be full, it's rather splitting a full-width double-page in two single pages ?

It's page splitting, not page gathering :wink:
It takes a jpg containing 2 pages (width > height) and splits it and/or rotates it

C'est du fractionnement de pages, pas du regroupement de pages :wink:
Il prend un jpg contenant 2 pages (largeur > hauteur) et le divise et/ou le fait pivoter

```
Double page parsing mode. 
0: Split 
1: Rotate 
2: Both 
[Default=0]
```


see/voir
 https://github.com/ciromattia/kcc/blob/4ec4c9966c727d6dac44507d34607bd7d2c5ed5c/kindlecomicconverter/image.py#L120

**Comment by Nurovek** [comment]
Haha yes, I should have guessed that. 
So I should rather find a way to combine two pages in order to create a full-width spread. Maybe you know some way to do so ? 

But I'm not even sure I want to recreate my generated .mobi from my cbz files. It's not even that uncomfortable to not have a full-width spread in the end

(Merci pour la traduction en français ^^)

**Comment by darodi** [comment]
@Nurovek 
je ferme le ticket
rouvrir si nécessaire
