### ISSUE TITLE
KCC not starting up

### ISSUE THREAD

**Issue by adrian-aleph** [ciromattia/kcc#428]
I have a laptop and a desktop pc. In my desktop pc KCC runs flawlessly but in my laptop KCC doesn't even start up. What can i do about this? I can't use my desktop pc because I'm out of town for a while.

**Comment by titolopolous** [comment]
Same here.

**Comment by mo-man** [comment]
@adrian-aleph  the latest binary works, which is version 5.5.2.  The download link through the KCC website and also on the KCC GitHub readme is pointing to the 5.1.2 binary.  If you change the URL to https://kcc.iosphe.re/Windows/KindleComicConverter_win_5.5.2.exe this will work.

**Comment by darodi** [comment]
reopen if needed
