### ISSUE TITLE
KCC closes at start - Windows 10 - 5.1.2

### ISSUE THREAD

**Issue by retardBoy** [ciromattia/kcc#429]
I don't know what can cause this, but KCC doesn't even start on my HP Laptop, as soon as it opens, the programs closes itself.

**Comment by mo-man** [comment]
@retardBoy the latest binary works, which is version 5.5.2.  The download link through the KCC website and also on the KCC GitHub readme is pointing to the 5.1.2 binary.  If you change the URL to https://kcc.iosphe.re/Windows/KindleComicConverter_win_5.5.2.exe this will work.

**Comment by retardBoy** [comment]
I can't believe it, it worked, thank you very much bro.

**Comment by darodi** [comment]
seems OK, closing the issue
