### ISSUE TITLE
One of workers crashed. Cause: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by apa-u** [ciromattia/kcc#432]
Hi, Iḿ trying to convert my mangas to MOBI however im having issues that some of the codes are in float and not int. I've atached screenshot below for reference.

Traceback:
  File "/home/jpvergara/kcc/kindlecomicconverter/comic2ebook.py", line 563, in imgFileProcessing
    img.autocontrastImage()
  File "/home/jpvergara/kcc/kindlecomicconverter/image.py", line 261, in autocontrastImage
    self.image = ImageOps.autocontrast(Image.eval(self.image, lambda a: 255 * (a / 255.) ** gamma))
  File "/usr/lib64/python3.10/site-packages/PIL/Image.py", line 3100, in eval
    return image.point(args[0])
  File "/usr/lib64/python3.10/site-packages/PIL/Image.py", line 1676, in point
    return self._new(self.im.point(lut, mode))

**Comment by darodi** [comment]
see
- https://github.com/ciromattia/kcc/issues/406
- https://github.com/ciromattia/kcc/pull/426

**Comment by hhtien1408** [comment]
> see
> 
>     * [Work-around to "RuntimeError... 'float' object cannot be interpreted as an integer during execution" for kcc-c2e.py powershell/CLI #406](https://github.com/ciromattia/kcc/issues/406)
> 
>     * [Fix program to work with new dependency versions #426](https://github.com/ciromattia/kcc/pull/426)
I cannot fix this issue with KCC 5.5.2 flatpak version in Linux Mint 20.3. 
Anyway to use GUI or CLI perfectly on Linux Mint? Beta 5.5.3-6 for Linux users available somewhere?
Under Windows and MacOS, KCC 5.5.3-6 Dadori work perfectly.
I have difficulty finding path /app/lib/python3.10/... in the error dialog to edit code as suggested by [Carleslc](https://github.com/Carleslc)

Hope you could help me, Dadori! Thanks a lot!

![image](https://user-images.githubusercontent.com/49115404/196085353-e71c0f4f-8de4-4294-ba9a-f31f29936f60.png)

**Comment by darodi** [comment]
@hhtien1408 

I added an appImage and a docker it in this fork: 
https://github.com/darodi/kcc/releases
https://github.com/darodi/kcc/pkgs/container/kcc

**Comment by hhtien1408** [comment]
Great works. Thanks for all!

**Comment by darodi** [comment]
sould be fixed in version 5.6.0
reopen if needed
