### ISSUE TITLE
net able to cover to mobi

### ISSUE THREAD

**Issue by danushdabby** [ciromattia/kcc#434]
I tried to download kindlgen through brew on Mac but they are telling I can't download it even I can't download it on amazon 
PLS TELL HOW TO DOWNLOAD KINDLEGEN ON MAC

pls help

danUsh

**Comment by naveengovind** [comment]
install Kindle Comic Creator with brew `brew install kindle-comic-creator --cask` and If you show package contents of the application then Contents -> MacOS -> kindlegen will be inside and work as a standalone executable.

**Comment by danushdabby** [comment]
> install Kindle Comic Creator with brew `brew install kindle-comic-creator --cask` and If you show package contents of the application then Contents -> MacOS -> kindlegen will be inside and work as a standalone executable.

sorry I dint understand the last part which u told

**Comment by naveengovind** [comment]
[kindlegen.zip](https://github.com/ciromattia/kcc/files/9459511/kindlegen.zip)

Ya no problem i just went ahed and attached the file here hope this helps.

**Comment by danushdabby** [comment]
yup I got thank u so much naveengovind 
yess

**Comment by danushdabby** [comment]
j
