### ISSUE TITLE
MacOS Monterey v12.6: “Kindle Comic Converter” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by apolidoro** [ciromattia/kcc#436]
When I try to open the KCC App on my MacBook I get the following message:
<img width="272" alt="Screenshot 2022-09-16 at 17 15 29" src="https://user-images.githubusercontent.com/107958779/190672816-5b9f8cff-b8e3-4116-a5f0-0e736856b300.png">

“Kindle Comic Converter” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

**Comment by Arthegor** [comment]
right click on kcc icon -> click open -> click open on popup

**Comment by Pasicho** [comment]
This issue persists on 5.6.0 release and 5.6.1 pre-release.

**Comment by darodi** [comment]
@Pasicho 
>  that isn't a viable solution for the regular user.

https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/

>  Prerequisites
>  
>  Having a paid [Apple Developer Program](https://developer.apple.com/programs/) subscription. This costs about ~$99 per year depending on your country and is necessary to generate the required certificates.

If you have $99, why not 😆

**Comment by darodi** [comment]
see commit b71d056559651b94eae7eb97397affe0493b6edf for a start
now we _"just_" need the keys.

**Comment by SonosMiro** [comment]
What's the fix for this issue? I'm on mac and I receive the message saying the DMG is damaged. It makes the application not possible to use. Any help would be greatly appreciated.

**Comment by darodi** [comment]
wiki page updated
https://github.com/ciromattia/kcc/wiki/Installation#macos-installation

**Comment by axu2** [comment]
If you want to install from source reference here, you'll also get all the latest features and bug fixes: https://github.com/ciromattia/kcc/wiki/Installation#install-from-sources

**Comment by axu2** [comment]
Anyone know why can't KCC be opened by just doing a right click > open? 

For example, melonDS only has the unverified error which can be easily bypassed with a right click open. 

Kcc additionally has this damaged error.

**Comment by axu2** [comment]
Once we merge in the #564 #565 which copied files into the `.app`, we no longer get the damaged or unverified error. I only get this:

<img width="257" alt="image" src="https://github.com/ciromattia/kcc/assets/20757319/c0e79b03-4982-4488-99f5-2d0e1f42b1d5">

https://github.com/axu2/kcc/actions/runs/5708724750

**Comment by borako** [comment]
There's no right click open -> open on popup on my Mac, 13.4.1

**Comment by borako** [comment]
> This issue persists on 5.6.0 release and 5.6.1 pre-release.
> 
> *Although my error says dmg is damaged. But that error is often related to the same developer cannot be verified error. The common work around is that users have to go into terminal and override permissions but that isn't a viable solution for the regular user.

I can override permissions. How do I do that? 

```
➜  /Applications ls -lath Kindle\ Comic\ Converter.app 
total 0
drwxrwxr-x  74 root  admin   2.3K Aug  6 09:37 ..
drwxr-xr-x@  3 blee  admin    96B Jan 21  2023 .
drwxr-xr-x@  7 blee  admin   224B Jan 21  2023 Contents

```

**Comment by borako** [comment]
NVM, I've finally found out that this does not support Apple Silicon yet.

**Comment by axu2** [comment]
@borako you can still run it under Rosetta. What happens when you click the app after installing from dmg?

**Comment by axu2** [comment]
@borako What are you right clicking? Make sure you install the app first

**Comment by borako** [comment]
@axu2 When I open it I get the message "Can't be opened because Apple cannot check it for malicious.." 
When I right click and open, I did get the option to override "unidentified developer" message, this was after installing your link, which was different from before even though they both say 5.6.2 dmg. Thank you!

**Comment by axu2** [comment]
@borako Sorry, didn't update the version number. Thanks for confirming it worked.
