### ISSUE TITLE
Cannot start kcc 5.5.2

### ISSUE THREAD

**Issue by ale11693** [ciromattia/kcc#437]
![image](https://user-images.githubusercontent.com/114103680/191581538-d7995c32-969e-411b-8018-13d60128c38b.jpeg)
I don't know why, I added kindlegen and 7z but not work 🥹🥹🥹🥹

**Comment by ale11693** [comment]
expert developer help me pls, i never use my laptop im newbie

**Comment by darodi** [comment]
the screenshot is clear.
Inside your zip file, there is a directory "Capitolo08" with a file "05.png" 
That png file is corrupted.

Use 7zip to unzip your files and delete/crop/restore that one.

**Comment by darodi** [comment]
reopen if needed
