### ISSUE TITLE
Files have a weird filename after convertion

### ISSUE THREAD

**Issue by it0na72** [ciromattia/kcc#438]
Using Pop_OS on the latest version 22.04.
My current KCC settings: https://i.imgur.com/ssxQJn6.png
What the output files look like: https://i.imgur.com/DQnHXAt.png

The files itself work when I change the name and remove the ".xdp" in the beginning, and remove the characters after "epub". However is this normal behaviour on linux? Is there anyway to change it?

On the other hand, is it possible to install the beta version on linux? Tried checking the assets but none of them work on linux. Converting to kepub would be a blessing. 

Thanks in advance.

**Comment by darodi** [comment]
@hhtien1408 

Thanks for this.
I'll add those instructions on my fork homepage as it might help others.

**Comment by hhtien1408** [comment]
> @hhtien1408 
> 
> 
> 
> Thanks for this.
> 
> I'll add those instructions on my fork homepage as it might help others.
> 
> 

Yeah. Hope it could help other Linux users while KCC Flathub is impossible to use (except metadata editor lol).
