### ISSUE TITLE
Is it possible to turn 1x4 strips into 2x2 to maximise screen usage?

### ISSUE THREAD

**Issue by ADVFRED** [ciromattia/kcc#439]
First off I have to say thank you for making this tool, it works fantastically! I just started rereading some of my old favorite comic strips on my kindle and I immediately noticed that a good chucnk of the screen is squandered. So my question is this: is it possible to output a strip in 1x4 as a 2x2 grid?

Images below to better illustrate:
This 1x4 strip
![1988-04-11](https://user-images.githubusercontent.com/56049633/194991505-712b65e6-7b31-45a8-a6dc-25082c619e72.gif)
When converted results in these two pages:
![IMG_3020](https://user-images.githubusercontent.com/56049633/194992060-383f6e82-53ac-4709-9ef7-eada695bff0f.jpg)
![image_123927839](https://user-images.githubusercontent.com/56049633/194992064-6e274eaa-034d-497d-8fcf-6e5a2c90a007.JPG)

**Comment by darodi** [comment]
should be possible, I'll have a look

**Comment by darodi** [comment]
I added a new option in the GUI
![image](https://user-images.githubusercontent.com/4682830/199339916-0992bc37-1155-42c2-ba5b-65434b94fa66.png)

check the beta version here
https://github.com/darodi/kcc/releases

**Comment by ADVFRED** [comment]
Thank you so much! I'll give that a try!

**Comment by ADVFRED** [comment]
I’m sorry for the late response—it works great! Thank you so much for adding the feature!
