### ISSUE TITLE
kfx output

### ISSUE THREAD

**Issue by nulllee** [ciromattia/kcc#442]
Hi, ciromattia. I'm a Chinese non-programmer user. 
Today, I’ve been trying to make a KFX comic and I learned to use your comic2ebook.py. It turns out that it’s much more difficult for someone like than I thought. So, can I ask you a favor? Please add the “KFX” as a output format option to KCC.exe(I have installed Kindle Previewer). Hope this won't bother you. I am looking forward to your reply.

**Comment by darodi** [comment]
@nulllee 

What is the point of a KFX output?
Is your reader unable to read MOBI/AZW3 or EPUB?

**Comment by nulllee** [comment]
> @nulllee
> 
> What is the point of a KFX output? Is your reader unable to read MOBI/AZW3 or EPUB?

Well, it’s complicated.
First, it’s better than azw3/mobi on kindle.
Second, it’s much more secure. Kfx files, as I know, can be read only on kindle.
I don’t know how it’s going in other countries. But in China, there are so many restrictions that many comics can’t be normally published or even be browsed on websites. So, we usually use cloud storage (like baidu netdisk) and chat group (mostly QQ group which can contain up to 2000 users) to store and share forbidden comics. But due to those strict restrictions, some fools’ online extracting and many a-holes’ tipping-off(they download and sell the files. To realize the purpose of charging fees, after downloading, they will tip off), files are always disappeared or locked, even worse, a large chat group may get banned.
Torrents’ environment in China is very bad for many reasons. Many people don’t even know how it works and they don’t fulfil their uploading duty so that torrents are not sustainable.
As I know, these companies are using hash to track files. Once someone has done something stupid like uploading comic files (epub,mobi,azw3,cbz,cbr,pdf,jpg,png and other image formats) in raw or compressed files without password or extracting encrypted files online instead of decompressing after downloading, files will be reviewed and anything they think is inappropriate for children will get banned.
For example, in Avengers: Age of Ultron，Captain American say“you son of a bitch” to Nick Fury and it is translated to “你个老伙计” which means “you old pal”. Can you believe it? Violence will be shortened, bad words (not so bad. To be honest, kids say these words every day because they’re acceptable) will be translated to other irrelevant words which is bad for understanding author’s meaning, porn and foreign religious content will be deleted.
For all these reasons, I think Kfx is in need. But many of Chinese kindle user don't even there's something like Kfx. Sadly, they don't think about these things. I know Kfx but I lack knowledge about programming. But, after all, Kfx can’t be read easily on computer so that there is no review for Kfx. Kfx can help us. You can help us.

**Comment by darodi** [comment]
The purpose of KCC is to transform images in a format that can be read on a e-reader.
You would prefer kfx as output because it would be "harder" to censor. I'm not sure it is the case. 
Amazon provides a Kindle app for Windows, macOS, Android, and iOS. 
That format can be opened on computers and the content of your books can be reviewed anyway.

**Comment by nulllee** [comment]
> The purpose of KCC is to transform images in a format that can be read on a e-reader. You would prefer kfx as output because it would be "harder" to censor. I'm not sure it is the case. Amazon provides a Kindle app for Windows, macOS, Android, and iOS. That format can be opened on computers and the content of your books can be reviewed anyway.

Thank you for your reply.
You’re right. Kfx can be opened on pc. But by now, they don’t censor Kfx and I’m sure about that. They only censor those files which can be preview online like doc, docx, pdf, epub(can be opened in zip format), mobi, etc. As for kfx, I uploaded a kfx which contain only one comic picture(a boxer whose right arm is broken and the bones are exposed) for test. Then I shared it with another one. It’s still there without deletion. So, I trust kfx.

**Comment by darodi** [comment]
@nulllee 

You should be able to create kfx files using
https://github.com/ciromattia/kcc/releases/tag/v5.6.1
and calibre plugin for kfx
Could you give it a try and give some feedback?

**Comment by nulllee** [comment]
> @nulllee
> 
> You should be able to create kfx files using https://github.com/ciromattia/kcc/releases/tag/v5.6.1 and calibre plugin for kfx Could you give it a try and give some feedback?

I don’t know what to say. It just doesn’t work. I selected the “kfx” and it created a epub file. Then it showed “All jobs completed.” I thought it might the path’s problem. So I cut it to the disk E ,changed the folder‘s’ name to “1” and tried again. The same thing happened.
The calibre plug can’t convert comic file in calibre. That plug will transfer comic file(mobi, epub) to normal file(kfx).

**Comment by nulllee** [comment]
> @nulllee
> 
> You should be able to create kfx files using https://github.com/ciromattia/kcc/releases/tag/v5.6.1 and calibre plugin for kfx Could you give it a try and give some feedback?

Thank you so much for your work.

**Comment by darodi** [comment]
@nulllee 

`KCC` only creates an `epub` file 
(compatible for kfx conversion <> standard epub)

That `epub` file can then be converted to `kfx` in a second step.
That second step is not done in `KCC`.

see
https://www.mobileread.com/forums/showthread.php?t=272407

- install calibre https://calibre-ebook.com/fr/download
- install the `KFX Output.zip` plugin in calibre https://www.mobileread.com/forums/attachment.php?attachmentid=197805&d=1668612691
- use calibre to convert from epub to your reader in kfx
- Enjoy!

**Comment by nulllee** [comment]
> @nulllee
> 
> `KCC` only creates an `epub` file (compatible for kfx conversion <> standard epub)
> 
> That `epub` file can then be converted to `kfx` in a second step. That second step is not done in `KCC`.
> 
> see https://www.mobileread.com/forums/showthread.php?t=272407
> 
> * install calibre https://calibre-ebook.com/fr/download
> * install the `KFX Output.zip` plugin in calibre https://www.mobileread.com/forums/attachment.php?attachmentid=197805&d=1668612691
> * use calibre to convert from epub to your reader in kfx
> * Enjoy!

Done. Thank you again. This is a good present for me. Happy Chinese new year(the year of 🐰)!  \^o^/

**Comment by AcidWeb** [comment]
I highly doubt that EPUB created by KCC can be converter to KFX and don't fall apart.

**Comment by darodi** [comment]
@AcidWeb 
I've tried it once and it worked 
I didn't test fully in details though 😅

**Comment by darodi** [comment]
@nulllee 

> Done. Thank you again. This is a good present for me. Happy Chinese new year(the year of 🐰)! ^o^/

Thanks! Happy new year to you too!

**Comment by axu2** [comment]
@darodi I tested this. KFX files don't fill the screen on my Kindle Scribe. So it's a pretty bad experience.

Maybe the UI should say something like "EPUB (Calibre KFX)" There are so many comments on Reddit, GitHub, and MobileRead saying why they got an EPUB instead of a KFX file.

Honestly though, since the experience is so bad, I feel like KFX should be restricted to CLI usage only.

**Comment by darodi** [comment]
I agree we should rename the label.
I'm not sure we should remove it from the gui though. It has been requested before, so some people use it via gui.

**Comment by axu2** [comment]
@darodi in that case renaming is best. I can't actually find the label in the code though lol

**Comment by darodi** [comment]
@axu2 

- see #538

**Comment by axu2** [comment]
It actually turns out that lots of people are footgunning themselves since it says EPUB (Calibre) and try to use it on their Kobos and the like with disatrous results.

I'm just gonna rename it to 

> KFX (broken)

i believe there are (non-automatable) methods of creating kfx with Kindle Create now. @nulllee Out of curiosity do you still use this feature?
