### ISSUE TITLE
Convert from Kindle Create KPF 

### ISSUE THREAD

**Issue by LostOnTheLine** [ciromattia/kcc#445]
I have a Manga series that unfortunately Amazon's version doesn't have the panel view mode.
I was looking for a way to make it work when I discovered the Kindle Comic Creator, which said its now just part of Kindle Create & also said it could export to ePub, which I figured was fine to convert the kfx or AZW3. I spent many hours figuring out how it worked & using the horrible interface to finish the 1st book & discovered it can only output ePub files if you have just word docx files.
Is there a way to convert those KPF files created by Kindle Create to be used in this program?

**Comment by darodi** [comment]
I know calibre has extensions to convert kfx files to other formats, but I've never tried.
You'll certainly need another calibre plugin to remove DRMs too.

**Comment by darodi** [comment]
I thought it was a kfx bought, hence, with drm.

**Comment by LostOnTheLine** [comment]
I can also extract the KPF file. 7-Zip says it's an unencrypted zip file

**Comment by LostOnTheLine** [comment]
> I thought it was a kfx bought, hence, with drm.

Nope, it's created in Kindle Create from a folder of images

**Comment by darodi** [comment]
https://github.com/ciromattia/kcc#a-word-of-warning

### A word of warning
**KCC** _is not_ [Amazon's Kindle Comic Creator](http://www.amazon.com/gp/feature.html?ie=UTF8&docId=1001103761) nor is in any way endorsed by Amazon.
Amazon's tool is for comic publishers and involves a lot of manual effort, while **KCC** is for comic/manga readers.
_KC2_ in no way is a replacement for **KCC** so you can be quite confident we are going to carry on developing our little monster ;-)


------------

What about converting the folder with images directly in Kindle Comic Converter ?

**Comment by LostOnTheLine** [comment]
I mean I spent hours getting the frames right. The Kindle Create is crap so I'm sure the auto detected frames are probably better in this guy but I'd still rather manually select the frames instead of having a script do it. That's why I was hoping for a way for the script to use the manually set frames that I spent hours adjusting from the KPF file

**Comment by LostOnTheLine** [comment]
If this one had the option of manually specifying frames I'd just use this one, but having it zoom into the 4 corners just isn't better than having it just show the page as that is going to give useful frames 1% of the time. But since this program can do the "covert it to the panel made format" thing I don't mind doing the work on the other & then converting it here if that's what it takes

**Comment by darodi** [comment]
Well... not really related to KCC.
You can always use KCC to convert from images with or without processing.
There is a KFX output, it will create an EPUB file that can then be processed by calibre and uploaded to you reader in kfx format.

I close the ticket

**Comment by LostOnTheLine** [comment]
> Well... not really related to KCC.
How is it not? I'm asking if there is a way to convert KPF using this program. If not suggesting it as a potential feature.

> You can always use KCC to convert from images with or without processing.
What do you mean? 

> There is a KFX output, it will create an EPUB file that can then be processed by calibre and uploaded to you reader in kfx format
That is something calibre can do on it's own, The whole intention is to have custom panels, because most comics/manga don't have the same frame size & shape on each page. I understand that may be too much for this app, but if the work is done in the only app it can be the framing details are there, I just don't know where. I'm just looking for a way to use that information without submitting a book to amazon for sale, as I just have copies of the books, I didn't create them

**Comment by axu2** [comment]
refer to the "Converting Comics and Manga:" section. 

[https://www.mobileread.com/forums/sh...d.php?t=272407](https://www.mobileread.com/forums/showthread.php?t=272407)

> Comics in KFX format with Guided View can be produced using Amazon's [Kindle Create](https://kdp.amazon.com/en_US/help/topic/GHU4YEWXQGNLU94T?tag=mr060-20). After creating the comic use the Publish option to produce a KPF file and then convert that to KFX using the plugin's command line interface. (Do not use the calibre GUI for comic conversion. It is not compatible with fixed-layout comics.)
> 
> For example, if the comic is named mycomicbook.kpf it can be converted to KFX using the following command:
> 
> Code:
> `calibre-debug -r "KFX Output" -- mycomicbook.kpf`
> 
> KFX comics sideloaded to an e-ink Kindle display in manga mode, even if they are not manga, and panel view does not function. Conversely, manga mode does not function in the Android or iOS Kindle app, but comics with panels will display using Guided View.
> 
> Comics produced using [Kindle Comic Converter](https://www.mobileread.com/forums/showthread.php?t=207461) or Amazon's [Kindle Comic Creator](https://www.amazon.com/gp/feature.html?tag=mr060-20&docId=1001103761) cannot be converted using this plugin. The plugin is also not able to convert fixed layout comics and manga from source formats such as CBR, CBZ, EPUB, or MOBI.

**Comment by LostOnTheLine** [comment]
> KFX comics sideloaded to an e-ink Kindle display in manga mode, even if they are not manga, and **_panel view does not function_**. Conversely, manga mode does not function in the Android or iOS Kindle app, but comics with panels will display using Guided View.
> 
> Comics produced using [Kindle Comic Converter](https://www.mobileread.com/forums/showthread.php?t=207461) or Amazon's [Kindle Comic Creator](https://www.amazon.com/gp/feature.html?tag=mr060-20&docId=1001103761) **cannot be converted using this plugin**. The plugin is also not able to convert fixed layout comics and manga from source formats such as CBR, CBZ, EPUB, or MOBI.

The sample MOBI file was able to be read on my Paperwhite & the panel view worked, so it IS possible for Sideloaded books to work. the problem, however, is converting them. This app is the ONLY thing that I've found that has successfully made a panel-view-readable comic. But unfortunately it's paneling is unintelligent, non-customizable, & ONLY zooms into the 4 quarters of the page. This doesn't work for MOST comics from my experience. Using that plugin can convert it to KFX, which is great, but I can already do that a bunch of different ways. It says you can create them, & convert them to KFX, but that they won't be "Guided View" or panel view. What I was, & still am, seeking is to be able to do what this app can do... But with the customization that this app doesn't have. If this app had the ability to accept KPF (Unencrypted) files & just produce the same output it does normally, just using the panel frames set by the KPF file, I could make it work, in ePub it'd probably convert fine, & if not I could jut use MOBI for those
