### ISSUE TITLE
Error KCC linux

### ISSUE THREAD

**Issue by fabtimus** [ciromattia/kcc#446]
Hello, I have put the put the file kindlegen at : /home/fab/.var/app/io.github.ciromattia.kcc/data/
But when I try to convert, I have this error : 
![crop guthub kcc](https://user-images.githubusercontent.com/119073645/204038995-1c9923e2-2d99-4340-8b96-4480593231fb.png)

**Comment by darodi** [comment]
duplicate ticket

see
- https://github.com/ciromattia/kcc/issues/432
- https://github.com/ciromattia/kcc/issues/406
- https://github.com/ciromattia/kcc/pull/426

**Comment by fabtimus** [comment]
Thanks!
I solved my problem and I am willing to share it with other Manjaro or Linux users in general.

The problem comes from version KCC 5.5.2, you need to install the latest beta, as for now, KCC 5.5.3-6 Darodi works perfectly: https://github.com/darodi/kcc/releases

Basically, at the first launch, you will see that you need to put the kindlegen file in another folder.
You may need root or sudo privilege to do so.

Enjoy!
