### ISSUE TITLE
KCC breaks one single manga page into 4 zoomed in sections.

### ISSUE THREAD

**Issue by yuhkid** [ciromattia/kcc#448]
I convert the cbz file to mobi with KCC and add the new mobi files to my kindle. When I open any file I see a full manga page normally, followed by 4 separate pages that are just the original page zoomed in on each corner. After these 4 zoomed-in corners the 5th page is the second page of the manga, and this repeats for the whole file. Im not sure if this is an intentional feature, but its a little annoying having to press the next page button 5 times whenever I want to go to the next page. Any advice much appreciated!

**Comment by darodi** [comment]
@yuhkid 

What model of Kinde are you using?
It's a feature.
You are using your reader in zoom mode.
Double tab the screen to change to normal mode.

**Comment by darodi** [comment]
@yuhkid 

can this be closed?

**Comment by yuhkid** [comment]
Absolutely, the problem has been resolved!
