### ISSUE TITLE
Kindlegen no more avilable

### ISSUE THREAD

**Issue by sembolino** [ciromattia/kcc#449]
kindlegen is no more available on amazon for download.
how can i do?

**Comment by darodi** [comment]
duplicate. see:

- https://github.com/ciromattia/kcc/issues/424#issuecomment-1128015241
- https://github.com/asciidoctor/asciidoctor-epub3/issues/363#issuecomment-684794354
- https://github.com/ciromattia/kcc/issues/402
- https://github.com/ciromattia/kcc/issues/371
