### ISSUE TITLE
How does kcc reduce the file size  ?

### ISSUE THREAD

**Issue by Joshuajrodrigues** [ciromattia/kcc#450]
Hey this is just curious question but does kcc compress the images when it converts to epub ? Does it change it to jpg ? Or is it because of timing borders that we usually end up with a smaller epub file than the original cbz ?

**Comment by Joshuajrodrigues** [comment]
> @Joshuajrodrigues 
> 

> - resizes to the size of the device (can expand)


And how does it handle fitting the image to the kindle screen ? I've tried creating a epub manually, with the width and height hard coded to the img tag to meet my kindle specification. But it always ends up kinda floating.

**Comment by Joshuajrodrigues** [comment]
Hmm I see. Thing is I've been trying to automate this more for personal use. But the epub I create always doesn't scale right. Even tho I hard code the width and height the same as kcc. Any idea what I could be missing ?

I have my own epub generator. I've compared the files but I think the opf has issues.

**Comment by macandiphone** [comment]
> When you select the device, the resolution is hardcoded ![image](https://user-images.githubusercontent.com/4682830/207044102-39d40d3a-55c1-471a-86e0-e315ab0f4a2d.png)
> 

may I ask why is there a Kindle scribe in your device list?

**Comment by darodi** [comment]
@macandiphone 

I added new devices in my fork.
https://github.com/darodi/kcc/releases

**Comment by macandiphone** [comment]
> @macandiphone
> 
> I added new devices in my fork. https://github.com/darodi/kcc/releases

@darodi 

Thank you for your help, Sorry for not replying message here, I've left a message under your issues about KCC 5.5.3 not working properly on macOS ( [https://github.com/darodi/kcc/issues/23] ). The last message was left by me.
