### ISSUE TITLE
Kindle Gen not getting recognised

### ISSUE THREAD

**Issue by PurpleDemon0yt** [ciromattia/kcc#454]
When I try to open the amazon kindlegen, it says it isnt there so i checked a random website that had it, so i downlaoded and moved it to the folder were kindle comic is and i still get it saying it still cant find the file, would be grateful if you could help me.
![image](https://user-images.githubusercontent.com/109389573/210634637-cdd9ecfa-0d50-4f68-a323-9a7e280ab4e5.png)
![image](https://user-images.githubusercontent.com/109389573/210634740-7054e3f6-cca9-4da8-baa7-3369d1819a70.png)

**Comment by paolovinoya** [comment]
It appears that your Kindle Comic Converter application is just a shortcut. Where is the actual ".exe" file located? 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/26787363/210729537-f81d765c-4831-4c0c-bd79-7aad7d4bc20a.png">

**Comment by PurpleDemon0yt** [comment]
I am so stupid thanks alot

**Comment by darodi** [comment]
@PurpleDemon0yt 

can this be closed?

**Comment by darodi** [comment]
reopen if needed
