### ISSUE TITLE
Change how KCC saves metadata when converting to MOBI/AZW3

### ISSUE THREAD

**Issue by jluhuang** [ciromattia/kcc#455]
Is there any way to modify the way KCC saves metadata when converting CBZ to MOBI/AZW3? I'd like to be able to change how the title and author fields for the MOBI/AZW3 file are generated.

**Comment by paolovinoya** [comment]
You can always edit the title and author fields before you even use KCC.

Try using [comictagger](https://github.com/comictagger/comictagger) for ComicRack XML manipulation. It can even set up the tags from either commandline or GUI.

**Comment by axu2** [comment]
Yes you refer to here: https://github.com/ciromattia/kcc/wiki/ComicRack-metadata
