### ISSUE TITLE
[Feature Request] Delete after conversion

### ISSUE THREAD

**Issue by HamzaM** [ciromattia/kcc#458]
Is it possible having the possibility to delete the file after conversion ? It would really be helpful

**Comment by darodi** [comment]
@HamzaM 

command line and GUI?

**Comment by HamzaM** [comment]
I used GUI and i didn't see it, if it's available as a command I'll do that then

**Comment by darodi** [comment]
That option doesn't exists yet.
I was asking if you would like that feature in the GUI too?

**Comment by HamzaM** [comment]
Oh yes both would help ! I've seen other people being interested in this as well

**Comment by darodi** [comment]
@HamzaM 

added in command line, but not in GUI yet.
Will be available in next release

**Comment by HamzaM** [comment]
> @HamzaM 
> 
> 
> 
> added in command line, but not in GUI yet.
> 
> Will be available in next release

Can't wait to try that out !
