### ISSUE TITLE
supporting Kindle Previewer

### ISSUE THREAD

**Issue by darodi** [ciromattia/kcc#463]
> Kindlegen is gone. You should definitely consider  supporting Kindle Previewer.

_Originally posted by @Grauen in https://github.com/ciromattia/kcc/issues/371#issuecomment-714340746_
            

TODO: adapt README

**Comment by darodi** [comment]
It can be found in "_Amazon Kindle Previewer 3 Folder\lib\fc\bin_" too but using the Wayback Machine is the fastest way to get it since no installation is needed.

_Originally posted by @HermesPasser in https://github.com/ciromattia/kcc/issues/371#issuecomment-718827421_

**Comment by innocenat** [comment]
Sorry for commenting on closed issue, but I was wondering why isn't Kindle Previewer's Kindle gen detected automatically?

It seems trivial to just add those path to `kcc.py` to just detect them automatically. Specifically, `%LOCALAPPDATA\Amazon\Kindle Previewer 3\lib\fc\bin\` on Windows and `/Applications/Kindle Previewer 3.app/Contents/lib/fc/bin/` on Mac OS. Are there anything I missed here?

**Comment by darodi** [comment]
OK I'm adding this and reopening the issue.
