### ISSUE TITLE
7z Not Found & "Add file" option only supports pdf

### ISSUE THREAD

**Issue by Madhav-Sheth** [ciromattia/kcc#469]
![image](https://user-images.githubusercontent.com/85406105/214062938-f024fe0a-4477-4ccf-899a-bd447b4a114b.png)
7zip is installed, I have already rebooted just to make sure.

![image](https://user-images.githubusercontent.com/85406105/214063334-b2e18863-fe65-481e-9ba7-1603e0d5e33b.png)
There isn't any option for cbr/cbz/cb7 file. 

The old version(5.5.2) works fine.
Am I missing something?

**Comment by darodi** [comment]
@Madhav-Sheth 

Is the directory of 7z in your `Path` environment variable ?
or is 7z.exe in the directory of KCC?

**Comment by Madhav-Sheth** [comment]
> @Madhav-Sheth
> 
> Is the directory of 7z in your `Path` environment variable ? or is 7z.exe in the directory of KCC?

I added `C:\Program Files\7-Zip` to `Path` and it worked. Thanks a lot!
