### ISSUE TITLE
Unable to run KCC AppImage

### ISSUE THREAD

**Issue by manikandancode** [ciromattia/kcc#470]
OS: Ubuntu 22.10 Wayland
Version: [v5.6.1](https://github.com/ciromattia/kcc/releases/tag/v5.6.1)

![Screenshot from 2023-01-24 13-31-47](https://user-images.githubusercontent.com/46480489/214240799-f2993a21-5d55-4b54-9370-a51a3e0798ae.png)

**Comment by darodi** [comment]
@manikandancode 

same problem with flatpak?
https://flathub.org/apps/details/io.github.ciromattia.kcc

**Comment by manikandancode** [comment]
No.

**Comment by darodi** [comment]
Is it ok when you run this?
`GDK_BACKEND=x11 ./kindleComicConverter-latest-x86_64.AppImage`

**Comment by darodi** [comment]
![image](https://user-images.githubusercontent.com/4682830/214384409-620eab73-6be6-46b6-b872-f64de574977e.png)

**Comment by darodi** [comment]
@manikandancode 

here is a beta update of the AppImage
let me know if this works for you. If so, I'll correct next release
https://github.com/darodi/kcc/releases/download/v5.6.2b1/kindleComicConverter-latest-x86_64.AppImage

with AppImage v5.6.1, this could also work

```
GDK_BACKEND=x11 LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./kindleComicConverter-latest-x86_64.AppImage
```

**Comment by manikandancode** [comment]
Beta Working.
