### ISSUE TITLE
Mac - "Kindle Comic Converter" is damaged and can't be opened

### ISSUE THREAD

**Issue by Seabass-25** [ciromattia/kcc#475]
Happens whenever I try to install the latest 5.6.1 or 5.6.0 version on my M2 Mac Air. This is also in regards to the .dmg files. I don't know if there is a common solution since I have yet to find any. I can verify that the 5.5.2 version does work though.

**Comment by Slownic** [comment]
This also happens on my 2019 Intel i9 MacBook Pro. I can't seem to find a way to use this release aside from running on CL in Docker. Any solutions?

**Comment by darodi** [comment]
https://github.com/ciromattia/kcc/wiki/Installation#x86_64-version

#### MacOS installation    
##### x86_64 version
see: KindleComicConverter_osx_*.dmg in **https://github.com/ciromattia/kcc/releases**   
If you can't open the last beta and the OS says it's damaged, fix it with:
```
xattr -d com.apple.quarantine /Applications/Kindle\ Comic\ Converter.app
```

**Comment by macandiphone** [comment]
<img width="495" alt="Screenshot 2023-02-01 at 3 57 57 PM" src="https://user-images.githubusercontent.com/30499000/216171403-57098057-765a-45e9-91cf-22ba446bc942.png">

The last few versions make my Intel MacBook Pro unable to convert comics. 

Currently the only way to get it to work is to return to version 5.5.2. Is there anything I can do? I hope to provide some error information.
