### ISSUE TITLE
Mac cannot convert manga in version 5.6.1

### ISSUE THREAD

**Issue by ghost** [ciromattia/kcc#476]
My Intel macBookPro can't convert manga or even change metadata. The only way to get it to work is to return to version 5.5.2. 
Is there anything I can do? I hope I can provide some useful information.

<img width="495" alt="Screenshot 2023-02-01 at 3 57 57 PM" src="https://user-images.githubusercontent.com/30499000/216175450-0b804874-6881-47ea-8e46-85a238d9546c.png">

<img width="510" alt="Screenshot 2023-02-01 at 5 01 59 PM" src="https://user-images.githubusercontent.com/30499000/216175465-a213b256-64dc-42f2-aecc-961d3d0fd5bd.png">

**Comment by darodi** [comment]
@macandiphone 

could you tell me if this version works better? 
https://github.com/darodi/kcc/releases/download/v5.6.2b2/KindleComicConverter_osx_5.6.2b2.dmg

If so, I'll push a PR

**Comment by macandiphone** [comment]
@darodi 
I can convert .zip files, but can't convert .cbz files, and metadata still can't be edited. To start the conversion I had to authorize trust in a program called 'URAR', I can't quite remember if this is the correct name.

**Comment by landonepps** [comment]
Using the beta I still had to run this command to allow 7z to run.
But the combination of the two fixed it.
```bash
xattr -d com.apple.quarantine -- /Applications/Kindle\ Comic\ Converter.app/Contents/Resources/7z
```

**Comment by StrawHatCyborg** [comment]
I'm getting the same issue. I've tried using all three versions, 5.6.1, the beta in this thread, and 5.6.2, and applied xattr to 7zm KCC, and even rar/unrar in from cask. I can only convert directories, zip and cbz ends with the same error in the screenshot.
