### ISSUE TITLE
1-2 blank pages before/after each actual page after conversion of PNG's

### ISSUE THREAD

**Issue by QuestioningEspecialy** [ciromattia/kcc#478]
Everytime I convert a set of 6 png's to a single EPUB, it has white and/or black pages mixed in. Trying different settings (including target device) didn't help. 

- Page 1: 1 white page beforehand
- Page 2: 1 white page beforehand
- Page 3: 1 black page beforehand
- Page 4: 2 white pages beforehand with a thin black strip on the top of the 1st
- Page 5: 2 white pages beforehand
- Page 6: 1 white and 1 black page beforehand; 1 white page afterward with a thin black strip on the top

**Comment by darodi** [comment]
could you provide more information? What are your input files and settings used? What reader are you using?

**Comment by QuestioningEspecialy** [comment]
Turns out, SumatraPDF v3.4.6 64-bit was failing where calibre v6.12 succeeded. 🤷🏿‍♂️
Is this a KCC issue, or should I post it on SumatraPDF's page?

As for the details, it's 5 png's and 1 jpg.
### Settings:
Other || EPIB
Manga mode | | 
 | Stretch/Upscale | 
 | | Color mode
JPEG/PNG/mozJpeg | | 
Gamma: Auto
Custom width: 1080 | Custom height: 1920

**Comment by darodi** [comment]
@QuestioningEspecialy 

KCC is made for physical devices like Kindle, Kobo, ...

If the result is correct in calibre, it might be a display issue in SumatraPDF.

If you just want to read on your pc, the best would be to just zip your directory with images, rename the zip file to cbz and open it in SumatraPDF.
No need for KCC.
