### ISSUE TITLE
Dragging & dropping images produces "Unsupported file type" error

### ISSUE THREAD

**Issue by QuestioningEspecialy** [ciromattia/kcc#479]
When I drag and drop a set of 5 png's and 1 jpg, I get the below error message for each of them. Trying a single image produces the same result.

>   Unsupported file type for D:\Users\owner\Documents\Docs\Books\removed\removed removed Vol 1\Chapter 00\removed01 (Eng).png

Just in case it matters,
### Settings:
Other || EPUB
Manga mode | |
| Stretch/Upscale |
| | Color mode
JPEG/PNG/mozJpeg | |
Gamma: Auto
Custom width: 1080 | Custom height: 1920

**Comment by darodi** [comment]
@QuestioningEspecialy 

You can drag and drop directories or files of those types :
*.cbz *.cbr *.cb7 *.zip *.rar *.7z *.pdf

`file selector add All *.*` is only present for file named with wrong extension
see https://github.com/ciromattia/kcc/pull/412#issuecomment-1061038095

So, just create a directory with your images instead
