### ISSUE TITLE
Add file > EPUB > Convert: "Error during conversion!"

### ISSUE THREAD

**Issue by QuestioningEspecialy** [ciromattia/kcc#480]
When I `Add file` a set of 5 png's and 1 jpg and `Convert`, I get the below error message for each of them. `Add directory` is the only way I've found to get around it.

>    Source: D:\Users\owner\Documents\Docs\Books\removed\removed removed Vol 1\Chapter 00\removed01 (Eng).png
>    Creating EPUB files
>    None
>    Error during conversion! Please consult wiki for more details.

Just in case it matters,
### Settings:
Other || EPUB
Manga mode | |
| Stretch/Upscale |
| | Color mode
JPEG/PNG/mozJpeg | |
Gamma: Auto
Custom width: 1080 | Custom height: 1920

**Comment by darodi** [comment]
Duplicate #479
