### ISSUE TITLE
7zip and double page

### ISSUE THREAD

**Issue by saisot2006** [ciromattia/kcc#481]
Hi, my KCC kept saying no 7zip even though I already installed it. One more thing, KCC mistook my comic pages as double pages though they are all single pages.

Thanx.

**Comment by darodi** [comment]
@saisot2006 

Is the directory of 7z in your `Path` environment variable ?
or is 7z.exe in the directory of KCC?

Please provide an example of your pages to reproduce the double page issue, thanks.

**Comment by saisot2006** [comment]
![07face380fa53de4e2a60313d05b4a94](https://user-images.githubusercontent.com/71863003/219815876-4090a7d3-636a-4b6e-8737-47e794282d2c.jpg)

This is one of my images.

**Comment by bust4cap** [comment]
i think the basic detection is just if the page is wider than it is tall, then it is considered a spread

**Comment by darodi** [comment]
bust4cap gave the answer.
closing this, reopen if needed
