### ISSUE TITLE
MOBI generation stuck if Kindle is mounted to macOS

### ISSUE THREAD

**Issue by ScherisMarie** [ciromattia/kcc#482]
Using **v5.6.1**, if I attempt to create a **MOBI** file when my _Kindle Paperwhite (10th Gen)_ is mounted in macOS, KCC will indefinitely stall out following the `Processing MOBI files...Done!` step.

If I unmount the device, it works normally.

(I'm on **macOS 13.2.1**, if that makes any difference.)

**Comment by Constantin1489** [comment]
Hi @ScherisMarie.
Please Would you write the command you used?
Also, would you provide your mobi file directory?

**Comment by ScherisMarie** [comment]
<img width="501" alt="Screenshot 2023-03-03 at 1 41 26 AM" src="https://user-images.githubusercontent.com/35884882/222649858-095f450d-bf97-427f-b103-c3cfe1211e23.png">

Assuming by absolute directory, you mean the folder path. It's the macOS **Downloads** folder for my user account. Not sure about the Kindle mounted drive --- how would I determine that?

**Comment by aliafshany** [comment]
@ScherisMarie 
yea, i confirm this. as soon as I unplugged my kindle pw 10th gen, I got this successful message

<img width="612" alt="image" src="https://user-images.githubusercontent.com/40741745/233832084-4aa37fde-d559-4036-8ce8-412c07795847.png">

**Comment by vinhtq115** [comment]
I have the same issue with v5.6.2. If my Kindle is connected to my Mac, KCC will always stuck at `Processing MOBI files... Done!` and hang there. I'm using macOS 13.4 (M1) and the binary is self-compiled.

**Comment by axu2** [comment]
This is almost definitely a permission issue with writing the kindle cover. you need to allow the app to write to external drives. When I ran it from vs code it asked for permission.

**Comment by CRP** [comment]
> This is almost definitely a permission issue with writing the kindle cover. you need to allow the app to write to external drives. When I ran it from vs code it asked for permission. I've never tried running the binary.

![image](https://github.com/ciromattia/kcc/assets/807824/6b046523-a49d-42f4-940b-e77062dab122)

I have permissions set up but app will still freeze as described by previous posters

**Comment by nelsonchen5** [comment]
+1

**Comment by axu2** [comment]
For now, you can try running from source, it doesn't give me issues and has a bunch of fixes.

**Comment by axu2** [comment]
I wrote a guide on how to run KCC from source, maybe it will help: https://github.com/ciromattia/kcc/wiki/Installation#install-from-sources

I don't have any issues running from source, and you also get all the newest features and bug fixes that haven't been bundled in a DMG. Also, I can't even get the DMG to run personally...

**Comment by aalfath** [comment]
I had the same problem. Installing 3.72 seems to fix it for me.

**Comment by axu2** [comment]
#564 should fix this issue. It's a problem with the process of creating the DMG file, the issue doesn't exist when running from source.

You can either run from source using the guide from above or fork the repo and run the GitHub Action to create a new DMG from that branch.

**Comment by darodi** [comment]
Does someone experienced with mac Os bundling knows if a property in Info.plist can change this behaviour?

https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources
