### ISSUE TITLE
Trying to use kcc-c2e with the flatpack version

### ISSUE THREAD

**Issue by galloramiro** [ciromattia/kcc#492]
Hi, I install the flatpack version, but when I run the kcc-c2e  I get the old version that I have installed. 

How could I run this? 

The GUI works fine but I want to run the kcc-c2e

Thanks

**Comment by galloramiro** [comment]
Amazing @darodi I didnt know that was the command! 
Thanks a lot!

**Comment by darodi** [comment]
@ScrambleTheRamble 

create a file `kcc.sh`
with 
`flatpak run --command=kcc-c2e io.github.ciromattia.kcc "$@"`
in it, then 

```
$ sh kcc.sh -p KPW5 -m ./Issue-1
comic2ebook v5.6.2 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.
Preparing source images...
Checking images...
Processing images...
Creating EPUB file...
Creating MOBI files...
```

or just run

```
$ flatpak run --command=kcc-c2e io.github.ciromattia.kcc -p KPW5 -m ./Issue-1
comic2ebook v5.6.2 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.
Preparing source images...
Checking images...
Processing images...
Creating EPUB file...
Creating MOBI files...
```
