### ISSUE TITLE
KindleGen slow for Scribe

### ISSUE THREAD

**Issue by axu2** [ciromattia/kcc#493]
It takes like 20 minutes for me to run the kindlegen portion even though the epub portion takes like 1 minute. Any way to make it faster? I'm using these settings by the way on a really old PC. I am also running KindleGen on files on my really old HDD, maybe moving the files to the SSD would help?
![image](https://user-images.githubusercontent.com/20757319/227601326-f230340e-4b2f-43ce-9c06-a8fd6f0294be.png)

![image](https://user-images.githubusercontent.com/20757319/227602678-5407f6e8-9c36-4e4d-a93b-949bdf0bcfba.png)

for reference, source files are jpg with 2250 height.

For reference, tried it on my gaming PC and kindlegen ran really fast, so assuming my old CPU is just weak.

**Comment by darodi** [comment]
@axu2 
You could also try to convert to epub and use send to kindle instead.
Here is the link:
web version https://www.amazon.com/sendtokindle
pc version https://www.amazon.com/sendtokindle/pc

**Comment by axu2** [comment]
Oh the limit is now 200 mb now. https://www.reddit.com/r/kindle/comments/z3otof/psa_you_can_now_upload_200_mb_files_to_kindle/

**Comment by axu2** [comment]
Curiously, the older version from archive seems to be significantly faster than the one from Kindle Previewer. Maybe I only encounter the issue since Scribe files are a lot bigger than others.

**Comment by darodi** [comment]
@axu2 

with https://www.amazon.com/Kindle-Previewer/b?ie=UTF8&node=21381691011
using 
` "Kindle Previewer 3.exe" your_book.epub -convert`

is the result faster?

**Comment by axu2** [comment]
Nope, the old version runs in like 2 minutes and the new one runs in like 6. The new one also creates files ~150 mb vs ~100 for the old one. Quite interesting. I don't see a visual difference on my Kindle Scribe.

**Comment by axu2** [comment]
Saw a bug in one of the old-version generated files. A page was in the wrong place, but closing and re-opening the book on the kindle fixed it. Hmmm

**Comment by axu2** [comment]
Overall, I get a much less buggier experience with the files generated by the latest version on my Kindle Scribe.

While it sucks it's a lot slower, less bugs is more important.

**Comment by axu2** [comment]
I just tried generating the mobi at the custom resolution 1440x1920 and it was really fast. Kindlegen transforming source images at the scribe resolution of 1860x2480 down to that really slows it down.

**Comment by darodi** [comment]
closing this

- Duplicate #460 
- Duplicate #500
