### ISSUE TITLE
KindleGen is missing on Docker kcc run

### ISSUE THREAD

**Issue by RhaynerRS** [ciromattia/kcc#497]
I'm trying to automate the creation and download of comics, but I'm getting the following error when I execute "docker run":
`comic2ebook v5.6.1 - Written by Ciro Mattia Gonano and Pawel Jastrzebski. ERROR: KindleGen is missing!`
 Where should I insert KindleGen or how can I resolve this error?``

**Comment by HamzaM** [comment]
Would love to know how we can put kindlegen in the directory, because the moment the container starts it stops right after as it only proceeds to run the kcc command
