### ISSUE TITLE
Crop cover art to fix screen size of specified device

### ISSUE THREAD

**Issue by mattthw** [ciromattia/kcc#504]
When processing a book for MOBI on a selected kindle device, the cover art should crop from middle to the device resolution (Example: 600x800 on Kindle 19th gen) so that the cover art does not have borders when the device is in rest mode.

**Comment by axu2** [comment]
Is #495 what you are looking for? It crops all pages however.

**Comment by axu2** [comment]
KCC will now crop images if the difference in aspect ratio is within 0.015. Practically, this is about 10 pixels per side on a Kindle Scribe. 

Closing for now, re-open if needed. Feel free to provide source image resolution. Any further cropping would probably look weird.
