### ISSUE TITLE
KCC 5.6.1.EXE wont run on windows 11

### ISSUE THREAD

**Issue by AragornThorongil** [ciromattia/kcc#510]
so i downloaded the 5.6.1.exe file but when i press it my computer wont even open or touch the file, anyone can help me resolve this please

i am currently running 5.5.2. downloaded it from the website so i have no idea how that one worked, but if anyone can teach me how to run 5.6.1 ill be very happy. ty

**Comment by darodi** [comment]
what happens when you open a command line window and try to run the exe file in it?

**Comment by AragornThorongil** [comment]
i have no clue how to do this, i usually just used the one that was on this website until i saw that this project existed, the website gave me an exe that worked without a problem and installed an application.
https://kcc.iosphe.re

**Comment by AragornThorongil** [comment]
well i just tried to run it, it did nothing for a good while, but just now it open the program, i had no idea this is how i had to run it

**Comment by darodi** [comment]
closing. You seem to be able to run it now.
reopen the issue if needed.
