### ISSUE TITLE
Automatic Output Splitting to ePub not working on MacOS

### ISSUE THREAD

**Issue by parispjones** [ciromattia/kcc#525]
I reviewed the instructions on [Automatic Output Splitting](https://github.com/ciromattia/kcc/wiki/Automatic-output-splitting) in the wiki and setup my files following Variant C. However, after conversion, it creates a single ePub file with all files instead of outputting for individual volumes.

Specs:
MacOS Ventura 13.1
KCC 5.6.2
Input is JPGs and output is Kobo Libra 2 ePub (Kepub).

**Comment by axu2** [comment]
Are you dragging in a folder that contains all the volumes. (e.g. only one line in KCC GUI.)
Or are you highlighting all the folders and dragging them in? (e.g. one line per volume in GUI.)

**Comment by parispjones** [comment]
The first one. I selected the root folder that contains all volumes in sub-folders.

**Comment by axu2** [comment]
Please try the 2nd way
