### ISSUE TITLE
Error During Conversion For All CBZ Files | Mac OS

### ISSUE THREAD

**Issue by chenobies** [ciromattia/kcc#528]
Adding CBZ file > EPUB > Convert: "Error during conversion!" but no specific reason as to why

Toggled on for Kindle PW 11 + Manga Mode, All Files are under 500 MB. First time using the converter so any fixes?

**Comment by axu2** [comment]
Are you able to run the python version straight from the repo? Otherwise, can you tell me the file structure of the cbz? Is it just images in the cbz or are their also folders or both?

**Comment by Sojiroh** [comment]
> Adding CBZ file > EPUB > Convert: "Error during conversion!" but no specific reason as to why
> 
> Toggled on for Kindle PW 11 + Manga Mode, All Files are under 500 MB. First time using the converter so any fixes?

I was having the same problem on Windows, I fixed it by adding 7z to my PATH. I don't know if this applies for es Mac Os version

**Comment by sparkirat** [comment]
> > Adding CBZ file > EPUB > Convert: "Error during conversion!" but no specific reason as to why
> > Toggled on for Kindle PW 11 + Manga Mode, All Files are under 500 MB. First time using the converter so any fixes?
> 
> I was having the same problem on Windows, I fixed it by adding 7z to my PATH. I don't know if this applies for es Mac Os version

What is the path could you please tell me?

**Comment by axu2** [comment]
@sparkirat Google "add 7z to path [Windows/mac]" depending on your OS.
@chenobies can you provide a screenshot of KCC when you first open it?

**Comment by axu2** [comment]
@Sojiroh can you try with latest version of kcc? 5.6.2

**Comment by Sojiroh** [comment]
> @Sojiroh can you try with latest version of kcc? 5.6.2 or if you feel brave running from source?

I tried 5.6.2 and it gives the same error. I tried the version posted on the "How to build M1" guide and it works perfectly
<img width="490" alt="image" src="https://github.com/ciromattia/kcc/assets/10394571/cba59b85-63bc-4459-a942-35924cc84caa">

So maybe it's a arm compatibility issue?
Anyways i'm trying to build from source using those steps and will let you know if it works

**Comment by sparkirat** [comment]
> > @Sojiroh can you try with latest version of kcc? 5.6.2 or if you feel brave running from source?
> 
> I tried 5.6.2 and it gives the same error. I tried the version posted on the "How to build M1" guide and it works perfectly <img alt="image" width="490" src="https://user-images.githubusercontent.com/10394571/244791639-cba59b85-63bc-4459-a942-35924cc84caa.png">
> 
> So maybe it's a arm compatibility issue? Anyways i'm trying to build from source using those steps and will let you know if it works

Hey it looks like you ver able to fix the issue can you post the link to the guide that helped you with this. Many thanks

**Comment by sparkirat** [comment]
> @sparkirat Google "add 7z to path [Windows/mac]" depending on your OS. @chenobies can you provide a screenshot of KCC when you first open it?

I don't know where the path is and I'm eager to know. When I extract the cbz file it suddenly works but without that it doesn't even work. Will putting in the 7z file help? If so please tell me the Mac path

**Comment by Sojiroh** [comment]
> > > @Sojiroh can you try with latest version of kcc? 5.6.2 or if you feel brave running from source?
> > 
> > 
> > I tried 5.6.2 and it gives the same error. I tried the version posted on the "How to build M1" guide and it works perfectly 
> > So maybe it's a arm compatibility issue? Anyways i'm trying to build from source using those steps and will let you know if it works
> 
> Hey it looks like you ver able to fix the issue can you post the link to the guide that helped you with this. Many thanks

@sparkirat https://github.com/darodi/kcc/issues/4#issuecomment-1364553511

**Comment by sparkirat** [comment]
> Are you able to run the python version straight from the repo to see if it generates an error? Otherwise, can you tell me the file structure of the cbz? Is it just images in the cbz or are their also folders or both? It will fail if their are mixed images and folders on the same folder level. It will also fail of another program was recently using the cbz.

How do I run the python version straight from the repo? there are many python files and also I don't know how to manually install it other than running the dmg appplication

**Comment by sparkirat** [comment]
> > > > @Sojiroh can you try with latest version of kcc? 5.6.2 or if you feel brave running from source?
> > > 
> > > 
> > > I tried 5.6.2 and it gives the same error. I tried the version posted on the "How to build M1" guide and it works perfectly
> > > So maybe it's a arm compatibility issue? Anyways i'm trying to build from source using those steps and will let you know if it works
> > 
> > 
> > Hey it looks like you ver able to fix the issue can you post the link to the guide that helped you with this. Many thanks
> 
> @sparkirat [darodi#4 (comment)](https://github.com/darodi/kcc/issues/4#issuecomment-1364553511)

I saw this guide it seems confusing I'm not sure how to use it

**Comment by axu2** [comment]
figured it out.

`brew install p7zip-rar`

**Comment by maxthiel** [comment]
Hi,

I have the same issue on a M1 Mac, with 5.6.2.
I've tried with KCC installed via DMG or with Homebrew.
I did `brew install p7zip` and have it in my path.

I tried to unzip/re-zip the cbz just to check if the file was the issue but no luck.
When processing the extracted image, I end up with the correct epub.
Extracting the cbz directly with 7z in the terminal works without issue.

Thank you!

**Comment by axu2** [comment]
@maxthiel Can you try the dmg file provided in #565 

https://github.com/axu2/kcc/actions/runs/5708082883

7z is in a different location on Apple Silicon vs normal Macs

**Comment by maxthiel** [comment]
Thank you @axu2 
I'm now getting an "Unsupported archive format" error.
![kcc cbz](https://github.com/ciromattia/kcc/assets/607492/ebdaa701-fa9a-458e-b827-ed0ae8ffd48f)

**Comment by axu2** [comment]
What happens when you run the exact command that KCC runs:

```
7z l -y -p1 "/Users/YOU/Downloads/manga.cbz"
```

**Comment by maxthiel** [comment]
Thanks for digging into this.

The 7zip command lists the files in the archive properly:

```
mt@computer Mangas % 7z l -y -p1 "manga.cbz" 

7-Zip [64] 17.05 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.05 (locale=utf8,Utf16=on,HugeFiles=on,64 bits,10 CPUs LE)

Scanning the drive for archives:
1 file, 32199333 bytes (31 MiB)

Listing archive: manga..cbz

--
Path = manga.cbz
Type = zip
Physical Size = 32199333

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2011-07-06 13:35:26 D....            0            0             Manga
2020-06-22 19:53:57 ....A       115671       109462  Manga/01_000.jpg
[...]
```

I get the same error with the version you've just posted.

**Comment by axu2** [comment]
OK, missed something, this one fixes it for sure: https://github.com/axu2/kcc/actions/runs/5708359548

I've removed the pre-included 7z binaries entirely so KCC will only look for homebrew installed 7z.

**Comment by maxthiel** [comment]
Thanks @axu2, this last version works!
* I got the "KCC request access to your files" popup
* The conversion worked as intended
