### ISSUE TITLE
Problem while try to convert comics

### ISSUE THREAD

**Issue by babayarro19** [ciromattia/kcc#530]
İ was using kcc for a long time but now i reseted mu computer and i had to download kcc again i did it but that time kcc is not working well when i Tried to convert a comic it said unsupported file type and thats why its not convert anything the file type is cbr and cbz btw

**Comment by axu2** [comment]
Did you add 7z to PATH? On Windows, it's:

>Add 7z to PATH via setx path "%path%;C:\Program Files\7-Zip"

**Comment by babayarro19** [comment]
Yes i did it after you said that but its not still working saying the same problem

**Comment by axu2** [comment]
What file type are the images? Unzip the cbz/cbr files. They are just renamed zip/ear.

**Comment by axu2** [comment]
Can you close KCC and re-open it and try again, now that you've added 7z to path? You have installed 7z first right?

**Comment by babayarro19** [comment]
Not that message but i get about 7z is saying like that  archive will not ne working because 7z lack but i download it how can i add it to path 
Btw i wrote that "%path%;C:\Program Files\7-Zip" to path

**Comment by axu2** [comment]
Just install it normally

**Comment by axu2** [comment]
I'll update the UI to be more explicit im #531
![image](https://github.com/ciromattia/kcc/assets/20757319/403d5326-8b7b-4573-b1df-2eddaf5011ff)

**Comment by Beebeedeedop** [comment]
I might be having the same issue on a Mac — what's the 7z solution for Macs?

**Comment by babayarro19** [comment]
İ download 7z and creat New file put the kcc and 7z in same file but you need to pull out 7z from main file also i add the 7z to path

**Comment by babayarro19** [comment]
Yes its working now

**Comment by axu2** [comment]
@Beebeedeedop https://github.com/darodi/kcc/issues/4#issuecomment-1364553511 This should fix for macs
