### ISSUE TITLE
[Bug Report] MOBI conversion

### ISSUE THREAD

**Issue by UPSA007** [ciromattia/kcc#535]
Whenever I create a MOBI file from cbz if I choose to Disable processing or an arbitrarily big resolution (haven't figured out the limits) the output comes out weirdly. The file opens in Kindle for PC as well as kindle android no problem but in a weird zoomed sort of way. I tried everything to view the full page but nothing works. P.S- I'm using KCC 5.6.2 and Panel view is disabled during conversion so that surely isn't causing the issue.
Thank You in advance.

**Comment by darodi** [comment]
If you are using mobi output, kindle gen is limited in resolution  during conversion.
Same thing with send to kindle.

>@darodi I have sent recently several epubs to my Scribe using Send to Kindle via web. They are converted to AZW3, and to the best of my recent experience the image resolution is still downscaled (down to 1440x1920).
_Originally posted by @nicoladicicco in https://github.com/ciromattia/kcc/issues/460#issuecomment-1523829841_

Also, kindlegen is slower for resizing than KCC.
see. https://github.com/ciromattia/kcc/issues/493

Why do you need mobi output + disable processing? What is your use case?
I don't see the point with a e-reader device.

**Comment by darodi** [comment]
>  Kindle for PC as well as kindle android 

OK

**Comment by UPSA007** [comment]
I agree cbz will work better. But sometimes the sync across devices feature is nice to have. Also since 200 MB size cap was implemented, what I do is change .MOBI to .epub and upload which prevents from the downscaling which happen if you just simply upload the epub.

**Comment by axu2** [comment]
In my experience KCC files look weird on any Kindle apps. They only look good on actual Kindles.

**Comment by axu2** [comment]
In my experience the files made by KCC only look good on actual Kindles, not in any Kindle apps

**Comment by darodi** [comment]
Some solutions, not related to KCC

- use a format with limited resolution. mobi conversion will downscale anyway.
- use a cbz reader instead with a sync app (google drive, dropbox, onedrive, syncthing, ...)
