### ISSUE TITLE
kcc-c2e如何为漫画添加封面？

### ISSUE THREAD

**Issue by Duck15** [ciromattia/kcc#539]
如果我在漫画文件夹下放置了cover.jpg 使用kcc-c2e就会报错。
报错如下：

PS D:\用户目录\桌面\onimai.comic.github> .\kcc-c2e_5.6.2.exe ./test/ -m -p K34 -o ./
comic2ebook v5.6.2 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.
Preparing source images...
Checking images...
Processing images...
Traceback (most recent call last):
  File "kcc-c2e.py", line 32, in <module>
  File "kindlecomicconverter\startup.py", line 49, in startC2E
  File "kindlecomicconverter\comic2ebook.py", line 74, in main
  File "kindlecomicconverter\comic2ebook.py", line 1166, in makeBook
  File "kindlecomicconverter\comic2ebook.py", line 816, in splitDirectory
UserWarning: Unsupported directory structure.
[9244] Failed to execute script kcc-c2e
但是，在使用kcc图形界面时，这样做并不会出错，并且能生成正常带封面的mobi文件

**Comment by axu2** [comment]
Do not have images and folders on same level. Move any loose images into a folder.

**Comment by Duck15** [comment]
> 
我已经通过删除cover.jpg解决了
但是我在kcc的gui版这样放可以跑通还会有封面，但是kcc-c2e不行。为什么呢？

**Comment by axu2** [comment]
May be easier to just put the cover in the folder for the first chapter. May need to rename the cover so it shows up first in the file order.

Sorry don't speak Chinese so may have missed something.

**Comment by Duck15** [comment]
> May be easier to just put the cover in the folder for the first chapter. May need to rename the cover so it shows up first in the file order.
> 
> Sorry don't speak Chinese so may have missed something.

thank you for your reply. 
my problen is decided.
because my studyis a little busy,so i can't respond promptly..
**thanks!!**
