### ISSUE TITLE
[Bug] Every Other Page are Gray Pages(PDF Issue)

### ISSUE THREAD

**Issue by Derzz** [ciromattia/kcc#540]
Hi,

I'm trying to convert a manga from PDF to EPub and every time I convert, every other page in the epub file contains a page filled with gray. I'm using a Kobo Clara HD with Manga Mode, Stretch/Upscale, and Cropping Mode with the power at 1.00x enabled. Is this a bug or is there an option that I can enable to get rid of this issue?

Eg. Every page has the actual manga content like so: 
![image](https://github.com/ciromattia/kcc/assets/45671788/336ebbd2-8ab7-4da0-af3c-7c99eaad48b6)

But then a gray page like this appears:
![image](https://github.com/ciromattia/kcc/assets/45671788/4befdbf6-db0f-4c34-b647-efd3584f5363)

And this pattern repeats for the whole ePub file.

**Comment by axu2** [comment]
If you open the epub on a PC do you still see the gray pages? The pdf might just have small gray images...

**Comment by Derzz** [comment]
So on Calibre and when unzipping the epub, the gray pages are still there. I'm looking at the pdf and there doesn't seem to have small gray images in there other than the manga being black and white.

**Comment by axu2** [comment]
Are pages being replaced with gray? Or are additional gray pages being added?

**Comment by Derzz** [comment]
Additional gray pages are being added.

**Comment by axu2** [comment]
Hmmm, my suspicion is that it's a problem with the source file. Are you able to obtain a CBZ instead? Or an image folder? Can you test with just a folder of .jpgs?

**Comment by Derzz** [comment]
So when I obtain the CBZ, it still is producing the same issues. The issue isn't here with a random JPG folder. Attached are some pages of the PDF, let me know if you need more information.
[よつばと! 第01巻_removed.pdf](https://github.com/ciromattia/kcc/files/11780182/01._removed.pdf)

**Comment by axu2** [comment]
I'll test myself soon. In the meantime, are you on the latest stable version 5.6.2?

**Comment by Derzz** [comment]
Yes, I’m on the latest stable version 5.6.2.

**Comment by axu2** [comment]
A single gray pixel is being generated between pages. 
![image](https://github.com/ciromattia/kcc/assets/20757319/a17e94e1-53a3-4d50-bed1-dc1d12d5f8e2)

The pdf file must have stray single gray pixels between pages... Are you able to get a better source?

**Comment by Derzz** [comment]
Sorry, I don't have a better source for this :( 

Is there a way to delete these files, I'm fine if I have to manually do it, but if I manually delete each single gray pixel file, how would I repackage the image files into an epub?

**Comment by axu2** [comment]
I would try another program to extract the images out of the pdf. And then use the extracted file in KCC.

**Comment by axu2** [comment]
Can you test #546 @Derzz

**Comment by Derzz** [comment]
Sorry, but what should I do with #540? I have the release version right now and there's no python file for me to edit in the release. Can you elaborate on what I should do to test this PR?

**Comment by axu2** [comment]
clone the branch of the PR and run it.

![image](https://github.com/ciromattia/kcc/assets/20757319/2127f9a8-e2a0-467b-a959-5b8560e61c36)

or run my branch directly

https://github.com/axu2/kcc/tree/skip-pdf-pixels

![image](https://github.com/ciromattia/kcc/assets/20757319/07541d82-d850-4151-8617-06659bbf186b)
