### ISSUE TITLE
M1 Mac mini, symbol not found in flat namespace '_jpeg_copy_critical_parameters'

### ISSUE THREAD

**Issue by Se7enYXS** [ciromattia/kcc#541]
When running kcc-c2e.py v5.6.2 on my Mac, there's an error :

Traceback (most recent call last):
  File "/Users/se7en/Downloads/kcc-master/kcc-c2e.py", line 33, in <module>
    startC2E()
  File "/Users/se7en/Downloads/kcc-master/kindlecomicconverter/startup.py", line 47, in startC2E
    from .comic2ebook import main
  File "/Users/se7en/Downloads/kcc-master/kindlecomicconverter/comic2ebook.py", line 45, in <module>
    from . import image
  File "/Users/se7en/Downloads/kcc-master/kindlecomicconverter/image.py", line 23, in <module>
    import mozjpeg_lossless_optimization
  File "/opt/homebrew/lib/python3.11/site-packages/mozjpeg_lossless_optimization/__init__.py", line 1, in <module>
    from .mozjpeg_opti import optimize
  File "/opt/homebrew/lib/python3.11/site-packages/mozjpeg_lossless_optimization/mozjpeg_opti.py", line 1, in <module>
    from ._mozjpeg_opti import lib, ffi
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/mozjpeg_lossless_optimization/_mozjpeg_opti.abi3.so, 0x0002): symbol not found in flat namespace '_jpeg_copy_critical_parameters'

I already installed all requirements.

There's no issue when running kcc-c2e.py v5.5.2.

Seems like an issue with mozjpeg-lossless-optimization package.

**Comment by axu2** [comment]
#523

**Comment by axu2** [comment]
Interestingly looks like you are using homebrew python too. I wonder if normal python works.

**Comment by Se7enYXS** [comment]
> Interestingly looks like you are using homebrew python too. I wonder if normal python works. Are you on m2 Mac mini too? Or any m2?

I'm using M1 Mac mini.

After trying [this method](https://github.com/wanadev/mozjpeg-lossless-optimization/issues/5#issuecomment-1557439188) , everything works fine now.

**Comment by axu2** [comment]
Thanks for confirming m1. I'm surprised you are the only other one to report this.

**Comment by Se7enYXS** [comment]
> Thanks for confirming m1. I'm surprised you are the only other one to report this. Can you add m1 to the title?

Already change the title. Thanks for your help.

**Comment by axu2** [comment]
@Se7enYXS Out of curiosity, how did you get PyQT5 working on M1?

**Comment by axu2** [comment]
Actually, I uninstalled everything in homebrew, I had some jpeg related stuff installed related to something else.
I also uninstalled homebrew python, using python.org version instead.
Now it works. No clue why.

Can you help me figure out which part caused the error?

**Comment by vinhtq115** [comment]
> Actually, I uninstalled everything in homebrew, I had some jpeg related stuff installed related to the Portal port. I also uninstalled homebrew python, using python.org version instead. Now it works. No clue why. Maybe just a slightly newer version of python fixed it.
> 
> Can @Se7enYXS help me figure out which part caused the error? Please try normal python.
> 
> Also @vinhtq115 did you run into this issue? Which python version did you use?

I haven’t run into this issue yet. I am using Python 3.11.4 from Homebrew. Also, I always create a virtual environment from that Python for compiling kcc.

**Comment by Se7enYXS** [comment]
> python.org

Can confirm, python 3.11.4 from python.org works fine, does not need [this method](https://github.com/wanadev/mozjpeg-lossless-optimization/issues/5#issuecomment-1557439188), just pip3 install mozjpeg-lossless-optimization, then every thing works.

**Comment by axu2** [comment]
Sounds like a bug in an older python version then. Guess we can close this.

**Comment by darodi** [comment]
it seems resolved
closing this.

reopen if needed

**Comment by Observer5** [comment]
my python version is 3.10.13
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/mozjpeg_lossless_optimization/_mozjpeg_opti.abi3.so, 0x0002): symbol not found in flat namespace '_jpeg_CreateCompress'

**Comment by axu2** [comment]
@Observer5 Please try latest python 3.11
