### ISSUE TITLE
Inverted color in few panes

### ISSUE THREAD

**Issue by MarcFacerias** [ciromattia/kcc#547]
Hello I've found that from time to time the epub generates one page with inverted color scheme (white background to black background). Do you know if this is a bug of the software or if it can be fixed through the configuration? I added both the original and the converted screenshots 

Thanks a lot 

![Screenshot from 2023-06-22 13-03-38](https://github.com/ciromattia/kcc/assets/38987718/8c1d82eb-1f49-4324-b28c-863bbde83d34)
![WhatsApp Image 2023-06-22 at 13 03 19](https://github.com/ciromattia/kcc/assets/38987718/efda08df-e810-4f0e-9b60-cf3718165329)

**Comment by axu2** [comment]
You sure you don't have dark mode enabled on Kindle? It's funky with Kcc files.

**Comment by MarcFacerias** [comment]
Oh yes my bad, I had the dark mode enabled, didn't know it messed up kcc. Thanks a lot for your fast reply, I'll close the issue
