### ISSUE TITLE
error during conversion

### ISSUE THREAD

**Issue by juno880** [ciromattia/kcc#549]
certain cbz files when i try to convert them give me the error message "none error during conversion! please consult wiki for more details" the same files when i try to edit meta data give error message "failed to save metadata! none traceback: File "kindlecomicconverter\KCC_gui.py", line 1208, in saveData File "kindlecomicconverter\metadata.py", line 119, in savexml" some other cbz work fine. Is it an error with my device or are the files damaged in some way

**Comment by erenseekingfreedom** [comment]
This happened to me too. It eventually fixed itself after some time and a few restarts.

**Comment by juno880** [comment]
Tries to unzip cbz files and they appear to be corrupted so it's on my end. Sorry should have checked that first

**Comment by darodi** [comment]
issue seems resolved
closing
