### ISSUE TITLE
Downloading KCC

### ISSUE THREAD

**Issue by KhalElh** [ciromattia/kcc#550]
Hello, I'm not familiar at all with this website. I just want to download KCC so I can read comics on my kindle. Im a windows user. I download the zip file but from there I have no idea what to do next. I have the KCC-master zip file. I downloaded 7zip like it recommended as well. I also downloaded the Github desktop app. Any help is much appreciated. Thanks :)

**Comment by darodi** [comment]
https://github.com/ciromattia/kcc/releases

scroll down to "assets" and [kcc_5.6.2.exe](https://github.com/ciromattia/kcc/releases/download/v5.6.2/kcc_5.6.2.exe)
