### ISSUE TITLE
“Kindle Comic Converter.app” is damaged and can’t be opened.

### ISSUE THREAD

**Issue by erenseekingfreedom** [ciromattia/kcc#551]
I downloaded the latest version [KindleComicConverter_osx_5.6.2.dmg], but after installation, I tried to open it and received a message saying “Kindle Comic Converter.app” is damaged and can't be opened. You should move it to the Trash. I am on MacOS Ventura.

**Comment by erenseekingfreedom** [comment]
This fixed it 
xattr -d com.apple.quarantine /Applications/Kindle\ Comic\ Converter.app
xattr -d com.apple.quarantine -- /Applications/Kindle\ Comic\ Converter.app/Contents/Resources/7z

**Comment by darodi** [comment]
https://github.com/ciromattia/kcc/wiki/Installation#x86_64-version

If you can't open the last beta and the OS says it's damaged, fix it with:
```
xattr -d com.apple.quarantine /Applications/Kindle\ Comic\ Converter.app
xattr -d com.apple.quarantine -- /Applications/Kindle\ Comic\ Converter.app/Contents/Resources/7z
```
