### ISSUE TITLE
[Bug] Colour Shift after conversion

### ISSUE THREAD

**Issue by UPSA007** [ciromattia/kcc#552]
Used KCC 5.6.2 on a bunch of cbz files with Kindle Scribe preset. Custom gamma with auto. Colour mode turned on with mozjepeg. In some of them I noticed a yellowish tint. Did anyone else notice any similar thing?

**Comment by axu2** [comment]
Can you try with color mode off?

Not sure how you can see yellow on a b/w Kindle unless you have the warm light on.

**Comment by UPSA007** [comment]
My mistake used in a tablet with kindle for Android app .

**Comment by axu2** [comment]
You should really use a native cbz viewer for an android tablet. Some probably offer sync.

**Comment by UPSA007** [comment]
I know and agree but it is simply too convenient to not use. Image quality despite compression looks descent. In most of the cases compression artifacts are not visible unless you go pixel peeping. For instance a 637 MB cbz got compressed into 192 MB epub and the image quality was ok. It was a manga with those dotted embossing patterns and some of the pages got slightly like 2 to 3 percent darker but other than that it looked visibly same.

**Comment by axu2** [comment]
Image compression can be done by another program. 

Anyways the dark factor is set by gamma. You can disable it by setting it to 1.0

**Comment by axu2** [comment]
But I highly suggest you use a cbz viewer. I personally like Tachiyomi, though it doesn't sync.  They have many more image adjustment options available.
