### ISSUE TITLE
Cannot install KCC.exe

### ISSUE THREAD

**Issue by jcmefra** [ciromattia/kcc#554]
Hi, I can't install the .exe file, may I know if you guys have a workaround for this? I run Windows 11 and it says "Seach application in store?" when I try to open the .exe

Thanks in advance!

**Comment by darodi** [comment]
KCC is not signed by a certificate (we didn't buy one)

So it might be blocked by windows 11 `Smart App Control`



see https://support.microsoft.com/en-au/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003

> What is Smart App Control?
> Windows 11
> 
> Smart App Control adds significant protection from new and emerging threats by blocking apps that are malicious or untrusted.

You can maybe try to turn it off.

> Where are the Smart App Control settings?
> 
> You can find the settings for Smart App Control in the App & browser control panel of the Windows Security app. The fastest way to access these settings is:
> 
>     Tap the Start button in Windows.
> 
>     Type Smart App Control in the search box.
> 
>     Select the Smart App Control system settings from the results.


https://helpdeskgeek.com/windows-11/how-to-enable-and-use-smart-app-control-in-windows-11/

> How to Disable Smart App Control in Windows 11
> 
> If you already have SAC enabled on your Windows 11 installation, you can always turn it off. However, remember that disabling SAC is permanent – you can’t turn it on again (or put it into Evaluation mode) without reinstalling Windows.
> 
> To disable SAC, head to Settings > Privacy & Security > Windows Security > App & browser control > Smart App Control settings and flip the switch to Off.


-------------------------


Same problem as 
- #436

**Comment by axu2** [comment]
To clarify, you are using the 5.6.2 exe linked in the releases page? And which version of 11? Are you on windows 11 s?

**Comment by darodi** [comment]
@jcmefra 

axu2 is right.
Windows 11 S is also limited to windows store apps only.
You can disable "S" mode if needed

https://4sysops.com/archives/what-is-windows-10-s-mode-how-does-windows-11-s-mode-differ/

**Comment by darodi** [comment]
TODO
add more information in the wiki page when we get feedback from jcmefra?

**Comment by jcmefra** [comment]
> To clarify, you are using the 5.6.2 exe linked in the releases page? And which version of 11? Are you on windows 11 s?
> 
> Try right click and troubleshoot compatibility
> 
> Answers from googling "windows 11 exe store"
> 
> If you feel brave try running the python code from GitHub directly.

I'm going to do the compatibility first, I purchased a new laptop but it has Windows 11 by default, I was able to install Calibre so I don't thing it has that "S" mode enabled but I'll check.

I'm not pretty sure if I need to run setup.exe directly or do a `python setup.exe install`. FHow do you install the app through the python code? Not quite sure, thanks!

**Comment by jcmefra** [comment]
Update: Just run using W8 compatibility and it worked. Thank you guys!

**Comment by darodi** [comment]
> I'm going to do the compatibility first, I purchased a new laptop but it has Windows 11 by default, I was able to install Calibre so I don't thing it has that "S" mode enabled but I'll check.

Calibre is in windows store, and not locked.
Some new laptops are delivered in S mode by default

> Update: Just run using W8 compatibility and it worked. Thank you guys!

Glad it worked :)

**Comment by darodi** [comment]
a solution has been found. I'm closing this.

TODO
- create a fundraising for a certificate? 😁
- add more information in the wiki page
