### ISSUE TITLE
Error during conversion list index out of range

### ISSUE THREAD

**Issue by SurajSandhu** [ciromattia/kcc#556]
I was trying to convert the berserk cbz but it keeps showing the same, I tried different sources for the cbz and the one I am using right now has no modifications and is the original. I did the same with Spy x Family from the same source it worked but not for berserk and vagabond. I tried doing it in parts (instead of combining all in one using ComicRack I tried doing in 50 - 70 files and it sill won't work. It works if I convert the chapters individually but not for all-in-one file, the spy x family all in one worked though. Please provide any guidance.
![Screenshot 2023-07-06 151521](https://github.com/ciromattia/kcc/assets/81230543/629d590f-e164-4650-8ca8-9f3843c72c99)

**Comment by axu2** [comment]
@SurajSandhu I've updated #507 it should fix your issue.

If you want to run from source: https://github.com/ciromattia/kcc/wiki/Installation#install-from-sources
