### ISSUE TITLE
Incorrect table of contents if "Rotate and split" is chosen

### ISSUE THREAD

**Issue by vinhtq115** [ciromattia/kcc#558]
It seems that if "Rotate and split" is chosen, the table of contents created with ComicTagger is not adjusted correctly. If there are any double pages before the entry, It is off by a few pages (roughly equal to the number of double pages before that page).

For example:
Example file: `https://we.tl/t-RHYm3amWpH`

Settings I used:
![image](https://github.com/ciromattia/kcc/assets/34190240/e396226e-fbb5-446d-bfb3-ef8846b265ad)

The first three entries in the ToC is correct (since there aren't any double pages between them). But the fourth one is off by 3 pages (should be 74/171 on Kindle instead of 70/171) because there are 3 double pages before the third and fourth entries. Also, idk why Kindle does not show page 72 (only 70-71-73-74) and the number on the ToC is 68 instead of 70.

**Comment by axu2** [comment]
Can you test if #507 fixes it?

**Comment by vinhtq115** [comment]
> Can you test if #507 fixes it?
> 
> Also png doesn't work well with kindlegen you should do jpg to avoid reprocessing. If you really want lossless use gif.

I just tested with #507 and the behavior is still the same.

**Comment by axu2** [comment]
Can you investigate further, I thought it would fix split page bookmark drift since I re-added some logic that was skipped before. 

Look for logic related to kcc-b and kcc-c

**Comment by vinhtq115** [comment]
> Can you investigate further, I thought it would fix split page bookmark drift since I re-added some logic that was skipped before.
> 
> Look for logic related to kcc-b and kcc-c

Sorry, I forgot to checkout that branch. Will recheck immediately.

**Comment by vinhtq115** [comment]
I just tested #507 again with this settings (only changed PNG to JPEG):

![image](https://github.com/ciromattia/kcc/assets/34190240/5c81276d-86be-4958-8cfa-fda7c60d59c5)

Seems like the pages are shuffled. Even the cover is replaced by another page in the manga.

I also tried renaming all the files in the CBZ with 4-digit numbers and now I have this error:

```
list index out of range

Traceback:
  File "kindlecomicconverter/KCC_gui.py", line 293, in run
  File "kindlecomicconverter/comic2ebook.py", line 1177, in makeBook
  File "kindlecomicconverter/comic2ebook.py", line 520, in buildEPUB
```

**Comment by axu2** [comment]
You may need to merge in the apple silicon PR

**Comment by axu2** [comment]
Hmmm maybe the logic that was skipped before regarding kcc-b/c is buggy. I just noticed you attached a sample file so probably can take a look sometime this week. 

Maybe apple silicon PR will help.

**Comment by axu2** [comment]
Can't seem to use that link...

**Comment by axu2** [comment]
@vinhtq115 Please test the current version of the PR, just added a `sorted`

**Comment by vinhtq115** [comment]
> @vinhtq115 Please test the current version of the PR, just added a `sorted`

ToC appears to be fine now. Only managed to test the first entry that is incorrect because the device froze and crashed.

> For some reason, it wasn't iterating in sorted order in the first place.
> 
> Please also test for the index out of range problem.

I tested with CBZ file renamed from `0000.jpg`. Seems like checking the `Disable processing` will make the problem go away (but the result mobi file is about 6MB larger than cbz one, while the intermediate epub is about 200-300 KB larger).

**Comment by vinhtq115** [comment]
File for testing: https://we.tl/t-EMC3t7UgD7

I printed the filenames and filelist variables in `buildEPUB` function. It seems that they only have 48 files. Here is the `filelist`:

```
[('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0000-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0001-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0002-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0003-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0004-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0005-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0006-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0041-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0043-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0044-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0045-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0058-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images', '0062-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0063-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0064-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0083-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0089-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0090-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0091-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0094-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0102-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0103-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0104-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0155-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0165-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0166-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0167-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0180-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0192-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0193-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0194-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0207-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0219-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0220-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0221-kcc-a.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0222-kcc-b.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0223-kcc-c.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0224-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0225-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0226-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0227-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0228-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0229-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0230-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0231-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0232-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0233-kcc.jpg'),
 ('/var/folders/nk/vbrzxwl93h15t3j0kv8bwfbr0000gn/T/KCC-4t1jq94v/OEBPS/Images',  '0234-kcc.jpg')]
```

**Comment by axu2** [comment]
Please try the updated PR. Looks like the bookmark logic was buggy.

I believe the corrupted files issue is an entirely separate issue. @vinhtq115

**Comment by vinhtq115** [comment]
I tested with original CBZ file and the ToC is correct now. For the file that begins with `0000.jpg`, I still got the same exception.

**Comment by axu2** [comment]
Please leave open until merged into master.

Also, can you test the latest PR, I believe it has fixed the 0000 issue as well.

And if you have a moment, review the PR in its entirety.

**Comment by vinhtq115** [comment]
Seems like the error with `0000.jpg` is fixed as well.

Regarding the PR, it looks fine to me.

**Comment by axu2** [comment]
Thanks, and just out of curiosity I was testing this with the Apple Silicon PR merged in on top. Did you do that too?

**Comment by vinhtq115** [comment]
No. I only use `slugify` branch. Is the Apple Silicon branch [this one](https://github.com/axu2/kcc/tree/pyqt6)? I will test it in the morning.

**Comment by axu2** [comment]
Yea, it's #523

**Comment by vinhtq115** [comment]
I tested it and everything worked. Had to remove the .spec file that was generated earlier for the compilation to work because if I don't, it will generate a non-functional binary file (size = 1/2 that of functional one).
