### ISSUE TITLE
Cannot output MOBI file larger than 400MB

### ISSUE THREAD

**Issue by tsopeh** [ciromattia/kcc#563]
I want to convert a manga (larger than 700MB) so I can transfer it to my Kindle Paperwhite. There are the two options for me; I can convert it to MOBI/AZW3 or to EPUB format. If I covert it to MOBI/AZW3, than the output gets split automatically because of the 400MB limitation, and this is something that I would **really** like to avoid. On the other hand, the problem with conversion to EPUB is that it introduces some unavoidable margins, when transferred via Calibre to Kindle, meaning that the content looks smaller than when converted to MOBI/AZW3.

If I understand correctly, "automatic split" was introduced for MOBI/AZW3 due to the limitation of KindleGen. Was this limitation surpassed in the latest KindleGen? Is there a possibility that the "Indeterminate" option can be added for the "Output split" parameter, which would ignore size limitation, and try to create a MOBI file as large as the source data without splitting?

Is there some other way in which I can get large manga packed into a single file that gets displayed fullscreen/without margins?

**Comment by darodi** [comment]
@tsopeh 

> If I understand correctly, "automatic split" was introduced for MOBI/AZW3 due to the limitation of KindleGen. Was this limitation surpassed in the latest KindleGen?

Same limitation in the latest `KindleGen`. 
As said [here [KindleGen]](https://www.amazon.com/b?node=23972728011)

>KindleGen is no longer available for download. Please use Kindle Previewer to convert, preview, and validate your eBooks. Kindle Previewer provides the same functionality of KindleGen

`KindleGen` is now found a sub directory of `Kindle Previewer`, but might disappear in the future.
So it won't be updated.

Kindles partitions are FAT32 and have a limit of 4GiB  (4.294 GB)

**Comment by tsopeh** [comment]
Hi @darodi, thanks for the reply and explanation.
