### ISSUE TITLE
MacOS app is told that it is damaged

### ISSUE THREAD

**Issue by killam42** [ciromattia/kcc#569]
<img width="259" alt="Screenshot 2023-08-01 at 9 40 02 PM" src="https://github.com/ciromattia/kcc/assets/48464668/26be8296-3c6d-4bf6-9c75-4e4f2e63835d">

**Comment by axu2** [comment]
Known issue, please use this version instead: https://github.com/axu2/kcc/actions/runs/5709825357

You may need to right click open if you are on Apple Silicon.

**Comment by killam42** [comment]
Thanks it did work and now I'm having another error pop up "Failed to extract archive. Check if p7zip-rar is installed" and I've checked and reinstall through brew several times already

**Comment by axu2** [comment]
Are you using rar or cbr?

7zip on Mac hates certain rar cbr. 

Use unarchiver app to extract them first outside of kcc

**Comment by killam42** [comment]
Yes I'm using CBR, going to try converting it to CBZ

**Comment by axu2** [comment]
Did you get it working? Added a link to unarchiver.
Just extract the CBR and drag the extracted folder into KCC.

**Comment by killam42** [comment]
Yes I did thanks for the link

**Comment by axu2** [comment]
If you feel brave try running from source and adding support for `unar` which you can install via `brew instal unar`.

#267
