### ISSUE TITLE
KCC Folder

### ISSUE THREAD

**Issue by pokhrelapar** [ciromattia/kcc#573]
Hello. 
This installation wiki says:

Move kindlegen.exe from Kindle Previewer into the same folder as KCC.

But when I download the installer, I don't see the folder. It's just the KCC app that opens. Where is the KCC folder?

For reference I am on windows and ran this installer. 
https://github.com/ciromattia/kcc/releases/download/v5.6.2/kcc_5.6.2.exe

**Comment by axu2** [comment]
Updated the wiki, let me know if it works: https://github.com/ciromattia/kcc/wiki/Installation#windows-1

Also please try 5.6.3
