### ISSUE TITLE
kcc.exe missing? 

### ISSUE THREAD

**Issue by erbazzone** [ciromattia/kcc#576]
Hi, I might be very nooby in installing programs and using github, but I'm wondering if there's a reason why I see no kcc.exe inside my kcc-master folder. Am I downloading the wrong folder? I'm using Windows 10.
Thank you!
![Cattura2](https://github.com/ciromattia/kcc/assets/141845465/f44e7bbc-45e7-4133-92f1-51c7077c8d3c)

**Comment by darodi** [comment]
You don't need to clone the repository or download master, except if you plan to run it from source.

On the first page: https://github.com/ciromattia/kcc#downloads

![image](https://github.com/ciromattia/kcc/assets/4682830/6381450e-d3be-483a-a8c3-9e90745308c6)


follow https://github.com/ciromattia/kcc/releases

![image](https://github.com/ciromattia/kcc/assets/4682830/a566e22c-d900-40a5-aca1-37b99320cb00)
