### ISSUE TITLE
v5.6.3 broken on Windows | Failed to execute script kcc

### ISSUE THREAD

**Issue by axu2** [ciromattia/kcc#578]
Just noticed that the Windows build is broken...

![image](https://github.com/ciromattia/kcc/assets/20757319/24917d06-14c2-4b3f-b3e2-4e69960422ca)

When I try to build it myself using the **disabled** `windows` workflow it works fine though: **https://github.com/axu2/kcc/actions/runs/5835174394**

I think it must be an issue with the `windows-docker` workflow which also creates the CLI versions. (As an aside, multiple EXE with similar names might be confusing for average user, should at least add `win` to filename.)

**Comment by lohtse** [comment]
I have the same error on windows 10 22h2  all previous versions work without this error

**Comment by axu2** [comment]
When I try to build it myself using the disabled `build KCC for windows` workflow it works fine though: https://github.com/axu2/kcc/actions/runs/5835174394

**Comment by DavidNSB** [comment]
I'm seeing the same issue with Windows 11.

**Comment by darodi** [comment]
OK I found why.
The minimum version in the code has been set to python 3.8
and that github action 
works with python by default 3.7

see. 
https://github.com/JackMcKew/pyinstaller-action-windows/tree/main#python-310

I'm rebuilding
