### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Tamamaster** [ciromattia/kcc#582]
Hey guys,

Got an issue with 5.6.3 that i thought has been resolved. My issue links with #556  where i get the list 'index out of range'.

I saw that this issue was linked to #507 which is now closed. I do use ComicRack to combine the files into one large book. 

![Screenshot-2023-08-14-165430](https://github.com/ciromattia/kcc/assets/142300048/d4fa52d6-0a92-4a47-a30e-91286753dea4)

Test file: https://www.dropbox.com/scl/fi/rvapeciwd71s86dtdf251/Gantz-1-5.cbz?rlkey=9o1peile4b7gjbbbql08l6m4j&dl=0

**Comment by axu2** [comment]
Unable to replicate, what settings are you using?

Please try redownloading latest release.
 
![image](https://github.com/ciromattia/kcc/assets/20757319/4b49de0e-a771-4611-85e0-2114517a4da2)

**Comment by Tamamaster** [comment]
Hey @axu2 

I've was on the newer 5.6.3 but re-downloaded just for in case.
I'm still getting the same issue with the settings as per the image below. 
Normally i would convert to MOBI/AZW3 then bring it over to Calibre to add to my kindle.
Making the output as EPUB does work on my end, it just causes some issues for me when using Calibre to convert (file doesnt show up on my device (was fixed when i broke it down to smaller size e.g volume 1-15) and manga mode doesnt work)

![Screenshot 2023-08-24 221806](https://github.com/ciromattia/kcc/assets/142300048/86a1c0dd-baef-4f1d-8d48-50fbb558b85b)

**Comment by axu2** [comment]
In the meantime is there anything stopping you from creating folders with sub folders for each chapter and using those folders directly in KCC?

You bc an also transfer the MOBI directly via usb not just through calibre. Covers get uploaded on Kindle Scribe if you convert while it's plugged in.

**Comment by axu2** [comment]
Pretty sure this has to do with Kindlegen filesize autosplit conflicting with comicrack bookmarks.

**Comment by Tamamaster** [comment]
Deleting the ComicInfo.xml works and allows for KCC convert CBZ to MOBI successfully (splitting into 4 parts).
It does seem like a size limitation issue as when turning off 'stretch/upscale' would work on the smaller size files (volume 1-5) but will not work on larger ones (volumes 1-15).

Sorry this is a more quality of life issue than anything. As I just wanted KCC to work on larger files to save navigating chapters in kindle. Since you've found a temp solution, I'm more than happy to close off this issue if you are.

Thank you for all your time and support. I really do appreciate it!

**Comment by axu2** [comment]
We should keep this open until a fix is merged.

**Comment by axu2** [comment]
@Tamamaster Can you test if the prebuilt version provided in #620 fixes your issue?

**Comment by axu2** [comment]
@Tamamaster Thank you for the test file! I think I solved it.
