### ISSUE TITLE
What's c2e and c2p? What to use?

### ISSUE THREAD

**Issue by lucasfcnunes** [ciromattia/kcc#584]
https://github.com/ciromattia/kcc/releases/tag/v5.6.2

![image](https://github.com/ciromattia/kcc/assets/29926675/294818cb-fc03-40c7-aa92-53f41b8dd8a9)

**Comment by darodi** [comment]
kcc is GUI (graphical user interface) version
kcc-c2e CLI (command line) version
kcc-c2p CLI (command line) version

https://github.com/ciromattia/kcc#usage
> CLI version of KCC is intended for power users.
