### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by DemonEye888** [ciromattia/kcc#586]
had this issue while using kcc 5.6.2
![image](https://github.com/ciromattia/kcc/assets/144113040/5a26fc90-4043-4d94-9bbc-4ee5fe10b925)
![image](https://github.com/ciromattia/kcc/assets/144113040/af763b6e-3c2b-4156-b30a-318aa60aee02)

**Comment by axu2** [comment]
Please try v5.6.3 and reference #582

**Comment by DemonEye888** [comment]
I tried downloading v5.6.3. but when I open it this error message pops up
![image](https://github.com/ciromattia/kcc/assets/144113040/5f3aa5e0-2735-47cd-b336-51db625bbcc4)

**Comment by axu2** [comment]
Interesting, possibly a docker issue. 

Please try the non docker version linked in #578

**Comment by DemonEye888** [comment]
yea I am not using c2e or c2p

**Comment by axu2** [comment]
Please try the non docker version: https://github.com/axu2/kcc/actions/runs/5835174394

**Comment by DemonEye888** [comment]
I tried, but there is still the same error message

**Comment by axu2** [comment]
Are you talking about original `index of out range error` or `exit` error?

**Comment by DemonEye888** [comment]
I tried the no docker version for "the exit not defined error" but it still didnt work (as in i can't open 5.6.3.)

the solution for "the index of out range error" is to delete the ComicInfo.xml file. But where do I find this file?

**Comment by axu2** [comment]
Did you use ComicRack to combine images?

Options are:

1) Disable upscale (won't work on really large files)
2) don't use ComicRack, convert volumes individually
3) unzip the ComicRack CBZ and delete the ComicInfo.xml. This will cause splitting around ~350 MB
4) create a folder and unzip the volumes into the folder, use that folder in KCC

A CBZ is just a renamed ZIP file, you can use 7zip to unzip.

**Comment by DemonEye888** [comment]
yes I did use comicrack.

I did combine all 308 chapters of Diamond no Ace II into one, so the file was over 2 GB big.
I think the size itself wasn't the issue because I converted volumes, that were over 1 GB big in the past.
My solution is to keep the combined comicrack-file of chapters under 350 MB. If I do that, it converts them just like normal.

I also can't really convert this manga individually because I downloaded all chapters individually.

Thansk for the help.

**Comment by axu2** [comment]
You can try combing the file manually by just unzipping the chapters into a new folder. No comicrack needed. Then it shouldn't require you to manually split.

**Comment by axu2** [comment]
Mind opening a separate issue for the exit error?

**Comment by axu2** [comment]
@DemonEye888 Can you test if the prebuilt version in #620 fixes your issue?

**Comment by axu2** [comment]
@DemonEye888 I believe I've fixed it now. Please test when you can to confirm in #620
