### ISSUE TITLE
Conversion Issue: Pages out of order

### ISSUE THREAD

**Issue by n3nuzzzz** [ciromattia/kcc#587]
Hi I'm new to KCC and I tried to use it to convert a volume of One Piece that I wanted to upload to the kindle, however, despite the fact that I created a special folder for the volume and put inside the chapter folders, when I go to convert it I get a mobi file with all the messy pages.
(I tried to convert the folder with both a directory and the .zip format of it but it always gives me the same problem)
I hope you can help me!  (I use KCC 5.6.3)
<img width="104" alt="Screenshot 2023-09-07 alle 20 27 50" src="https://github.com/ciromattia/kcc/assets/144380354/c30d3ec9-4c2e-4472-8fe3-c648d2b1b49d">
<img width="216" alt="Screenshot 2023-09-07 alle 20 27 55" src="https://github.com/ciromattia/kcc/assets/144380354/2782253e-1f34-410c-be38-10e79ac9361d">
<img width="192" alt="Screenshot 2023-09-07 alle 20 28 04" src="https://github.com/ciromattia/kcc/assets/144380354/ceeef6b2-b09d-4e52-97bb-8e455eaee067">

**Comment by axu2** [comment]
What do you mean by messy?

**Comment by n3nuzzzz** [comment]
> What do you mean by messy?
> I mean that if I start to read the first chapter the first page it may be okay but the others have a different order and I can't read them
> Upload an image of your kcc settings

<img width="515" alt="Screenshot 2023-09-08 alle 12 11 51" src="https://github.com/ciromattia/kcc/assets/144380354/c7ef93d0-78aa-4588-baa6-470660872d27">

**Comment by n3nuzzzz** [comment]
> I've the same error, when I try to convert a pdf to mobi, the mobi file have a wrong index of the pages. example normal reader---> pag1->pag2->pag3-pag4->pag5 actual issue-----> pag1->pag30->pag31->pag2->pag3 I try to convert the same pdf with the version 5.6.2 and I don't have this issue

I don't have a pdf file I have those folders that I mentioned in the first post but I'll try to download the 5.6.2 version of kcc

**Comment by vincenzo1993** [comment]
@n3nuzzzz let me know if you solve

**Comment by n3nuzzzz** [comment]
@vincenzo1993 ok I tried downloading the 5.6.2 but I can't even open it.
It says that the file is damaged and it can't be opened (I have a mac, of course I downloaded the macos file)

**Comment by vincenzo1993** [comment]
@n3nuzzzz I use windows so I don't know why the program 5.6.2 don't start.

**Comment by n3nuzzzz** [comment]
@vincenzo1993 so I MAYBE found the issue with the folders... I need to number all the pages with different numbers and removing the gap between the letters and the numbers.
It's not the best solution but it works in this way... idk how I'll manage to number all the pages in One Piece but that's it I think

**Comment by axu2** [comment]
Please try this build that uses natural sort:

Windows: https://github.com/axu2/kcc/actions/runs/6123144358
Mac: https://github.com/axu2/kcc/actions/runs/6123143150

**Comment by n3nuzzzz** [comment]
How should I build it?

**Comment by n3nuzzzz** [comment]
YOU SAVED ME @axu2 
It works!!

**Comment by axu2** [comment]
@n3nuzzzz Consider using manga mode and mozJpeg mode. Also considering installing from source since Apple Silicon native python is twice as fast for the conversion step.

**Comment by axu2** [comment]
@n3nuzzzz Also please change the title to something like "Pages out of order" or similar to make it easier for others to find.

**Comment by axu2** [comment]
@n3nuzzzz don't close issues until fixes are officially merged in a PR
