### ISSUE TITLE
Exit error

### ISSUE THREAD

**Issue by DemonEye888** [ciromattia/kcc#588]
I ran into this error message after I tried opening kcc version 5.6.3.

I use windows 10 and the issue is not my antivirus-software, because I already tried downloading and opening it with the software disabled.

I also tried the non-docker version but it still didn't work.

![image](https://github.com/ciromattia/kcc/assets/144113040/6acc2f81-381c-4ab9-9fc7-fa5a4a2450a5)

**Comment by axu2** [comment]
What folder are you running KCC from? Try running it from the desktop.

**Comment by axu2** [comment]
Can you try running:

Temporary EXE here: https://github.com/axu2/kcc/actions/runs/6125895319

Also, try running the exe from multiple locations (Downloads, Desktop, etc) and tell me if any locations cause problems.
