### ISSUE TITLE
Images showing up in wrong order

### ISSUE THREAD

**Issue by ziaa-xyz** [ciromattia/kcc#595]
Title. Images from a zip and pdf are either skipped or put in the wrong order. Small chapters work fine but volumes of manga don't work right. This would be fine if I could merge .mobi files insome way but i can't find anything online

**Comment by axu2** [comment]
Please try this build that uses natural sort instead of python sort:

Windows EXE: https://github.com/axu2/kcc/actions/runs/6123144358
Mac DMG: https://github.com/axu2/kcc/actions/runs/6123143150

@n3nuzzzz
