### ISSUE TITLE
Error converting zip file

### ISSUE THREAD

**Issue by snape2019** [ciromattia/kcc#596]
Latest version 5.6.X kcc can't convert my zip to epub, reporting unsupported archive format. This did not happen with the old version 5.4.X.

**Comment by axu2** [comment]
This is a surprisingly common issue, can you elaborate the solution?

**Comment by snape2019** [comment]
Someone mentioned this issue and seems to be experiencing a similar problem. After I raised the issue at the time, I looked at the wiki and found that it could be resolved, so I just closed the issue. Specifically, I looked at this https://github.com/ciromattia/kcc/wiki/Installation#mac , and viewed through brew that the program installed on September 16th was indeed this one. An unzipped program was installed and no errors have been reported since.
