### ISSUE TITLE
Compatibility Note: Kindle 4 Successfully Uses "Kindle Keyboard" Setting

### ISSUE THREAD

**Issue by panostsl** [ciromattia/kcc#597]
Hello,

I wanted to share a helpful note regarding device compatibility for users of the Kindle 4 model. The software does not explicitly list Kindle 4 under the 'Select Target Device' options. However, after some experimentation, I found that choosing the 'Kindle Keyboard' setting works flawlessly for the Kindle 4.

It might be beneficial to other users if this information could be added to the documentation or as a tooltip in the software.

Thank you for developing this excellent tool!

**Comment by axu2** [comment]
That's a great idea, our labels aren't actually the best.

Feel free to edit the labels yourself and send in a PR! 

https://github.com/ciromattia/kcc/blob/master/kindlecomicconverter/image.py#L86

**Comment by axu2** [comment]
Turns out the Keyboard, Touch, and plain Kindle profiles are all identical. Gonna just update the labels. @panostsl
