### ISSUE TITLE
Hay soporte para el  kindle 2022

### ISSUE THREAD

**Issue by YtAdr** [ciromattia/kcc#599]
Dentro de poco me va a llegar el  kindle 2022 que es el ultimo que se puso a la venta, al instalar el programa salen las siguientes opciones :  Kindle ,  kindle1,  kindle2. Me gustaría saber cual es su versión ya que el ultimo modelo tiene mas resolución 300ppp por lo que no quiero ver los mangas a peor resolución.  Cual opción es para el ultimo modelo? Muchas gracias.

**Comment by axu2** [comment]
https://github.com/ciromattia/kcc/blob/master/kindlecomicconverter/image.py#L86

Kindle 11

Make sure to use latest version, right now that is v5.6.3

![image](https://github.com/ciromattia/kcc/assets/20757319/edb847e5-0e7d-4608-894c-58c0757c5c0e)

**Comment by YtAdr** [comment]
Muchísimas gracias por aclararme la duda.

**Comment by axu2** [comment]
Renamed Kindle profile to 4/5/7/8/10
