### ISSUE TITLE
windows 11

### ISSUE THREAD

**Issue by shubhamrana07676** [ciromattia/kcc#600]
it isnt working on my win 11 pc it opens a terminal for a second and closes i have tried running in compatibilty mode with win 8 but it doesnt work

**Comment by axu2** [comment]
Where is the kcc.exe? Try running it from desktop. 

Make sure you aren't using the c2p or c2e versions, those are cli versions.

**Comment by shubhamrana07676** [comment]
Thanks my issue was fixed sorry for concerning for such a small issue

**Comment by darodi** [comment]
closing this, it is fixed
