### ISSUE TITLE
Error page between each page on the random part

### ISSUE THREAD

**Issue by 666diabolus** [ciromattia/kcc#601]
Hi, since the manga I try to convert is too big for a whole *cbz, I try to use the *.epub 200mb split format, copy to my device (Boox Leaf 2) and try to read it. There's a random part that show the error sign (something like below) between each pages (says that it split into 10 part and the error could appear in part 2, 5, 7, 8, or 1,2,4,9, it just random parts)
 I already check the source and it's on the right folder format.

My Settings : 
KCC 5.6.3 natural sort
Device : Kindle Oasis 2/3
Type : EPUB (200MB limit)
Manga Mode Checked
Indeterminate JPEG/PNG/mozJpeg (already tried the checked and unchecked, still happening)
Stretch/Upscale Checked

![3-39218_big-image-no-entry-sign-black-and-white](https://github.com/ciromattia/kcc/assets/57742957/69718474-482d-4101-8940-a6f1f554321e)

**Comment by axu2** [comment]
What is the format (cbz/pdf/etc) of your source? How big and how many pages?

**Comment by 666diabolus** [comment]
> What is the format (cbz/pdf/etc) of your source? How big and how many pages?
> 
> Try the normal epub format.
> 
> If you unzip the KCC generated epub on a PC what do you see? Maybe the KCC generated epub has an issue with boox software. Also try a pc epub reader.

My Source are JPEG, around 14k pages, ~3GB
The normal epub format always push it to 6GB (despite jpeg or png), which cannot run on my Boox or any e-reader I guess :(
When I unzip it on PC, it work just fine without any traces of that error page.

**Comment by axu2** [comment]
What's the issue with CBZ output?

Maybe try a non Kindle device profile. Or custom profile. There are some differences with kindle epub generation.

**Comment by 666diabolus** [comment]
> What's the issue with CBZ output?
> 
> Maybe try a non Kindle device profile. Or custom profile. There are some differences with kindle epub generation.
> 
> Maybe uncheck upscale.

The only problem with the CBZ is that the file size is too big, double in size compare with the original. I wish it had a split options.
Lemme try other profiles and I'll let you know.

**Comment by axu2** [comment]
also try v5.6.2 if you still have issues.

**Comment by axu2** [comment]
Someone had a similar issue, please use the custom profile with your device resolution.
