### ISSUE TITLE
Splitting up manga files

### ISSUE THREAD

**Issue by RaymondRed** [ciromattia/kcc#602]
KCC splits up the size of the manga and there isn't an option to turn it off either kind of annoying since I'm a bing reader and i spend time till 4 in the morning trying to fix this

**Comment by axu2** [comment]
Duplicate #563

**Comment by RaymondRed** [comment]
Hi @axu2 . I saw the explanation you referred to but I wasn't able to understand. So is there no way to make it not split up the manga I convert

**Comment by axu2** [comment]
There is no way to avoid the split using KCC.
