### ISSUE TITLE
Feature Request - Option to disable Panel View in MOBI+EPUB and MOBI/AZW3

### ISSUE THREAD

**Issue by UPSA007** [ciromattia/kcc#603]
I really appreciate EPUB (Calibre KFX) output format but can you please add an option to disable Panel View completely in MOBI+EPUB and MOBI/AZW3 because sometimes while reading it triggers due to accidental touch. It will be nice if there was an option to disable this feature in those modes completely. 
Thanks in Advance :-)

**Comment by axu2** [comment]
Disabling it has some issues. https://github.com/ciromattia/kcc/pull/499#issuecomment-1500921345

**Comment by axu2** [comment]
@UPSA007 Should be fixed in above PR, please use the linked test build.
