### ISSUE TITLE
Filename problem if contain "." in Kobo profiles

### ISSUE THREAD

**Issue by vietvu94** [ciromattia/kcc#615]
If a file name input contains the character "." , all characters after that will be skipped in the output file. 
For example: "Vol.01 Ch.001 - Shinmen Takezo.cbz" will be named "Vol.kepub.epub".

Organizing files is super difficult.  Renaming the origin files to not include "." is impossible because the number of chapters can be easily 300.

**Comment by axu2** [comment]
Related #613
