### ISSUE TITLE
Why does KCC change my metadata after I convert the file?

### ISSUE THREAD

**Issue by bbeam23** [ciromattia/kcc#617]
Just edited every metadata in Calibre nice and tight. Then converted my finished files from CBZ to EPUB in KCC so I could upload to my Kinder. Boom! The author of every book changed to KCC for some reason. What's this?

**Comment by axu2** [comment]
This is how kcc handles metadata : https://github.com/ciromattia/kcc/wiki/ComicRack-metadata
