### ISSUE TITLE
[Feature Request] Option to disable rescaling

### ISSUE THREAD

**Issue by ssokolow** [ciromattia/kcc#622]
I was directed at KCC as the solution for "Calibre converting manga scanned as two-page spreads results in split pages with 2 1 4 3 6 5 page ordering".

All I want to do is convert CBZ to EPUB so I can load the things in the stock Books app on my hand-me-down iPhone (I refuse to create an Apple account and it's needed to install other apps).

I don't want to crop, resize, or do any kind of reprocessing *other* than producing split pages in the correct reading order.

Every other feature has a checkbox, but there's no apparent way to NOT specify a target file size except possibly approximating it by selecting Other and then keying in half the source file width as the custom width and the original source file height as the custom height.

Given that I don't intend to be doing this very often, the scans in question are well-centered and consistent, and it's more enjoyable to hack up a quick Python+Pillow script than to manually check the dimensions of the input files on all my source archives, I'm probably going to write a quick script of my own to to split the files right down the middle and generate a new CBZ I can drop into Calibre to perform the EPUB conversion, but I can't imagine that everyone who wants to do this knows how to program.

**Comment by axu2** [comment]
Just select CBZ output, a resolution that definitely way bigger than your source, and uncheck upscale and work from there.

**Comment by ssokolow** [comment]
> Just select CBZ output, a resolution that definitely way bigger than your source, select split pages, and uncheck upscale and work from there to get a split cbz of original resolution images.

Ahh. Not very obvious, but makes sense in hindsight... but I posted that on the assumption that nobody would respond quickly enough to meet my needs so I immediately started writing the aforementioned script.

https://gist.github.com/ssokolow/c2e24fd3ae7f1bf83b601156c20e6c69

Heck, a non-trivial amount of that time was waiting for Calibre to convert, and for the phone to download it from my copy of [miniserve](https://github.com/svenstaro/miniserve/) over WiFi that's overdue for an upgrade.

> I'm not sure how good calibre is at creating fixed layout comics.

For how I use it, not too bad.

That said, I noticed it also looks a little squashed and not as zoomed in as I'd like so, since I'm not a Calibre expert and tend to read via infinite scrolling anyway, I think I'll just extend the "rip it out and write my own" one step further and extend the script to write an `.html` file to turn the Safari preview in the files app into an infinite-scrolling reader so I can just copy the `.zip` over to the phone, tap it to unpack, and then open the HTML file, similar to what I do with fanfiction I've "offline reader mode"'d.

**Comment by ssokolow** [comment]
I was quickly reminded that the Files app doesn't allow external subresources so here's a script that converts a `.cbz` file full of two-page spreads into an `.html` file full of single-page `data:` URIs instead.

https://gist.github.com/ssokolow/482f9277251c7fdbd907c2711109f050

It works surprisingly well when I use it to convert ~40MiB `.cbz` files into ~55MiB HTML files. Mobile Safari's loading spinner takes maybe 1.7 seconds to go away.
