### ISSUE TITLE
Disable processing checkbox creates blank pages

### ISSUE THREAD

**Issue by saikoyama** [ciromattia/kcc#626]
I'm using a Kindle Scribe, and I'm using the disable processing checkbox to try to reduce the moiré pattern from screentones on certain manga pages. Although it does help, It takes a long time to complete, and the final output has missing blank pages.

**Comment by axu2** [comment]
KindleGen max resolution height is 1920. If you provide larger images and disable kcc rescaling, kindlegen will rescale instead VERY SLOWLY and may introduce other issues. 

If you don't disable processing is it fine?

**Comment by saikoyama** [comment]
@axu2 I need to experiment with this more. It's unfortunate that there isn't a one size fits all when it comes to having manga on an E-reader. Screentones look great on paper, but terrible on displays. The increased display resolution on the Kindle Scribe doesn't seem to help hide these issues. I'm going to play around with upscalers and see if I can get the image looking okay without the moiré pattern showing up.

If Kindlegen's max height resolution is 1920, does that mean any comic loaded onto the Kindle Scribe is going to be stretched from a lower resolution? If so, that is pretty frustrating. Hope these issues are figured out. If not, there's still time for me to return this thing if needed.

I hope there will be a way to sideload custom software specifically made for the scribe that has better comic support and better note/drawing tools.

**Comment by axu2** [comment]
There are some projects that use a reverse engineered kindlegen without the 1920 restriction. It's mentioned in #460. Specifically a go library called mobi. Feel free to experiment. It lacks gamma correction though and other kcc features. I think the projects are called kojirou or mapaki.

**Comment by saikoyama** [comment]
@axu2 I will have to look it up. It will be a bit of a process, but at least it's there if I want to view manga on my device at the highest quality. Source resolution is 3300x4500, so there will still be downscaling involved. Not even a 4k monitor has enough pixels, and an 8k monitor would be overkill.

**Comment by axu2** [comment]
@saikoyama 

The projects I mentioned are:
https://github.com/leotaku/kojirou
https://github.com/tsopeh/mapaki

They both use the go library:
https://github.com/leotaku/mobi

Feel free to experiment and report your results on image quality/sharpness/file size.

An idea could be using KCC Scribe profile but select CBZ output to resize to 2480 height. And use that CBZ in the other projects to make a MOBI.
