### ISSUE TITLE
[WinError 5] Access is denied 'C\\Users\\ ~

### ISSUE THREAD

**Issue by ainiaian** [ciromattia/kcc#630]
Can you please help me how to solve this? Thank you!
![image](https://github.com/ciromattia/kcc/assets/102847539/f1abc87e-d7ab-434b-9caf-3389cf82a72b)

**Comment by axu2** [comment]
Can you try this version? https://github.com/axu2/kcc/releases/tag/v5.6.3.1

**Comment by ainiaian** [comment]
> Can you try this version? https://github.com/axu2/kcc/releases/tag/v5.6.3.1
> 
> Maybe try disabling your antivirus?

Tried that version still the same. Also turned off windows defender. and tried to run in Administrator and still the same error.

**Comment by axu2** [comment]
Does pc restart help?

**Comment by ainiaian** [comment]
> Does pc restart help?
> 
> Is the problem with this specific file or anything you try to convert?

Tried that last night too. Yes. Every file I try converting will show that error.

**Comment by axu2** [comment]
I've figured it out, it's due to the file structure. 

Please Unzip the CBZ first

**Comment by ainiaian** [comment]
> Try extracting the CBZ using 7z and using the folder directly in KCC.

That worked. Thank you! :)

**Comment by axu2** [comment]
The code that throws this error is at 

```python
        if len(tdir) == 1 and os.path.isdir(os.path.join(targetdir, tdir[0])):
            for f in os.listdir(os.path.join(targetdir, tdir[0])):
                move(os.path.join(targetdir, tdir[0], f), targetdir)
            os.rmdir(os.path.join(targetdir, tdir[0]))
```

if anyone wants to take a crack at it.

**Comment by ainiaian** [comment]
> The code that throws this error is at
> 
> ```python
>         if len(tdir) == 1 and os.path.isdir(os.path.join(targetdir, tdir[0])):
>             for f in os.listdir(os.path.join(targetdir, tdir[0])):
>                 move(os.path.join(targetdir, tdir[0], f), targetdir)
>             os.rmdir(os.path.join(targetdir, tdir[0]))
> ```
> 
> if anyone wants to take a crack at it. It might be as simple as just deleting that code section if the plain folder method doesn't cause issues.
> 
> @ainiaian Please report if all the files created using extracted folders work fine.

Yes it works fine. Both epub and mobi.
