### ISSUE TITLE
Releases after 5.6.2 doesn't work on Windows 11 23H2 (22631.2792)

### ISSUE THREAD

**Issue by Trild** [ciromattia/kcc#637]
**Describe the bug**
Traceback (most recent call last):
  File "kcc.py", line 74, in <module>
  File "kindlecomicconverter\startup.py", line 39, in start
  File "kindlecomicconverter\KCC_gui.py", line 1050, in __init__
  File "kindlecomicconverter\KCC_gui.py", line 859, in detectKindleGen
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 8: invalid start byte

**To Reproduce**
1. Just open a kcc

**Screenshots**
![изображение_2023-12-07_134617959](https://github.com/ciromattia/kcc/assets/16444806/2d1fdb6a-eb4f-450f-8373-87b5aa613e36)
![изображение_2023-12-07_134705558](https://github.com/ciromattia/kcc/assets/16444806/f1a7de40-4076-4a37-9f1f-a61f57d486fb)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by axu2** [comment]
Can you try this build?
https://github.com/axu2/kcc/actions/runs/7131246925

If it still doesn't work, I'll have to change the `encoding='UTF-8'` to `text=True`.

(Which is the same as setting `encoding=ANSI` on Windows.

**Comment by Trild** [comment]
@axu2 it works but i get a new one
first one: when i click "Editor"
![изображение_2023-12-07_195146039](https://github.com/ciromattia/kcc/assets/16444806/b9a648dd-bf05-42ca-8646-12c6f330ea6b)
second one: when i try to convert
![изображение_2023-12-07_195210254](https://github.com/ciromattia/kcc/assets/16444806/3d5b542d-62e3-4564-8def-322772480e85)

**Comment by axu2** [comment]
Why did you delete Windows Updates? @Trild

**Comment by Trild** [comment]
@axu2 it works good without any bugs or errors
thx

**Comment by axu2** [comment]
@Trild can you upload a test file to see if I can reproduce? It might be file specific.

**Comment by axu2** [comment]
@Trild 
Can you please test this build as well, I believe I've done the proper fix now:
https://github.com/axu2/kcc/actions/runs/7136762489

**Comment by Trild** [comment]
@axu2 It starts, but the Editor does not work
![image](https://github.com/ciromattia/kcc/assets/16444806/53ff1b45-62b3-4b67-b428-6d1de5f722ff)
And the convertation doesn't work
![image](https://github.com/ciromattia/kcc/assets/16444806/7431cba9-0a70-472a-85ea-b44a5e497c9e)

**Comment by axu2** [comment]
@Trild OK, maybe it was a bad idea to encode the output of 7z with utf-8. I'll just leave it in binary. Please try this:
https://github.com/axu2/kcc/actions/runs/7154194942

**Comment by Trild** [comment]
@axu2 now everything works without errors

**Comment by axu2** [comment]
@Trild Where did you get 7z? I just tried with 7z 23.01 from the website.

**Comment by Trild** [comment]
@axu2 from the website (https: //www.7-zip .org/a/7z2301 -x64.exe)

**Comment by axu2** [comment]
Alright, so then there must be non utf8 characters inside the cbz, whether it's the file or folder names. 

Thanks for the help debugging!

**Comment by axu2** [comment]
This fix is now released: https://github.com/ciromattia/kcc/releases/tag/v5.6.5
