### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by Ozhun** [ciromattia/kcc#648]
**Describe the bug**
I can't launch the latest version because I get the error you see on the screenshot.

**Screenshots**
![Error KCC](https://github.com/ciromattia/kcc/assets/154545507/c0d91268-564c-4c2f-8c6e-c0ccbae9bc7c)

**Desktop (please complete the following information):**
 - I am using windows 11

**Additional context**
I am currently using a 5.5.2 version that I downloaded from a youtube video, including Kindlegen and 7zip, and it works perfectly fine, I tried reinstalling 7zip, kindlegen, putting the 5.6.4 version on the same folder and it doesn't work, I still get the same error.

**Comment by axu2** [comment]
Please try this version (may take a few minutes for the EXE to show up) 
https://github.com/ciromattia/kcc/releases/tag/v5.6.5

**Comment by Ozhun** [comment]
The 5.6.5 version works perfectly fine, thx.

I'm using the spanish version of W11.

**Comment by axu2** [comment]
Thanks for confirming, seems to have been a change in non English windows 11

**Comment by axu2** [comment]
@Ozhun I just re-released v5.6.5 with a few more bugfixes please try it and report back.

**Comment by Ozhun** [comment]
Still working as it should, no error/bugs to report.
