### ISSUE TITLE
Landscape reading loses alignment after spreads when reading non-manga

### ISSUE THREAD

**Issue by e1ker** [ciromattia/kcc#650]
When reading on Kindle with two-page spreads, rotating or no rotating, causes the pages after to become misaligned since the spread counts as 1 location(page) on Kindle instead of the 2 it would count on a physical copy. Can we have the option to duplicate the spread or add a blank page after it so this doesn't happen?

**Comment by axu2** [comment]
@e1ker are you using the latest v5.6.5?

**Comment by e1ker** [comment]
> @e1ker are you using the latest v5.6.5?

When this specific manga was converted it was with v5.6.4, but I didn't see anything on the changelog for v5.6.5 that would fix it

**Comment by axu2** [comment]
Can you upload pictures of the issue? I can't understand what is being misaligned after a spread.

**Comment by e1ker** [comment]
I use the rotate and split option with a full checkmark, which I think should do both? When using portrait it is a single rotated page as I expected but when in landscape it is just a single rotated page with another page next to it. Also, if I rotated AND split, would that make the picture not work properly in portrait and show as 2 pages instead? I'm a bit confused about how the option works

**Comment by axu2** [comment]
@e1ker try the option only partially checked and see if it does what you want.

**Comment by axu2** [comment]
@e1ker Finally got to my PC, do it like this:

![image](https://github.com/ciromattia/kcc/assets/20757319/2bee549d-e136-45de-ac05-88d9300f9027)

**Comment by e1ker** [comment]
A problem exists with rotate and split in which some comics in landscape show one singular page after a splitted spread, misaligning again the pages

**Comment by axu2** [comment]
Can you show an example picture of a comic in landscape only showing a singular page after a split spread using the partially checked option?

**Comment by e1ker** [comment]
![IMG_20231226_164131](https://github.com/ciromattia/kcc/assets/43532041/695ca8ce-f663-4abf-a5f3-d774819933ba)
This is the page shown as a single. Following it are these pages:
![IMG_20231226_164142](https://github.com/ciromattia/kcc/assets/43532041/c6206245-49d3-478f-84ab-20ebec3f78a1)
Note that the white margins are looking to the outside, while the proper way should be looking to the inside

**Comment by axu2** [comment]
What's the page right before the single page?

**Comment by e1ker** [comment]
> What's the page right before the single page?

This spread:
![IMG_20231226_184126](https://github.com/ciromattia/kcc/assets/43532041/6b54f8d5-30fe-44df-9c53-3077fb4698bd)
Here it is rotated.

![IMG_20231226_184135](https://github.com/ciromattia/kcc/assets/43532041/fe803ab1-f9df-4f05-9ca4-d678caed40ad)
After that is a split spread (these are 2 pages but shown together since it's in landscape)

![IMG_20231226_184211](https://github.com/ciromattia/kcc/assets/43532041/0bc6dffe-8ba5-4ac5-8e24-18084d9be31e)
This is how the last page of the spread appears in portrait. That's expected behaviour since it's a split.

**Comment by axu2** [comment]
Thank you for the information, I've replicated it. Can you send a screenshot of your KCC settings? I want to confirm it's a bug with the manga mode checkbox being unchecked This bug was never caught since most people read right to left content.

**Comment by axu2** [comment]
@e1ker This is now fixed in master. A release will come out eventually if you can't run the code directly.
