### ISSUE TITLE
the macOS download contains version number 0.0.0

### ISSUE THREAD

**Issue by suschizu** [ciromattia/kcc#651]
**Describe the bug**
the macOS download contains version number 0.0.0 instead of 5.6.5 
https://github.com/ciromattia/kcc/releases/download/v5.6.5/KindleComicConverter_osx_5.6.5.dmg

**Expected behavior**
The bundle version should contain the correct version number : 

info.plist contains:
```
…
	<key>CFBundleShortVersionString</key>
	<string>0.0.0</string>
…
```

**Desktop (please complete the following information):**
 macOS 13.6
 

<img width="575" alt="Screenshot 2023-12-24 at 15 52 41" src="https://github.com/ciromattia/kcc/assets/16004333/b79945dd-9660-40da-b63e-c200a1db49b9">

**Comment by axu2** [comment]
- duplicate #632
