### ISSUE TITLE
not adding margins, spreads don't work, and changing settings doesn't change the end result at all

### ISSUE THREAD

**Issue by peiskios** [ciromattia/kcc#659]
I'm trying to convert manga files to epub files for the kobo libra 2. No matter what settings I change, margins aren't added to prevent the image from stretching to fill the screen. I've tried several different settings combos but it doesn't change what the output looks like at all for some reason? It's always stretched across the screen and spreads don't work (just zooms in on one page or shows a blank page if I tilt my kobo to landscape).

Further explained + pictures in [this reddit post](https://www.reddit.com/r/kobo/comments/1908ces/manga_conversion_with_kcc_is_stretched_and/)

**Comment by axu2** [comment]
@peiskios 

Try
1) uncheck stretch/upscale
2) uncheck cropping mode
3) transfer file directly via USB without using Calibre. don't edit the metadata.

**Comment by peiskios** [comment]
using the kobo kepub plugin for calibre + changing the settings you reccomended fixed the issue
