### ISSUE TITLE
KeyError: ''

### ISSUE THREAD

**Issue by CristianIGVD** [ciromattia/kcc#663]
I get this error when I try to use 5.6.5. I initially had 5.6.3 working but I mistakenly deleted the main Kcc.exe 
I tried reinstalling 5.5.2 which has an installer. That one works but when I try to put the kcc.5.6.5 in the main directory of KCC. I get this error 
Traceback (most recent call last):
  File "kcc.py", line 74, in <module>
    start()
  File "kindlecomicconverter\startup.py", line 39, in start
    KCCUI = KCC_gui.KCCGUI(KCCAplication, KCCWindow)
  File "kindlecomicconverter\KCC_gui.py", line 1086, in __init__
    self.changeFormat(self.currentFormat)
  File "kindlecomicconverter\KCC_gui.py", line 659, in changeFormat
    if GUI.formats[str(GUI.formatBox.currentText())]['format'] == 'MOBI':
KeyError: ''

PLease help as I can't use this app for my KOBO Sage anymore

**Comment by axu2** [comment]
Ooo that looks like an old version conflict. 

Try changing settings related to the error message, in this case output format. 

Then try running 5.6.5.exe from your desktop. 

If that doesn't work, I can try force reset.

**Comment by CristianIGVD** [comment]
I changed to another supported kindle like you said. I used 5.5.2 to change that setting. Afterwards I used the latest 5.6.5 and now it works!
Thank you very much

**Comment by axu2** [comment]
Reopening. 

The proper fix is to not crash if unexpected stuff in registry.
