### ISSUE TITLE
Docker ModuleNotFoundError

### ISSUE THREAD

**Issue by onyto** [ciromattia/kcc#668]
**Describe the bug**
The app doesn't start because there is no module named 'natsort'

Error message:
```
sudo docker run --rm -v "$(pwd):/app" ghcr.io/ciromattia/kcc:latest
Traceback (most recent call last):
  File "/opt/kcc/kcc-c2e.py", line 33, in <module>
    startC2E()
  File "/opt/kcc/kindlecomicconverter/startup.py", line 47, in startC2E
    from .comic2ebook import main
  File "/opt/kcc/kindlecomicconverter/comic2ebook.py", line 37, in <module>
    from natsort import os_sorted
ModuleNotFoundError: No module named 'natsort'
```

**To Reproduce**
1. download latest docker image
2. run it

**Expected behavior**
App should run successfully

**Comment by axu2** [comment]
I do not use Docker, but I think it's due to these lines:
https://github.com/ciromattia/kcc/blob/master/Dockerfile-base#L69
https://github.com/ciromattia/kcc/blob/master/Dockerfile-base#L125

missing `natsort`

Do you mind adding them in a PR and testing? @onyto

**Comment by onyto** [comment]
You have pointed out the lines for the arm build but I'm using amd64 which should install natsort from the `requirements.txt`.
https://github.com/ciromattia/kcc/blob/v5.6.5/Dockerfile-base#L14
https://github.com/ciromattia/kcc/blob/v5.6.5/requirements.txt#L9

I did a `pip list` inside the container and confirmed that natsort is missing:
```
$ sudo docker run -it --entrypoint /bin/bash ghcr.io/ciromattia/kcc:latest
root@bea83532fe0f:/app# pip list
Package                       Version
----------------------------- -------
cffi                          1.15.1
distro                        1.8.0
mozjpeg-lossless-optimization 1.1.2
Pillow                        9.5.0
pip                           22.3.1
psutil                        5.9.5
pycparser                     2.21
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.12.1
python-slugify                8.0.1
raven                         6.10.0
setuptools                    65.5.0
text-unidecode                1.3
```

But doing a `python -m pip install -r /opt/kcc/requirements.txt` installs everything correctly:
```
root@bea83532fe0f:/app# pip list
Package                       Version
----------------------------- ----------
certifi                       2023.11.17
cffi                          1.15.1
charset-normalizer            3.3.2
distro                        1.8.0
fastnumbers                   5.1.0
idna                          3.6
mozjpeg-lossless-optimization 1.1.2
natsort                       8.4.0
Pillow                        9.5.0
pip                           22.3.1
psutil                        5.9.5
pycparser                     2.21
PyQt5                         5.15.9
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.12.1
python-slugify                8.0.1
raven                         6.10.0
requests                      2.31.0
setuptools                    65.5.0
text-unidecode                1.3
urllib3                       2.1.0
```

Now the app works:
```
root@bea83532fe0f:/app# python /opt/kcc/kcc-c2e.py -h                                                                                                                                                                                                         
comic2ebook v5.6.5 - Written by Ciro Mattia Gonano and Pawel Jastrzebski.                                                                                                                                                                                     
usage: kcc-c2e [options] [input]
...
```

I guess the problem is with building the image then.

**Comment by axu2** [comment]
Thanks for looking into it, I see the real issue.

The base docker image hasn't been updated in 5 months. It doesn't run automatically.

![image](https://github.com/ciromattia/kcc/assets/20757319/3246dcb1-f687-4e47-a148-89d7af540a48)

https://github.com/ciromattia/kcc/actions/workflows/docker-base-publish.yml

**Comment by onyto** [comment]
I just pulled the image and everything seems to be working now :+1:

**Comment by axu2** [comment]
Gonna reopen since this same issue might reoccur next time dependencies change.

**Comment by darodi** [comment]
@axu2 

Last docker image is broken for arm/v7
and maybe other platforms since 
- #523 

Please keep v5.7.0 a pre-release until I fix it.
I'll try to find some time for that this week.

```bash
rodi@computer:/mnt/c/test$ docker run --platform linux/arm/v7 --rm -v "$(pwd):/app" ghcr.io/ciromattia/kcc:latest -p KPW5 ./258.cbz
ERROR: psutil 5.0.0+, python-slugify 1.2.1+, Pillow 5.2.0+ is not installed!
```


I said before, here, that docker needed to be tested/adapted before a release.

> partly done in 
https://github.com/darodi/kcc/commit/e37559bdfc4ce49dd07b7b7f42e952c7fececc2a
I'm still testing docker before releasing a 5.7.0beta
_Originally posted by @darodi in https://github.com/ciromattia/kcc/issues/618#issuecomment-1850837822_
            
work in progress in branch
https://github.com/darodi/kcc/tree/beta_release

**Comment by axu2** [comment]
@darodi Yea, I wasn't planning to do a real release, I was just experimenting with the docker and I thought it needed a pre-release tag to run. I ended up reverting that change.

**Comment by axu2** [comment]
@onyto 6.2.0 has a fixed docker version now
