### ISSUE TITLE
7zip window popup that steals focus

### ISSUE THREAD

**Issue by ReaLx3m** [ciromattia/kcc#674]
**Describe the bug**
With 5.6.5 when im converting cbr to cbz, theres a cmd window popup caused by 7zip which steals focus from other windows every time it shows(thats for every file, and is visible for few seconds). I dont have similar behavior with 5.6.4.

**Settings Screenshot**
![Screenshot 2024-02-02 022301](https://github.com/ciromattia/kcc/assets/22484793/59ed9217-1655-4609-8fc5-ef23a00692a3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Device: Pocketbook Inkpad 3

**Comment by axu2** [comment]
@ReaLx3m 

Please try the pre-release v5.7.0

**Comment by ReaLx3m** [comment]
I checked before posting and latest was 5.6.5, must have been released minutes after opening this issue. 
I tired 5.7.0(though for some reason its still labeled as 5.6.5), and it doesnt exhibit the behavior.
Thanks for the heads up.

**Comment by axu2** [comment]
@ReaLx3m Yep it was released within 6 minutes of your post.

Pre-release will have the old version number until official release.

**Comment by ReaLx3m** [comment]
Cool then, issue can be closed as solved.

**Comment by axu2** [comment]
I decided to pull v5.6.5 and re-release it with this fix since v5.7.0 is in pre-release.
