### ISSUE TITLE
Double pages aren't rotated

### ISSUE THREAD

**Issue by MARW4N** [ciromattia/kcc#676]
**Describe the bug**
I convert from CBZ to MOBI to read on my kindle. Double pages aren't rotated although I checked it (full check not intermediate)

**Expected behavior**
The double pages should be rotated as stated

**Screenshots**
### This is my settings 
![image](https://github.com/ciromattia/kcc/assets/134745626/e842c364-76cf-4fca-8a52-121226f671c7)

### This is the double page before conversion 
![image](https://github.com/ciromattia/kcc/assets/134745626/6a5b6400-dcf6-48d0-bed0-4a6ad577431d)

### This is how the double page is displayed after conversion
![image](https://github.com/ciromattia/kcc/assets/134745626/95d0e8b6-ff0c-40b5-8258-7e42d465c453)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Device: Kindle Paperwhite 11th gen

**Comment by axu2** [comment]
@MARW4N its because you ticked disable processing which ignores most options.
