### ISSUE TITLE
Problem when starting 

### ISSUE THREAD

**Issue by justausername121** [ciromattia/kcc#677]
<img width="312" alt="kcc prob" src="https://github.com/ciromattia/kcc/assets/108175453/2ca41649-c152-4568-825f-eddef6602c50">

**Comment by axu2** [comment]
What version of KCC are you running? V5.6.5? V5.7.0?

Why does it say python 2 in the error? This is a python 3 app. Are you running from source?

**Comment by justausername121** [comment]
Ver 5.6.5 and I just start the app in the kcc-> kindle comic converter folder (file named KCC.exe)

**Comment by justausername121** [comment]
and when i download the kindle previewever and i start the exe file for downloading it just give me some random error during the process always starting with Extract: error writing to file...

**Comment by justausername121** [comment]
Tried redownloading both and somehow work still you have been of great help ty
