### ISSUE TITLE
PDOC vs EBOK option

### ISSUE THREAD

**Issue by axu2** [ciromattia/kcc#685]
It's a little annoying to always ask to rate the book at the end, which doesn't happen with personal documents from Send to Kindle.

**Comment by Zappy86** [comment]
There's also been an issue going around where documents labeled as EBOK get deleted from devices by Amazon.

**Comment by axu2** [comment]
@Zappy86 I have seen the thread on MobileRead, but never experienced the issue myself with any files, including kcc files.
