### ISSUE TITLE
flatpak: stuck on Creating MOBI Files

### ISSUE THREAD

**Issue by Pyrix25633** [ciromattia/kcc#690]
**Describe the bug**
When converting to MOBI/AZW3 or MOBI+EPUB the process is stuck at "Processing MOBI files". When converting to EPUB a hidden file (.<something><original file name>.epub-<something>) is created at the source directory if you don't select it, either way and it doesn't show on kindle.
Also when aborting, it just stays there, stuck.

**To Reproduce**
Convert .cbz or .cbr file to MOBI/AZW3 or MOBI+EPUB or to EPUB.

**Expected behavior**
It should finish converting or create an EPUB file that the kindle is able to read.

**Screenshots**
Defaults, no manga mode, stretch/upscale.
![image](https://github.com/ciromattia/kcc/assets/82797674/d57d64d4-f72d-4f95-9457-c646edf8f428)
![image](https://github.com/ciromattia/kcc/assets/82797674/d4fc15d2-dd0e-432b-b62c-7296bc27f8d7)
![image](https://github.com/ciromattia/kcc/assets/82797674/59c929f3-dd1e-46f7-8144-62b0980ff243)
![image](https://github.com/ciromattia/kcc/assets/82797674/9830ba02-9f27-4260-9bc4-840b20aa69c7)

**Desktop (please complete the following information):**
 - OS: Zorin OS 17 -> Ubuntu 22.04, flathub kcc
 - Device: Kindle Paperwhite 7th gen. 5.16.2.1.1

**Comment by axu2** [comment]
Hmmm, maybe it's a permission issue, try doing a shift+click on the convert button to select an output directory on your desktop or something.

**Comment by Pyrix25633** [comment]
Ok, i understand Kindle does not read epub.
Yes. conversion to epub works.
I tried selecting the output folder, it still is stuck at "processing MOBI files...", so conversion to AZW3 or MOBI does not work.

**Comment by Pyrix25633** [comment]
Yeah, sending it that way it works, but it kinda defeats the purpose and make it really slower.
I've installed through the "Software" application with flatpak, I suppose it automatically downloaded all dependencies, how do I run kindlegen?

**Comment by axu2** [comment]
Thanks for confirming nothing is weird with the Send to Kindle epub.

I don't use flatpak, but maybe this helps? https://github.com/ciromattia/kcc/wiki/Installation#linux

**Comment by Pyrix25633** [comment]
![image](https://github.com/ciromattia/kcc/assets/82797674/bf38f27a-0c90-4d83-aaae-b6005f071131)
Now it is stuck here.
And I would say that installation instruction are unclear, I don't even understand if it is possible to install kcc another way and how. And I'm a programmer.

**Comment by axu2** [comment]
@catsout @winstonma 

Can you help this user's issue?

**Comment by catsout** [comment]
Please use flatseal and add host filesystem permission.  
![image](https://github.com/ciromattia/kcc/assets/36527596/5f2f6d80-1034-4642-adfe-d84314329150)

**Comment by catsout** [comment]
Make sure your files that imported in kcc are not started with `/run/user/1000/doc`.

**Comment by winstonma** [comment]
@Pyrix25633

Please check the following

1. Please check if there is `kindlegen` executable in the following directory
```
$ ls ~/.var/app/io.github.ciromattia.kcc/data
kindlegen
```
2. Also please try to run KCC using terminal, this way you could see more logs
```
$ flatpak run io.github.ciromattia.kcc
```

Hope this helps

**Comment by Pyrix25633** [comment]
> Make sure your files that imported in kcc are not started with `/run/user/1000/doc`.

They do, I thought it was strange, but didn't manage solve that.

**Comment by Pyrix25633** [comment]
Ok, using flatseal to manage permissions it works, you should add it to the installation wiki.

**Comment by Pyrix25633** [comment]
Still, is it normal that the converted book has no cover?

**Comment by axu2** [comment]
If you want a cover, leave Kindle plugged in during conversion or follow this guide:

- https://github.com/ciromattia/kcc/issues/508

PW 7 is PW3.

This is going to be renamed to PW 7 in KCC v6.

![image](https://github.com/ciromattia/kcc/assets/20757319/6944dec5-b2ef-40c9-b98b-0dae101682c0)

**Comment by Pyrix25633** [comment]
Also, now I was trying to bulk convert .cbz contained in a folder, but it says that the directory is empty...
![image](https://github.com/ciromattia/kcc/assets/82797674/9ab8283d-e7c6-445b-9164-06387105d2b9)

**Comment by axu2** [comment]
You need to drag in all the cbz not the containing folder.

**Comment by axu2** [comment]
@Pyrix25633 Does the section here to use flatseal make sense or does a flatpak user need more detail than that? https://github.com/ciromattia/kcc/wiki/Installation#linux

**Comment by Pyrix25633** [comment]
I think it's perfect, maybe **make it stand out**. Flatseal has an intuitive and easy to use interface, so no additional information is needed.
👍

**Comment by axu2** [comment]
@darodi Just FYI in case it's relevant to Steam Deck
