### ISSUE TITLE
Pocketbook Inkpad Color 3 settings 

### ISSUE THREAD

**Issue by Kilvearn** [ciromattia/kcc#692]
Hello, 

I would like to ask what is the optimal setting for the "Pocketbook Inkpad Color 3" for reading comics and manga?
The resolution seems to be the same as "Kobo Aura One", but I don't know about other differences that could be taken into account in the KCC Profile. (it's not the same screen : kaleido 3)
Thanks a lot in advance!

**Comment by axu2** [comment]
I'd experiment with the "Other" profile and the color mode option, but I don't own any color devices to test.

**Comment by Kilvearn** [comment]
Thanks for your answer !
Which value must I put in "Gamma" ? Do I leave it in "auto" ?

**Comment by axu2** [comment]
Leaving it unchecked is probably fine. 1.0 disables gamma correction. 1.8 is unchecked at the moment. Higher number is darker.
