### ISSUE TITLE
distutils

### ISSUE THREAD

**Issue by 8uziak** [ciromattia/kcc#694]
**Describe the bug**
I would like to contribute to this project so i tried to install from source option included in readme.md. After doing step by step guide to open the app i get ModuleNotFoundError error.

**To Reproduce**
$ python -m venv venv
$ venv\Scripts\activate.bat
$ pip install -r requirements.txt
$ python kcc.py

**Expected behavior**
An app should open without any errors

**Screenshots**
```
python3 kcc.py                 
Traceback (most recent call last):
  File "/Users/mateuszbuziak/Code/kcc/kcc.py", line 71, in <module>
    from kindlecomicconverter.startup import start
  File "/Users/mateuszbuziak/Code/kcc/kindlecomicconverter/startup.py", line 24, in <module>
    from .shared import dependencyCheck
  File "/Users/mateuszbuziak/Code/kcc/kindlecomicconverter/shared.py", line 25, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
```

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.4.1

**Comment by axu2** [comment]
- duplicate #618

Use Python 3.11 instead.

**Comment by 8uziak** [comment]
switched to Python 3.11.6 and issue has been solved
