### ISSUE TITLE
Conversion to mobi is not creating landscape pages

### ISSUE THREAD

**Issue by Luttudo** [ciromattia/kcc#699]
Conversion (cbr > mobi) looks great but there are some pages that are supposed to be displayed together but aren't.

When converting from cbr to pdf using calibri this feature works fine

Cant find anything about it in wiki

**Comment by axu2** [comment]
Show a screenshot of your kcc settings. @Luttudo 

Do you have landscape split unchecked?

Are the images already split in the original CBR?

**Comment by Luttudo** [comment]
It worked. Thanks!! And sorry for the stupid issue, hope it helps someone.
