### ISSUE TITLE
"(X) Install KindleGen (link)" - KCC not finding Kindle Previewer

### ISSUE THREAD

**Issue by PrismLeopard** [ciromattia/kcc#701]
Hello,
I have very little experience coding and manually doing work arounds with programs. Could someone please walk me through how I can get KCC to recognize where Kindle Previewer is? The programs are located in the same folder.

![image](https://github.com/ciromattia/kcc/assets/171392815/7227144b-8fc5-4237-b26f-539520fbb8a0)

I am working on a Windows operating system.

**Comment by axu2** [comment]
Did you click on Kindle Previewer to install it?

Then restart kcc/your pc? @PrismLeopard

**Comment by PrismLeopard** [comment]
@axu2 Thank you for responding.

Yes, Kindle Preview is installed and I have restarted my PC. 
I've tried looking up fixes via Dr. Google but everything is a bit too technical for me to follow.

**Comment by axu2** [comment]
@PrismLeopard 

Can you try following this advice?

https://github.com/ciromattia/kcc/issues/660#issuecomment-1880085625

Then copy kindlegen.exe from there and place it next to kcc.

**Comment by PrismLeopard** [comment]
@axu2 I'm working on Windows 11

I found Kindlegen.exe and placed kcc.exe. The error is now gone. I though I was doing it right. I guess I just need to be told twice. 

![image](https://github.com/ciromattia/kcc/assets/171392815/780c2792-835c-459a-8778-2dff5ae62f6b)

**Comment by axu2** [comment]
@PrismLeopard could you add screenshots of where kcc/kindlegen are?

**Comment by PrismLeopard** [comment]
@axu2 
After moving KCC.exe into:

C:\Apps\Kindle Previewer 3\lib\fc\bin

I was able to remove the error in KCC landing pad, it is now working correctly and I am able to convert files.

**Comment by axu2** [comment]
@PrismLeopard 

Is that the exact location? You didn't edit the url to remove a username?

C:\Apps\Kindle Previewer 3\lib\fc\bin

**Comment by PrismLeopard** [comment]
@axu2 
Correct, I did not edit to remove a username.

**Comment by axu2** [comment]
@PrismLeopard Could you please review this PR and use the test build to see if it runs normally without putting KCC in a special place?

**Comment by axu2** [comment]
@PrismLeopard could you try the linked test build?

**Comment by axu2** [comment]
@PrismLeopard OK I'm just going to release the change in 6.1.0, would be nice if you could confirm it works.
