### ISSUE TITLE
Manga mode do not work when converted to cbz format

### ISSUE THREAD

**Issue by nodscrim** [ciromattia/kcc#708]
When I converted **zip** to **cbz** format(checked the manga mode option),I found that the page turn is still left to right.How could I fix this?

**device**:kobo libra colour

**Comment by axu2** [comment]
Have you tried the epub format? @nodscrim

**Comment by nodscrim** [comment]
Yes, it worked on epub format. But cbz would be better because of the high loading speed and zoom function @axu2

**Comment by bust4cap** [comment]
isnt that just a limitation of your reader? cbz is just a zip archive, you dont define any reading direction there

**Comment by axu2** [comment]
- duplicate #351

**Comment by nodscrim** [comment]
Ok,thanks a lot @axu2
