### ISSUE TITLE
Kobo Libra Colour

### ISSUE THREAD

**Issue by SUM1-UNO** [ciromattia/kcc#711]
Not an issue but I didn't know where to ask this. I can't find the Kobo Libra Colour in the list of devices. Will it be added any time soon?

**Comment by axu2** [comment]
In the meantime use the libra profile with the color box checked.

**Comment by axu2** [comment]
OK released a pre-release version of 6.1.0 with the Colour profiles attached, please test. @SUM1-UNO @afonsoguerra

**Comment by SUM1-UNO** [comment]
> OK released a pre-release version of 6.1.0 with the Colour profiles attached, please test. @SUM1-UNO @afonsoguerra

It's there now. Thank you! One question, is there a way to see what width/height is used?
