### ISSUE TITLE
XCB Platform Plugin Issue

### ISSUE THREAD

**Issue by detournemint** [ciromattia/kcc#712]
I get the following error
`$ ./kindleComicConverter-latest-x86_64.AppImage 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, wayland-egl, minimalegl, minimal, eglfs, linuxfb, vnc, xcb, offscreen, wayland.

Aborted (core dumped)
`

**Comment by axu2** [comment]
Looks like a problem with the Qt6 upgrade. You can either try installing from flatpak or just using the Qt5 version 5.6.5.
