### ISSUE TITLE
KCC 6.1 on Windows Docker | No module named 'pkg_resources.extern'

### ISSUE THREAD

**Issue by theseaking** [ciromattia/kcc#715]
I'm having problems installing on Windows 10.  I downloaded the latest version of Python (3.12.4) and the latest version of KCC (6.1.0). 

I got an error about some resource missing while installing. As well, Avast thought it was a suspicious program. I tried disabling the antivirus, but I got the same error.

**Comment by theseaking** [comment]
Added an image of the install error:
![Error](https://github.com/ciromattia/kcc/assets/173861082/c203c976-d19b-4b4c-9e61-9bb2eed2b3fc)

**Comment by axu2** [comment]
Does the problem exist on 6.0?

**Comment by axu2** [comment]
Thanks for bringing this up, it's an issue with the Windows Docker GitHub runner. Use 6.0 for now.

- https://github.com/pypa/setuptools/issues/4374#issuecomment-2123082242

**Comment by axu2** [comment]
OK apparently my fix flags KCC as a virus...

![image](https://github.com/ciromattia/kcc/assets/20757319/8f65d525-c067-4789-b514-131ffd7ea476)

Reverting...

**Comment by theseaking** [comment]
Thank you! It works without problems now!
