### ISSUE TITLE
I keep getting error message that software needs an update.

### ISSUE THREAD

**Issue by nikitarthbn** [ciromattia/kcc#720]
Hello there! First of all thank you for KCC! I’m only new to e-reading and I saw this. Unfortunately I can’t install it. I keep on getting this error message. 

<img width="251" alt="Screen Shot 2024-07-15 at 2 06 33 PM" src="https://github.com/user-attachments/assets/a4326cdb-2cc0-4929-86e0-64a13c22b50e">

I downloaded both the latest for macos. I'm not sure if I'm doing it right. Just trying my luck. Thank you!

**Comment by axu2** [comment]
@nikitarthbn 

You need to right click open to open unsigned apps. 

KCC doesn't have an apple developer account.

**Comment by nikitarthbn** [comment]
@axu2 oh that's why 😹 thank you!
