### ISSUE TITLE
Not detecting

### ISSUE THREAD

**Issue by ranart4** [ciromattia/kcc#721]
KCC is not detecting KindleGen,they are in the same hard drive and I've tried putting them into the same folder. I tried using the %APPDATA% line in file explorer but says that it doesn't even exist. How do I put them in the same directory to get it to work?

**Comment by axu2** [comment]
@ranart4 Did you install Kindle Previewer? If that doesn't work ping me on discord: https://discord.gg/uY8TZggA

**Comment by ranart4** [comment]
Oh my bad for the late response, I waited too long and your discord link is out of date. I've tried redownloading Kindlepreviewer (that's what I meant when I said KindleGen) and added it to C drive instead - still no luck

**Comment by ranart4** [comment]
Okay upon further research I was actually able to fix it. I moved KCC.exe into user/kindle previewer 3/lib/fc/bin

Once I moved it the error went away so if anyone else has this issue just drag and drop the KCC.exe into user/kindle previewer 3/lib/fc/bin on your C drive

I guess KCC was just looking in the wrong place for kindle previewer and for some reason my PC is missing certain file locations so it just downloaded into a different folder I guess

Anyway im really glad it was this easy. Thanks for trying to help me though I appreciate it

**Comment by axu2** [comment]
Can you provide the exact URL where kindlegen is? So I can tell kcc where to look in the next version? @ranart4

**Comment by ranart4** [comment]
I'm sorry I'm not 100% sure what you mean, are you asking for the download link I used? Or are you meaning the file path? Sorry I'm still learning a lot of this pc stuff

**Comment by axu2** [comment]
This window in the Kindle Previewer installer: 
![image](https://github.com/user-attachments/assets/7172477b-4849-47d7-9c39-20f004baff7e)

@ranart4

**Comment by ranart4** [comment]
Well I can't find the installer but KindlePreview is in its own folder so Users/user/KindlePreviwer3

I stuck KCC.exe into C/Users/user/KindlePreviwer3/lib/fc/bin

Really sorry if this isn't what you're asking for, I can't find the installer to see that window

**Comment by axu2** [comment]
Can you please go to where kindlegen.exe is for you:

![image](https://github.com/user-attachments/assets/f0bd1bac-5e43-4a53-a01a-f7c9ef01c5a3)

Click the URL bar:

![image](https://github.com/user-attachments/assets/3fa42198-53f7-4386-b6bd-dc02db9b6bc8)

And tell me the url? @ranart4

**Comment by axu2** [comment]
@ranart4 

Can you see if this build can be run without putting it in a special place?

https://github.com/axu2/kcc/releases/tag/v6.1.0-user-profile

Can you tell me if kindlegen is at this location?

`%UserProfile%\Kindle Previewer 3\lib\fc\bin\`
