### ISSUE TITLE
Chapters out of order

### ISSUE THREAD

**Issue by axu2** [ciromattia/kcc#724]
**Describe the bug**
Chapters aren't naturally sorted like pages. 

**To Reproduce**
Have chapter folders like

9

10

11

It will sort like:

10

11

9

**Expected behavior**
Should sort

09

10

11

**Additional context**
Only rename like this if natural sort is different than normal lexicographic sort. 

Possibly use os_sort_keygen on keys to convert to str, number tuples and string formatting to pad zeroes.

Can't just replace the original chapter names since they have important info, unlike individual page names. 

Maybe just put 01 02 03 at the start if sorts don't match.

**Comment by darodi** [comment]
And how will you manage chapters with a prefix?

- Stuff Chapter 9
- Stuff Chapter 10
- Stuff Chapter 11
- Stuff Chapter 12

It's just easier to just rename directories and keep the code "simple".
Or do 2 conversions:  One for a directory with chapter 1 to 9 and a second conversion with the rest.

**Comment by axu2** [comment]
Yea, fixing this would be pretty complicated, it's probably better to just leave it alone and fix it manually whenever it comes up.
