### ISSUE TITLE
 When making epub for Mac iBook, I found that no matter how I choose, the picture will still be cropped.

### ISSUE THREAD

**Issue by Lyman11** [ciromattia/kcc#725]
When making epub for Mac iBook, I found that no matter how I choose, the picture will still be cropped. How to set it up?

The resolution of the image is 980*1503
![image
](https://raw.githubusercontent.com/Lyman11/Lyman/main/upload/202407291018085.png)

My setting is 980*1550
![setting](https://raw.githubusercontent.com/Lyman11/Lyman/main/upload/202407291017834.png)

However, the displayed image is still cropped
![display](https://raw.githubusercontent.com/Lyman11/Lyman/main/upload/202407291026349.png)

**Comment by axu2** [comment]
You should use a cbz reader app on your Mac instead. Maybe there's a good one in Mac App Store.
