### ISSUE TITLE
Help in preserving colors 

### ISSUE THREAD

**Issue by AVM-1996** [ciromattia/kcc#732]
I am not sure how much of a value this would be to anyone but I had to ask since no one did

I have bought a color ereader for the first time, got to test which format/setting is good, found a decent balance but here's my problem
 
My device, a Pocketbook Color 3, works well with EPUB when handling colors, I don't get any artifacts or such from it but as many have said before it look washed, CBZ on the otherhand has some of artifact pixelation when there is color, I know I can adjust it but this doesn't fix anything and this is where I have to ask if there is a way to increase the saturation of an EPUB file when reading from an ereader? or do I lower the gamma level?

**Comment by axu2** [comment]
Please upload your kcc settings screenshot. @AVM-1996

**Comment by AVM-1996** [comment]
![image_2024-08-24_220451973](https://github.com/user-attachments/assets/74857632-e45f-46dd-8f6e-51b0678a13a4)

**Comment by axu2** [comment]
You can try setting gamma to 1.0

Or disabling upscale.

**Comment by AVM-1996** [comment]
well i tried that first but if i CBZ format it produces an effect like compression but when i used EPUB it doesn't but the colors are faded

i mostly read in black and white so this is new to me

**Comment by AVM-1996** [comment]
Ok i am going to test around with the gamma settings and see what happens

**Comment by axu2** [comment]
Some pictures of the problem could be helpful too. If you prefer discord you can troubleshoot on the discord.

**Comment by AVM-1996** [comment]
well thats the thing its only on the ereader but ill try different ways maybe with calibre?

**Comment by axu2** [comment]
@AVM-1996 did you solve the issue?
