### ISSUE TITLE
Error during conversion on MacOS Sonoma: No such file or directory '7z'

### ISSUE THREAD

**Issue by abstractrealism** [ciromattia/kcc#739]
**Describe the bug**
Upon trying to convert a CBR file I get the error "No such file or directory: '7z'. I've converted CBZ fine, but not CBR. Assuming it means 7zip, and is something to do with being a RAR. I can read the CBRs fine in YACreader, and extract them fine with the Unarchiver, so there's nothing wrong with the files. 

**To Reproduce**
Add CBR to queue, on MacOS Sonoma. Try to convert. "Error during conversion. Please consult Wiki" but there isn't an entry for this on the wiki. 
I have spread splitter and Stretch checked, if that matters. 

**Expected behavior**
Convert to epub successfully

**Screenshots**
Add a screenshot of your KCC settings.

**Desktop (please complete the following information):**
MacOS Sonoma 14.5

**Additional context**
![Screenshot 2024-09-07 at 11 46 14 PM](https://github.com/user-attachments/assets/86b70890-8682-40a6-b86f-d7ec9ae8e850)

**Comment by axu2** [comment]
This is already fixed in 6.1.1 @abstractrealism
