### ISSUE TITLE
Dark Mode (feature request)

### ISSUE THREAD

**Issue by jeffmcneill** [ciromattia/kcc#741]
Either dark mode switcher or simply follow color scheme of OS. This for Debian Linux.

**Comment by ctrleo** [comment]
I use Debian too! I think the colour scheme of the UI changes dependant on your gtk theme, for example, I am using [Dracula](https://draculatheme.com) and my KCC looks like this:
![kcc](https://github.com/user-attachments/assets/d7786a80-fa88-4c2a-9cd1-c6094d887366)
If you could let me know which desktop environment you're using or which theme is currently installed I'd probably be able to help :)

**Comment by jeffmcneill** [comment]
Yes, mine looks like that, also. The Dark Mode part desired is that large white area with dark text. Inverting that would solve everything for me. BTW I use Debian stable with XFCE, and Adwaita-dark (Gtk2, Gtk2) and Gnome theme for icons. Again, it is just the large white area with non-white text that would be usefully non-glaring if dark or dark grey.

**Comment by ctrleo** [comment]
I found a fix for it!! All I gotta do is fix the text colours and I'll get a pull request out probably in the next hour ^-^

![happy tay](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3p1enFqd2t6eHJ0NGpqbWp3a3I5NTllY2ZndGdwaGR3ZTlzZ2NmMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gromG2nn1K3Tg50ojX/giphy.gif)
