### ISSUE TITLE
Annotation feature disabled when converting CBZ files to EPUB

### ISSUE THREAD

**Issue by lovesewerrats** [ciromattia/kcc#744]
**Describe the bug**
Annotation feature is disabled when I try to I convert CBZ files to EPUB or KEPUB

To Reproduce

1. Add file .CBZ
2. Convert to EPUB
or 
3. Convert to KEPUB
or
5. Convert to EPUB (Calibre KFX)
none of these conversions worked 

Expected behavior
Would like to be able to annotate on my epub files converted from CBZ

**Screenshots**
<img width="551" alt="Screenshot 2024-09-18 at 9 50 41 PM" src="https://github.com/user-attachments/assets/3f63b3e4-410c-4172-8ec4-4eabd1dd1844">

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Device [Kobo Libra Colour]

**Additional context**
Regardless if my file was filename.epub or filename.kepub.epub, no annotation feature was enabled despite the Kobo allowing annotation for both of these files types.

**Comment by axu2** [comment]
- duplicate #704
