### ISSUE TITLE
macOS: kkc's info.plist contains wrong version numbers since version 5.6.2 

### ISSUE THREAD

**Issue by suschizu** [ciromattia/kcc#747]
Hello!
for some time now, every macOS kkc version contains 0.0.0 as CFBundleShortVersionString - and the CFBundleVersion is missing

<img width="541" alt="Screenshot 2024-09-29 at 22 05 49" src="https://github.com/user-attachments/assets/988e9bc7-5b48-4a89-b297-53d98885617c">

**Comment by axu2** [comment]
@suschizu where is this version number used?

**Comment by suschizu** [comment]
ah right yes - that's a duplicate - sorry! 
the CFBundleShortVersionString is the string that shows up for the user ()
<img width="311" alt="Screenshot 2024-09-29 at 22 27 04" src="https://github.com/user-attachments/assets/d85f6eb1-dfb9-43ba-a99c-a710347b7b5e">
the BundleVersion is the build version - this should iterate automatically
