### ISSUE TITLE
Virus Detected by Windows

### ISSUE THREAD

**Issue by Murderchan** [ciromattia/kcc#751]
**Describe the bug**
Windows Defender instantly detects the file as a virus and deletes it. It lists the threat as severe, and when clicking to 'Learn More' goes into detail that the file contained a trojan virus(Trojan:Script/Wacatac.B!ml).

**To Reproduce**
1. Download the first file listed
2. Run the file on Windows 10

**Expected behavior**
Windows will detect a threat, and instantly quarantine, and then delete any subsequent downloads.

**Screenshots**
![virusDetected](https://github.com/user-attachments/assets/2b20220a-11ff-4e6e-9585-adfcbba46d92)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Device: Desktop Computer

**Additional context**
I was able to run the app up until I tried to convert files, wherein Windows detected an issue and quarantined the program. Every download of the application afterwards was instantly deleted.
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

**Comment by axu2** [comment]
Ugh. I accidentally rebuilt 6.2.0 on the windows version and it seems to be causing issues. Please use an older release in the meantime while I look into it. 6.0.0 is very stable, 6.1.0 had a lot of issues.

**Comment by axu2** [comment]
@Murderchan Tweaked the build process, please confirm if its fixed.

**Comment by axu2** [comment]
@alpaquito28 is the error message any different? Screen shot and is it w10 or w11?

**Comment by alpaquito28** [comment]
@axu2 
I downloaded  at 14.15 CET multiple times the latest available version 6.2.0.exe, the first of the assets lists. It got flagged (quarantined and deleted) every time before I could run it. The trojan seems to be different than the one from the issue creator. Windows will detect a threat, and instantly quarantine, and then delete any subsequent downloads.

After that I tried with the previous version 6.1.0.exe. Before running it I also got a warning from Windows defender, but after dismissing it, it ran without issues and I could proceed as normal, so I did not try with 6.0 version. 

Version: 6.2.0.exe
Trojan:Win32/Sabsik.FL.A!ml
Windows: 11 23H2 (Lenovo Laptop)

This is the link from Microsoft after clicking on more info: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FSabsik.FL.A!ml&threatid=2147780195


![image](https://github.com/user-attachments/assets/dcfe377e-f2a8-4636-a31f-d9c921179ac1)

**Comment by Murderchan** [comment]
Nevermind - in the middle of converter some volumes Windows flagged it and quarantined it again. I almost finished 3 volumes worth of material before it got flagged.

![secondVirus](https://github.com/user-attachments/assets/16b6bc81-f6b1-4ecb-aa5a-15f1e0f6d36d)

**Comment by AcidWeb** [comment]
Sadly this often an issue with PyInstaller binaries. `!ml` in threat name mean it was educated guess - bad one in this case.

[Report a false positive](https://www.microsoft.com/en-us/wdsi/filesubmission/) to Microsoft.
Make sure that PyInstaller is recompiling the bootloader before using it and I would suggest to codesign the windows binaries - it helps **a lot** with this issue.

**Comment by axu2** [comment]
Ok, I reported it, and also did a tweak to the build process. Please report if it works now.

And I imagine codesign costs hundreds of dollars?

**Comment by AcidWeb** [comment]
Certum have quite cheap ones for open source project.

**Comment by darodi** [comment]
Time to make that donation button on the main page useful :grin:

**Comment by axu2** [comment]
I did a little research, I think maybe publishing on Microsoft Store is cheapest option.
