### ISSUE TITLE
"Cannot find kindlegen in PATH! MOBI creation will be disabled."

### ISSUE THREAD

**Issue by ghost** [ciromattia/kcc#76]
Where do I put the kindlegen.exe file in order to be able to create MOBI files?

**Comment by chawlaboo** [comment]
I know this is very late, but what about Linux (umbuntu)

**Comment by yafezdiham** [comment]
Hi, i am on ubuntu 16.04. I want to convert cbr/cbz to AZW3/MOBI but i have a same "Cannot Find KindleGen..." problem. Help me my brothers

**Comment by adrien-be** [comment]
You can install it using [Homebrew](http://brew.sh/).

Restart KCC afterwards.

**Comment by raghad17** [comment]
i have the same problem , i cant add kindlegen on KCC 
i use windows 7 
please help

**Comment by cdpath** [comment]
brew cask install kindlegen

**Comment by yassern** [comment]
i am using mac mojave, installed the kindlegen by brew and however iam getting that error;
already restarted the KCC
