### ISSUE TITLE
What is the correct profile to use for a Kobo Clara BW?

### ISSUE THREAD

**Issue by ernieIzde8ski** [ciromattia/kcc#760]
[The reported display of a Kobo Clara BW](https://us.kobobooks.com/products/kobo-clara-bw) is `1448 x 1072 resolution with Dark Mode`. Does that mean that the Kobo Aura HD has the closest matching profile?

https://github.com/ciromattia/kcc/blob/99d94ceaa77a3e42599aa65f77af32e657f2d574/kindlecomicconverter/image.py#L97

**Comment by axu2** [comment]
There's a kobo Clara 2e profile right there with the right res.

**Comment by ernieIzde8ski** [comment]
Looks like I missed that one, thanks!
