### ISSUE TITLE
KCC 6.0.0 won't detect my KindleGen install

### ISSUE THREAD

**Issue by P0tatoDevil** [ciromattia/kcc#763]
I downloaded KCC 6.0.0 and KindleGen but KCC still gives me the error message to 'Install KindleGen (link) to enable MOBI conversion for Kindles!'. I tried to paste them to the same same folder but it still doesn't work. They are both downloaded in the C drive as well. Is there a specific folder in there that they should both be in? did I download KindleGen incorrectly? I can provide screenshots or any other information that might help.

**Comment by axu2** [comment]
@P0tatoDevil can you try 6.2.1?

Look at this video tutorial:

Install KindleGen (link) | Kindle Comic Converter | KCC
https://youtu.be/u2DA2Y_Qrts

**Comment by P0tatoDevil** [comment]
> @P0tatoDevil can you try 6.2.1? Did you install kindle Previewer?
> 
> Look at this video tutorial:
> 
> Install KindleGen (link) | Kindle Comic Converter | KCC https://youtu.be/u2DA2Y_Qrts

That worked!!! Thank you x1000

**Comment by axu2** [comment]
@P0tatoDevil Please tell which part worked for you, especially the folder kindlegen originally installed to.
