### ISSUE TITLE
Table of contents not working (6.0.0)

### ISSUE THREAD

**Issue by oncpnda** [ciromattia/kcc#766]
After upgrading to MacOS 15.1, I had to update my KCC because my original version wasn't loading.

After doing so, I am unable to create .MOBI with a table of contents.

I usually create the ComicInfo.xml using ComicTagger, unzip the .CBZ and then manually edit the chapters in using this format:

    <Page Image="25" Bookmark="Ch 63: " />

Now, I'm getting nothing after converting.

I tried using the new format from the updated ComicTagger but that doesn't work either.

    <Page Bookmark="ch71" DoublePage="False" Image="7" ImageHeight="2000" ImageSize="938113" ImageWidth="1403" />

This issue also occurred with 6.2.1 when trying to convert for Kindle CS

**Comment by axu2** [comment]
Are you using intel or Apple chip?

Are your files being split due to file size? Kcc ignores chapters if file size split.

**Comment by oncpnda** [comment]
I'm using Apple Silicon, M1 Max to be specific. I added some more info [here](https://www.mobileread.com/forums/showpost.php?p=4465111&postcount=1594), but I don't believe my files are being split.

The previous version of KCC would create chapters/ToC I could use on both Kindle and Calibre, but the latest doesn't, even with the same .xml file and no changes.

The folder structure was just one flat folder with all of the image files and the .xml in the same folder.

The file size of the .mobi with the mozJpeg setting is only 50-80 mb, so I don't think it's causing any splits.

These are the settings I'm using:

<img width="1221" alt="Screenshot 2024-11-03 at 8 29 05 PM" src="https://github.com/user-attachments/assets/f028bc9f-879d-42a8-8312-fc3510317b1a">

![screenshot_2024_11_03T21_22_49-0554](https://github.com/user-attachments/assets/9afd20bd-bdd3-4f1d-8928-705f01e1d7c5)

<img width="248" alt="Screenshot 2024-11-03 at 8 21 06 PM" src="https://github.com/user-attachments/assets/106ccf1e-90ef-4ecc-b0c8-525b739ba10c">

**Comment by oncpnda** [comment]
I already tried that and it didn't fix the issue. The KCC editor doesn't have any fields for chapters.

**Comment by axu2** [comment]
Can you test 5.6.3 ?

If problem does not exist can you also test 5.6.4 and 5.6.5?

**Comment by oncpnda** [comment]
The problem didn't happen with 5.6.3 and did happen with 5.6.4 and 5.6.5

**Comment by axu2** [comment]
I see, thanks for investigating. 

I just converted a file with your xml and got this with 6.2.1

![image](https://github.com/user-attachments/assets/532619b9-b0df-43e1-ac69-c7794a5fc887)

So an assumption is being made somewhere. 

And what is your's folder's file structure look like? Mine looked like this:

![image](https://github.com/user-attachments/assets/93563e88-e2d4-489c-8732-fa2dc6360322)

**Comment by axu2** [comment]
Wait, I see that the mobi doesn't have bookmarks now, even though the intermediate epub does.

**Comment by oncpnda** [comment]
Thanks for the tip, however, I don't get covers with 5.6.3 and it kind of defeats the purpose of the CS if I can't see the covers. Is there any way to fix the chapter/ToC issue with 6.2.1?

**Comment by axu2** [comment]
I see the issue now, 

- #620 

broke comicrack chapters. Are you capable of running code from source?
 @oncpnda

**Comment by axu2** [comment]
Here's a test build that should fix it:

https://github.com/axu2/kcc/releases/tag/v6.2.1-comicrack-pdoc

**Comment by oncpnda** [comment]
Thanks, I‘ll take a look after work and edit this comment.On Nov 4, 2024, at 11:09 AM, Alex Xu ***@***.***> wrote:﻿
Here's a test build that should fix it:
https://github.com/axu2/kcc/releases/tag/v6.2.1-comicrack-pdoc

**Comment by axu2** [comment]
@oncpnda thanks for confirming! I'll push out a 6.2.2 with these fixes soon after I fix all the hardcoding.
