### ISSUE TITLE
 Unable to generate 4 strips

### ISSUE THREAD

**Issue by Maniuz** [ciromattia/kcc#776]
**Describe the bug**
The application currently does not allow users to generate 4 strips from comic pages on the Kindle Paperwhite 4. In previous versions, double-tapping on the screen would successfully split the page into 4 enlarged strips, but this functionality has ceased to work. 

**To Reproduce**
1. Open the comic on kindle.
2. Double-tap on the screen to attempt to split the page into 4 enlarged strips and see the first strip.
3. Nothing happens. the previously viewed page remains

**Expected behavior**
 After double-tapping, the page should be divided into 4 enlarged strips, as it was in previous versions of the app. 

**Screenshots**
![Immagine 2024-11-17 130641](https://github.com/user-attachments/assets/b5d62e29-51a4-45d9-87eb-a82421175d02)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Device: Kindle Paperwhite 4, 10th gen
 - Comic Format: Mobi/AZW3

**Additional context**
In the app settings, there is no option to select the Kindle Paperwhite 4. I selected "other" and manually set the device resolution.

**Comment by axu2** [comment]
Do you mean Paperwhite 10th gen? @Maniuz

**Comment by Maniuz** [comment]
> Do you mean Paperwhite 10th gen? @Maniuz

Yes, exactly that.

**Comment by axu2** [comment]
@Maniuz 

Then use the pw 10 profile.

**Comment by Maniuz** [comment]
thank you. It works. 

If I can give an opinion as a user of the software, "Kindle PW 7/10" can be confusing because my paperwhite model is the 4 and therefore I was looking for the "Kindle PW 4" profile and not the generation number (10th)

**Comment by axu2** [comment]
Why do you call it pw4? Amazon refers to things by generation number. https://www.amazon.com/gp/help/customer/display.html?nodeId=GKMQC26VQQMM8XSW

If I called it pw4 it would confuse people looking by generation number.

**Comment by Maniuz** [comment]
> Why do you call it pw4? Amazon refers to things by generation number. https://www.amazon.com/gp/help/customer/display.html?nodeId=GKMQC26VQQMM8XSW
> 
> If I called it pw4 it would confuse people looking by generation number.


Online I often found the number associated with the model and version and the reference to the generation specified as "gen" for example "10th Gen). As reported by Wikipedia [https://en.wikipedia.org/wiki/Amazon_Kindle](https://en.wikipedia.org/wiki/Amazon_Kindle). If what you report is the type of official identification it is good to know it. Perhaps in a sense we are both not wrong.

In any case, thanks for the replies and reflections
