### ISSUE TITLE
Number of pages is significantly off on Kindle

### ISSUE THREAD

**Issue by vinhtq115** [ciromattia/kcc#777]
**Describe the bug**
I notice that the total number of pages that the Kindle displays is significantly off compared to the real number of pages in original file.

**To Reproduce**
[Test CBZ file](https://we.tl/t-zCB14XLHQn) (expire on November 24)

When converted and transferred to Kindle, the number of pages on the device is only 226. The page number in the table of contents on Kindle appears to be correct tho.

**Expected behavior**
Number of pages should be at least 350.

**Screenshots**
<img width="650" alt="Screenshot 2024-11-17 at 23 24 56" src="https://github.com/user-attachments/assets/69a640cb-f619-40f6-a941-83467f564b54">

**Desktop (please complete the following information):**
 - OS: macOS
 - Device: Kindle Paperwhite 5 Signature

**Additional context**
None

**Comment by vinhtq115** [comment]
You mean 7.0.0? I haven't tried that yet. Will report back in a few minutes.

**Comment by vinhtq115** [comment]
I tested 7.0.0 and it's the same as 6.2.2.

**Comment by axu2** [comment]
I ran it with these settings and the file works fine on my kindle. It might be another png related issue.

![image](https://github.com/user-attachments/assets/ca3ef39b-46e0-416f-97a0-abc557ba9fb7)

**Comment by vinhtq115** [comment]
How many pages does it show on your Kindle? I tried your settings and both 6.2.2 and 7.0.0 but mine always shows 226 pages while the number of pages in the original CBZ file is 359.

**Comment by vinhtq115** [comment]
Nvm, seems like Kindle also has something else called "loc" and this displays the correct number of pages.

**Comment by axu2** [comment]
I was looking at loc, where else did you see page number?

**Comment by vinhtq115** [comment]
I was looking at this number

![screenshot_2024_11_19T11_54_05+0849](https://github.com/user-attachments/assets/5283ee02-0d24-4d9a-8521-a9f841c3890c)
