### ISSUE TITLE
6.3 a problem with processing multiple files? Need K7?

### ISSUE THREAD

**Issue by NeilS007** [ciromattia/kcc#787]
On my Intel iMac I was running kcc version 6.2.2 fine to convert .cbr to .ePubs. I have not used it in a bit and today I got the message and link to pick up the new version 6.3. I installed 6.3 and immediately had a problem. When I put in more than one file to process it changed to the Editor display as always but failed with a link to the install procedure for k7. But with 6.2.2 only the Kindle Previewer 3 app had been needed to install? It is installed, so should 6.3 have detected Kindle Previewer app and have worked normally? If so, how do I make 6.3 work with it? I looked at k7 but I recall back when I first got kcc 6.2.2 that it was the first not to need k7? But is kcc now back to needing K7 and KP3 is not going to work and so I need to get k7? I hope not because K7 looks a lot harder to install. Anyway I am back to using 6.2.2 and it has no prob with processing multiple files. Still, I would rather be on new stuff. Help???

**Comment by axu2** [comment]
I assume you mean 7z?

7z is required for certain files unfortunately. Does the problematic file work in 6.2.2? @NeilS007

**Comment by NeilS007** [comment]
Ooops. Yes, I meant 7z. One more try at explaining is needed so.... Running kcc 6.2.2 with Kindle Preview 3 installed in the same folder as kcc working with multiple cbr files is very easy. Let's say I have thirty comic book files (cbr) I need to covert to epub so that send to kindle will take them. All I need do is to select all thirty cbr files and drag and drop them into kcc. I think because I have installed Kindle Preview 3 app that kcc 6.2.2  does immediately  process the thirty files one after the other into epubs. But if I install 6.3 kcc it will not work. Dragging even two cbr files into 6.3 results in an error message that I need to install 7z and a link to it. So my question is  can I setup  kcc 6.3 to work like kcc 6.2.2 does with the Kindle Preview 3 app to process multiple files and avoid the whole 7z re-setup? I appreciate your help here.

**Comment by axu2** [comment]
Can you please provide a video or screenshots of the error?

What macOS version?

Are you using kcc 6.3.1 or 7.0.0?

If you aren't using MOBI for usb transfer kindle Previewer isn't used at all.

**Comment by NeilS007** [comment]
OK, this is weird. The first two times I installed 6.3.1 I got the problem. But when I reinstalled it for a third time to do screenshots it actually worked. I have no idea if it will remain reliable. But, for now, no problem I guess. And, each install was from the same download. Well, thanks for the help and let's hope it keeps working.
